import type { SpreadPositionKey } from "./spreads";

export const CARD_POSITION_DESCRIPTIONS_B: Record<number, Partial<Record<SpreadPositionKey, string>>> = {
  26: { // Five of Wands
    "mind": "Competing thoughts crowd the stage — every idea argues for precedence, and the noise is exhausting. Identify which voice is yours before acting.",
    "body": "The body is burning off restless energy in all directions; channelled movement will serve you better than scattered exertion.",
    "spirit": "Creative friction is not spiritual failure — sometimes the soul sharpens itself on resistance. Let the conflict clarify what you actually stand for.",
    "action": "Pick one fight and win it cleanly rather than skirmishing on every front. Focus is your most potent weapon this week.",
    "the gift": "Friction and competition arrive as unlikely gifts — they reveal your edges and test the true weight of your ambitions.",
    "what to release": "The need to be right in every argument. Release the compulsion to dominate every room you enter.",
    "the seed": "Plant the intention to compete with integrity — to strive fiercely without losing sight of what the contest is actually for.",
    "the obstacle": "Scattered energies pulling against each other before they can unite; the obstacle is the war inside before the work begins.",
    "first steps": "Name the one goal that matters most this cycle, then let the lesser battles fall away unanswered.",
    "what has grown": "The heat of competition has forged a clearer sense of your own position — you know now what you will and will not defend.",
    "what is illuminated": "The light reveals where collaboration was mistaken for rivalry, and where genuine opposition still needs to be named.",
    "what hides in the light": "Beneath the clash of wands, a fear of being outpaced — check whether you are fighting others or racing a shadow of yourself.",
    "what must be released": "The exhausting need to hold every contested ground. Some battles are finished; stop returning to them.",
    "how to let go": "Lay down one argument you have been carrying past its season. The wand can be grounded without being surrendered.",
    "what emerges": "Out of the melee, a single clear purpose rises — leaner, tested, and no longer interested in fighting for its own sake.",
  },
  27: { // Six of Wands
    "mind": "The mind rides high on the back of a recent success — savour the clarity that comes from having won, and use it while it lasts.",
    "body": "Victory has a physical signature: the shoulders drop, the chest opens. Let the body feel its own triumph this week.",
    "spirit": "Recognition from others touches something deep only when the inner self has already acknowledged its own worth. Receive the praise as confirmation.",
    "action": "Step into visible leadership without apology — this week asks you to carry the torch rather than pass it prematurely.",
    "the gift": "The Six of Wands rides in bearing public recognition and the momentum of demonstrated competence.",
    "what to release": "The habit of diminishing your victories before others can. Release the reflex of false modesty.",
    "the seed": "Plant the intention to be seen — to let your accomplishments speak without being whispered or hidden.",
    "the obstacle": "Pride that tips into arrogance, or the fear that success will invite jealousy; both can unseat the victor mid-parade.",
    "first steps": "Share one achievement honestly — not as a boast, but as a marker of how far the work has come.",
    "what has grown": "The effort you invested has ripened into visible results; the harvest is being witnessed by those who matter.",
    "what is illuminated": "The full moon reveals that the recognition you craved was available all along — you were withholding it from yourself.",
    "what hides in the light": "Behind the laurels, a quiet anxiety about whether the next victory is possible. Success can conceal its own doubt.",
    "what must be released": "The crown that has served its purpose. Victory is a moment, not an identity; set it down before it becomes a cage.",
    "how to let go": "Honour what you have accomplished, then return to the ordinary work with a clear head. The parade ends; the road continues.",
    "what emerges": "A more grounded confidence — one that no longer requires the crowd's noise to sustain it.",
  },
  28: { // Seven of Wands
    "mind": "The mind is on high alert, scanning for threats from below. Make sure the height you are defending was worth climbing to.",
    "body": "A stance of perpetual readiness is draining the body's reserves — perseverance must be matched with intentional rest.",
    "spirit": "Standing your ground is a spiritual practice when what you defend is genuinely sacred. Know the difference between conviction and stubbornness.",
    "action": "Hold your position this week — clearly, without aggression. Make your boundary visible without making it a war.",
    "the gift": "The Seven of Wands brings the gift of hard-won elevation and the stubborn endurance to keep it.",
    "what to release": "The belief that every challenge to your position is a personal attack. Release some of the vigilance.",
    "the seed": "Plant the intention to defend only what truly matters — and to make your footing firmer rather than your posture more aggressive.",
    "the obstacle": "Defensiveness that prevents new information from reaching you; the high ground can become an echo chamber.",
    "first steps": "Identify what you are actually protecting this cycle — then ask whether the threat is as great as it feels.",
    "what has grown": "Your persistence has made your position solid; what once felt precarious now has roots.",
    "what is illuminated": "The full moon shows exactly how many challenges were real and how many were conjured by fear of falling.",
    "what hides in the light": "Beneath the courageous stance, exhaustion — the kind that accumulates when you have been defending alone for too long.",
    "what must be released": "The lone-sentinel posture. Some burdens require allies, and asking for help is not surrender.",
    "how to let go": "Descend the hill long enough to accept support. The ground does not fall when you are not watching it.",
    "what emerges": "A confidence that no longer needs an elevated position to feel secure — one that holds even on flat ground.",
  },
  29: { // Eight of Wands
    "mind": "Thoughts arrive fast and multiply — the mind is firing on all cylinders. Catch the best ones before they blur past.",
    "body": "The body is a current, not a container this week. Move with the momentum rather than bracing against it.",
    "spirit": "Swift passage can be a spiritual experience — things moving at speed remind the soul that stagnation was never the natural state.",
    "action": "Send the message, launch the project, make the call. The window is open and the wands are already in the air.",
    "the gift": "Swift momentum — the kind that arrives when conditions align and resistance dissolves all at once.",
    "what to release": "The hesitation that makes you check the arrow's flight after it has already left the bow.",
    "the seed": "Plant the intention of decisive, unimpeded action — let this cycle be the one where you stop stalling at the threshold.",
    "the obstacle": "Moving so fast that communication becomes noise; speed without direction scatters more than it gathers.",
    "first steps": "Pick the one initiative that has been waiting on the launchpad and commit a concrete send-by date.",
    "what has grown": "The seeds of action planted weeks ago have accelerated; what was slow is now rushing toward its destination.",
    "what is illuminated": "The full moon reveals how much was delayed not by circumstance but by an internal hand on the brake.",
    "what hides in the light": "In the exhilaration of speed, the question of destination can go unasked. Where are these eight wands actually landing?",
    "what must be released": "Unfinished communications — unread messages, unsent replies, things said halfway. Clear the queue.",
    "how to let go": "Let the arrows land. You aimed, you released; the trajectory is set and interference now only creates chaos.",
    "what emerges": "Arrival — the satisfying moment when all that swift energy finally resolves into a concrete outcome.",
  },
  30: { // Nine of Wands
    "mind": "The mind has taken hits and remembers every one of them. This week, distinguish between earned caution and paranoia masquerading as wisdom.",
    "body": "The body carries its history of effort in tension and old wounds — honour the endurance without demanding more than what remains.",
    "spirit": "Battle-worn is not broken. The spirit that has kept moving through difficulty possesses a quality that ease could never build.",
    "action": "Tend your wounds without abandoning your post. Rest is not retreat — it is the strategy that makes completion possible.",
    "the gift": "The Nine of Wands brings the gift of endurance tested and proven — a resilience that exists now because everything tried to break it.",
    "what to release": "Hypervigilance applied to threats that no longer exist. You survived the last assault; not every arrival announces another one.",
    "the seed": "Plant the intention to finish — to carry the final stretch with the same commitment that carried the first.",
    "the obstacle": "Weariness that presents as wisdom — the voice that says give up dressed in the language of self-care.",
    "first steps": "Take stock of how close the finish line actually is before deciding whether to rest or press forward.",
    "what has grown": "The cumulative effect of not quitting has become something formidable; your persistence is the harvest.",
    "what is illuminated": "The full moon shows the distance already covered — the journey back is longer than the journey forward.",
    "what hides in the light": "The fear that completion will require something you are no longer sure you have. Beneath endurance, a private doubt.",
    "what must be released": "The identity of the one who almost didn't make it. Almost is not the story anymore.",
    "how to let go": "Lower the guard slowly, not all at once. The body that has been braced for impact needs permission to soften.",
    "what emerges": "Completion — and with it, a deeply earned peace that cannot be conferred, only survived into.",
  },
  31: { // Ten of Wands
    "mind": "The mind is bowed under the weight of too many responsibilities it accepted without examining. Identify what you agreed to carry versus what was placed on you.",
    "body": "The back is speaking. The Ten of Wands asks what physical strain you are absorbing that belongs to someone or something else.",
    "spirit": "Carrying others does not make you virtuous — sometimes it makes you unavailable to your own path. Ask what the soul has been set aside to hold.",
    "action": "Put something down this week. Not everything, just the heaviest thing — the one that is not yours to carry anymore.",
    "the gift": "Even in burden, this card brings the gift of near-completion — the shore is visible, which means the crossing is almost done.",
    "what to release": "The belief that you must carry all of this alone to prove your worth. The load is not a measure of your value.",
    "the seed": "Plant the intention to redistribute what you have accumulated — to arrive at the destination with energy left to enjoy it.",
    "the obstacle": "The inability to delegate or ask for help; pride wearing the costume of responsibility.",
    "first steps": "Write down every obligation you are currently carrying. Circle the ones that are not yours by right or by choice.",
    "what has grown": "The willingness to carry heavy things has grown into a habit of over-extension. The harvest here is the clarity to stop.",
    "what is illuminated": "The full moon reveals how much you have been carrying in secret — and who in your life has been watching without offering a hand.",
    "what hides in the light": "Under the strain, a quiet martyrdom — the part of you that needs the load to feel necessary.",
    "what must be released": "The extra weight. Something specific — a role, a project, a promise made past its usefulness — must be set down now.",
    "how to let go": "Carry the bundle to the door and leave it on the step. The act is simple even when the emotional permission is not.",
    "what emerges": "Uprightness — the spine finding itself again once the carried weight is lifted, and the vision returning with it.",
  },
  32: { // Page of Wands
    "mind": "The mind is lit up by a new idea, eager and unpolished. Let the excitement run before editing it — the refinement can come later.",
    "body": "There is a youthful fire in the body's cells this week — kinetic, restless, looking for an outlet. Give it direction before it turns to fidgeting.",
    "spirit": "The spirit of the Page of Wands is pure creative appetite — the soul remembering how it felt to want something just because it was interesting.",
    "action": "Begin the thing you have been exploring in theory. The Page does not need a full plan — it needs a first move.",
    "the gift": "Fresh creative fire and the magnetic enthusiasm that makes new beginnings possible — the gift of the beginner's mind.",
    "what to release": "The self-consciousness that kills curiosity before it becomes action. Release the need to look like you know what you are doing.",
    "the seed": "Plant the intention to follow a creative impulse without demanding it justify itself first.",
    "the obstacle": "Enthusiasm without follow-through — the risk that the flame burns bright and brief if structure never arrives to hold it.",
    "first steps": "Explore the idea through a first experiment: a sketch, a conversation, a single afternoon of uncommitted play.",
    "what has grown": "A message, a signal, a creative spark that arrived earlier in the cycle has grown into something worth serious attention.",
    "what is illuminated": "The full moon reveals that the new direction you dismissed as too naive or too small is actually pointing toward something real.",
    "what hides in the light": "Beneath the bright enthusiasm, a terror of failing at something you care about — newness is also vulnerability.",
    "what must be released": "The early draft that has been held too close. The Page's message needs to be sent, not clutched.",
    "how to let go": "Hand the creative thing over — publish, share, submit. What is held in draft forever never becomes what it was meant to be.",
    "what emerges": "A nascent creative identity — the first outline of a maker who is beginning to take their own fire seriously.",
  },
  33: { // Knight of Wands
    "mind": "The mind is charging ahead without checking whether the map is current. Passion is real; direction may need recalibration.",
    "body": "The body wants to move fast and far — honour that energy while building in checkpoints before exhaustion arrives unannounced.",
    "spirit": "The Knight of Wands reminds the spirit that desire is sacred, and that bold action taken from genuine passion is its own form of prayer.",
    "action": "Charge toward the thing you want this week — but pick one direction and hold it instead of galloping toward every horizon at once.",
    "the gift": "Fearless momentum and the magnetic pull of someone who moves from genuine passion rather than obligation.",
    "what to release": "Recklessness that calls itself courage. Release the habit of confusing speed with progress.",
    "the seed": "Plant the intention to pursue what excites you with the whole of your energy — not most of it, all of it.",
    "the obstacle": "Impulsivity that overcommits before resources are in place; enthusiasm that outruns follow-through.",
    "first steps": "Set a destination before accelerating. The Knight's energy is extraordinary — give it a worthy target.",
    "what has grown": "Bold action taken earlier has ripened into visible results; what you charged toward is now within reach.",
    "what is illuminated": "The full moon reveals whether the adventure you launched was genuinely yours or borrowed from someone else's idea of excitement.",
    "what hides in the light": "Beneath the charged forward motion, a fear of stillness — of what arises when the Knight finally stops moving.",
    "what must be released": "The half-begun adventure that you have circled back to three times without finishing. Ride it to its end or let it go entirely.",
    "how to let go": "Turn the horse and choose the direction deliberately. Release the scattered quests to pursue the one that burns brightest.",
    "what emerges": "A matured fire — passion that has learned to sustain itself past the first exhilarating sprint.",
  },
  34: { // Queen of Wands
    "mind": "The mind is warm and expansive this week — curious, generous, capable of seeing potential where others see obstacle.",
    "body": "The body is the Queen's throne; occupy it fully. Presence is physical first — shoulders back, voice carrying, warmth radiated outward.",
    "spirit": "The Queen of Wands is the spirit that refuses to make itself small for anyone's comfort. Let that sovereign energy rise.",
    "action": "Lead from warmth this week — hold the vision and invite others into it rather than commanding or pleading.",
    "the gift": "Magnetic creative authority — the rare combination of genuine confidence and genuine care that draws others naturally into your orbit.",
    "what to release": "The habit of shrinking your fire to avoid outshining. Your brightness does not diminish anyone else's.",
    "the seed": "Plant the intention to lead a project or space from your authentic creative self — not performing competence, embodying it.",
    "the obstacle": "Creative dominance that forgets to listen; confidence that shades into control and stops inviting collaboration.",
    "first steps": "Stand at the centre of your chosen domain this week — claim the room, the project, the creative territory that is yours to lead.",
    "what has grown": "The creative confidence you have been tending has reached full bloom; others are now drawn to your warmth rather than you seeking theirs.",
    "what is illuminated": "The full moon reveals the full scope of your influence — wider and warmer than you have allowed yourself to believe.",
    "what hides in the light": "The shadow of the Queen: creative possessiveness, a need to be the brightest flame that can, unchecked, char what it means to nourish.",
    "what must be released": "The creative project or role that once energised you but now only demands your fire without returning it.",
    "how to let go": "Pass the torch deliberately — not in defeat, but in the confident knowledge that your warmth creates more warmth, not less.",
    "what emerges": "A creative legacy — work that carries your particular fire forward even after you have moved on to a new burning.",
  },
  35: { // King of Wands
    "mind": "The mind operates from vision this week — seeing the whole arc rather than the immediate step, holding the end-state with steady clarity.",
    "body": "The King's body carries authority without strain. This week, inhabit your physical presence as if leadership were a posture, not just a title.",
    "spirit": "Mature fire is not less powerful for being controlled — the King of Wands embodies the spirit that has learned to direct its own intensity.",
    "action": "Make the visionary decision that has been waiting for someone with the authority to make it. That someone is you.",
    "the gift": "Entrepreneurial mastery and the rare capacity to inspire without coercion — the gift of a will that others willingly follow.",
    "what to release": "The reactive, impulsive fire that belongs to the Knight. Release the volatility that interferes with the vision.",
    "the seed": "Plant the intention to lead from your deepest creative conviction — to build something that outlasts the immediate season.",
    "the obstacle": "Overbearing vision that leaves no room for other perspectives; the King who has forgotten that a kingdom requires its people.",
    "first steps": "Define the vision for this cycle in writing — not a task list, but the true destination you are building toward.",
    "what has grown": "Leadership you once doubted in yourself has grown into something others recognise and respond to without prompting.",
    "what is illuminated": "The full moon reveals which of your ambitions are truly yours and which were inherited from someone else's version of success.",
    "what hides in the light": "The shadow king: domination dressed as vision, rigidity dressed as principle — check for the places where fire has become control.",
    "what must be released": "The empire that has outgrown its original purpose. Some thrones are ready to be vacated so the next thing can be built.",
    "how to let go": "Hand the dominion over with ceremony — naming a successor, completing the transition, letting the thing stand without your constant tending.",
    "what emerges": "A new creative frontier — the King who has nothing left to prove is finally free to build the one thing that was always the true work.",
  },
  36: { // Ace of Cups
    "mind": "The mind is softening at the edges — receptive, open, willing to be moved by beauty and connection in ways it recently forgot were possible.",
    "body": "The body is a cup this week: notice what fills it and what empties it. Something tender is beginning.",
    "spirit": "The Ace of Cups is the soul's original state — love offered freely, before experience taught it to calculate the risk.",
    "action": "Open to something new in the emotional realm this week. Allow what is being offered; receive it without immediately asking what it means.",
    "the gift": "A fresh emotional beginning — love, compassion, or creative flow arriving like rain into a vessel that has been waiting.",
    "what to release": "The heart's armour that kept necessary things out alongside unnecessary ones. Release one layer of the calcification.",
    "the seed": "Plant the intention to love — something, someone, some creative work — with your whole heart and without a contingency plan.",
    "the obstacle": "Fear of being overwhelmed; the cup held at arm's length because what it contains feels like too much.",
    "first steps": "Identify the one relationship, creative project, or practice that your heart has been quietly reaching toward and move one step closer.",
    "what has grown": "An emotional opening you allowed earlier in the cycle has grown into something nourishing — the cup is fuller than you knew.",
    "what is illuminated": "The full moon reveals the depth of your capacity for love and connection — deeper than your fears have been willing to admit.",
    "what hides in the light": "Beneath the open heart, the grief of previous cups that were dropped or taken. Receiving is harder when you remember the last spill.",
    "what must be released": "Emotional guardedness that has become a habit of deprivation. The cup that is never filled is also never shared.",
    "how to let go": "Let yourself be moved — by a conversation, a piece of music, an act of unexpected tenderness. Permission to feel is the practice.",
    "what emerges": "A new relationship with your own emotional life — more fluent, more willing, more capable of the deep joy that only openness allows.",
  },
  37: { // Two of Cups
    "mind": "The mind is drawn toward another — genuinely curious, genuinely open, thinking about connection as a two-way current rather than a transaction.",
    "body": "Mirroring is physical before it is conscious; notice where your body relaxes in the presence of one particular other.",
    "spirit": "The soul recognises its counterpart not through logic but through resonance — a hum that starts in the chest before the mind catches up.",
    "action": "Meet someone with full reciprocity this week — offer what you have and receive what they bring without keeping score.",
    "the gift": "Mutual recognition — the rare electric moment when two people see each other clearly and choose connection anyway.",
    "what to release": "Transactional patterns in relationship — the ledger of who gave what and when. Release the accounting.",
    "the seed": "Plant the intention to build one relationship this cycle on the foundation of genuine equality — no hierarchy, no rescue, just two cups touching.",
    "the obstacle": "The fear of losing yourself in union; the cup that refuses to touch another's for fear of contamination.",
    "first steps": "Make a gesture of genuine reciprocity — not grand, but real. Something offered freely to someone you respect.",
    "what has grown": "A connection you have been tending has matured into something balanced and sustaining — the two cups are no longer circling, they are still.",
    "what is illuminated": "The full moon reveals what you have been contributing to this bond versus what you have been withholding, and what the other has offered in return.",
    "what hides in the light": "Beneath the harmony, a question about whether both parties are truly equal, or whether one cup is always a fraction more full.",
    "what must be released": "The unequal footing that has been masquerading as partnership. Release the dynamic in which one cup is always fuller than the other.",
    "how to let go": "Part with gratitude, naming what was real. The Two of Cups at its end is still a ceremony — endings deserve the same care as beginnings.",
    "what emerges": "A new capacity for equal partnership — more clear-eyed, more deliberate, no longer willing to settle for connection that only runs in one direction.",
  },
  38: { // Three of Cups
    "mind": "The mind is lifted by the people around it this week. Let others' perspectives in — your thinking will be enriched by the exchange.",
    "body": "The body wants to be in community, to be fed and seen and surrounded by warmth. Make room for this need; it is not indulgence.",
    "spirit": "Joy in the company of others is a spiritual practice the solitary path sometimes forgets. The Three of Cups asks you to let yourself be celebrated.",
    "action": "Gather with people who genuinely delight in your presence. Celebrate something — a milestone, a season, a simple day that deserves marking.",
    "the gift": "The effervescent gift of community joy — abundance that multiplies in the sharing and diminishes when hoarded.",
    "what to release": "Isolated striving. Release the belief that celebration must be earned before it can be permitted.",
    "the seed": "Plant the intention to build or strengthen a circle of support — people who show up for each other in the small moments as well as the large.",
    "the obstacle": "Superficiality in celebration; the gathering that stays at the level of performance without ever touching real connection.",
    "first steps": "Initiate a gathering, however small — a shared meal, an invitation, a signal to your community that you are present and open.",
    "what has grown": "The seeds of friendship and collective joy have produced a real harvest; there are people now who will come when called.",
    "what is illuminated": "The full moon reveals who actually shows up — who is present in the circle when things are genuinely worth celebrating.",
    "what hides in the light": "Under the collective warmth, a quieter loneliness — the part that wonders whether the celebration would continue if you weren't doing the organising.",
    "what must be released": "The social obligation that has become a drain. Not all community is nourishing; some gatherings are merely habitual.",
    "how to let go": "Step back from the circle that no longer feeds you. Gratitude is possible without continued membership.",
    "what emerges": "A richer, more intentional community — smaller perhaps, but genuinely held, capable of bearing weight as well as celebrating.",
  },
  39: { // Four of Cups
    "mind": "The mind has turned inward and is no longer registering what is being offered from outside. Check whether the withdrawal is necessary contemplation or avoidance.",
    "body": "Stillness has become the body's default; there is a flatness, a low hum of restlessness in disguise. Gentle movement may unlock what sitting has not.",
    "spirit": "The soul sometimes needs to rest behind closed eyes. The Four of Cups asks whether your withdrawal is deepening you or merely deferring the discomfort.",
    "action": "Look up from your contemplation long enough to notice what is being extended toward you. One cup is being offered; it deserves examination.",
    "the gift": "The gift of the pause — the space between stimulus and response where deeper knowing sometimes arrives quietly.",
    "what to release": "Emotional apathy that mistakes itself for wisdom. Release the boredom that is actually a defence against disappointment.",
    "the seed": "Plant the intention to be genuinely receptive — to enter this cycle with eyes open rather than arms folded.",
    "the obstacle": "Withdrawal as self-protection; the cup that sits just out of view while you contemplate the three that no longer satisfy.",
    "first steps": "Notice what has gone unacknowledged at the edge of your awareness — the offer, the person, the opportunity that arrived quietly.",
    "what has grown": "A period of internal reflection has produced genuine insight; the contemplation was not wasted, even if it felt static.",
    "what is illuminated": "The full moon reveals the cup that was being extended all along — and whether the refusal was about the cup or the fear of accepting.",
    "what hides in the light": "Behind the meditative posture, dissatisfaction hunting for something it cannot name — a discontent that no cup, however beautiful, seems to answer.",
    "what must be released": "The dissatisfied vigil. Let go of waiting for the perfect offer while ignoring the real one.",
    "how to let go": "Open your eyes and your hand. The release is not dramatic — it is simply a small, deliberate act of receiving.",
    "what emerges": "Renewed appetite — desire returning after a period of numbness, and with it, the capacity to actually want what is being given.",
  },
  40: { // Five of Cups
    "mind": "The mind is cataloguing what has been lost and has not yet turned to survey what remains. Both inventories need to be taken before anything real can be decided.",
    "body": "Grief settles in the body before it reaches words — notice where you are held, guarded, or unexpectedly heavy.",
    "spirit": "The soul's capacity to mourn is the same capacity that loves. The Five of Cups does not ask you to stop grieving — it asks you not to stop there.",
    "action": "Acknowledge what spilled. Then, when you are ready, turn around and look at what is still standing.",
    "the gift": "The gift of honest grief — the clearing that becomes possible when loss is neither rushed through nor wallowed in indefinitely.",
    "what to release": "The three spilled cups. Release the continuous return to what cannot be recovered — not in denial, but in completion.",
    "the seed": "Plant the intention to carry what remains into the new cycle with honesty and care, rather than as a consolation prize.",
    "the obstacle": "Grief that has calcified into identity — the person who can only be defined by what they have lost.",
    "first steps": "Name one thing that has remained intact through the loss. Give it specific attention — not as distraction, but as recalibration.",
    "what has grown": "The work of grief, done with courage and care, has produced something unexpected: a deeper appreciation for what survived.",
    "what is illuminated": "The full moon reveals the two cups still standing behind you — and whether you have been willing to look at them.",
    "what hides in the light": "Under the visible grief, the guilt of the survivor: why did these two remain? What does it mean that you still have them?",
    "what must be released": "The cloak of mourning that has been worn past its season. The loss was real; the duration of the vigil is now a choice.",
    "how to let go": "Walk toward the bridge and the village lights beyond it. The act of moving forward is not a betrayal of what was lost.",
    "what emerges": "A reclaimed life — built deliberately from what endured, carrying the memory of loss without being defined by it.",
  },
  41: { // Six of Cups
    "mind": "Memory is visiting this week — not as haunting but as medicine. The mind can be nourished by what it has known and loved.",
    "body": "The body holds the memory of safety and simple pleasure. This week, let yourself return to a comfort that is genuinely yours.",
    "spirit": "Innocence is not something lost forever — it is a quality the soul can revisit with permission. Let the child-self teach something.",
    "action": "Return to something — a place, a practice, a relationship — with open eyes and genuine tenderness, not to escape but to be restored.",
    "the gift": "The gift of sweet memory and the nourishment that comes from knowing you have been loved and have loved well.",
    "what to release": "Nostalgia that functions as escape — the past as a place to live rather than a place to learn.",
    "the seed": "Plant the intention to carry forward the specific joy from an earlier chapter — not to recreate it, but to let its essence inform what is being built.",
    "the obstacle": "Sentimentality that resists the present; the pull of the past becoming an anchor that keeps the future from arriving.",
    "first steps": "Reach out to something or someone from an earlier, happier chapter of your life — with no agenda beyond genuine reconnection.",
    "what has grown": "The care you planted in earlier seasons — for yourself, for others — has come back to you in a form you didn't expect.",
    "what is illuminated": "The full moon reveals which threads from your past are still living and generative, and which ones are only memory.",
    "what hides in the light": "Under the warmth of nostalgia, a grief for the self you were before difficulty arrived and changed the shape of things.",
    "what must be released": "The version of the past that has been idealized into something the present cannot compete with.",
    "how to let go": "Honour the memory with gratitude, then let it take its proper size — real, meaningful, but not larger than the present.",
    "what emerges": "A renewed gentleness — a self that has been restored by memory and is now ready to make new ones.",
  },
  42: { // Seven of Cups
    "mind": "The mind is flooded with options, visions, possibilities — some luminous, some illusory, and the Seven of Cups does not label which is which.",
    "body": "The body is restless with unexpressed desires; without discernment, it will reach for whatever glitters closest. Slow down before choosing.",
    "spirit": "Fantasy is the soul's first language, but it was meant to lead toward incarnation, not to replace it. Ask which vision will survive contact with reality.",
    "action": "Choose one cup and investigate it seriously before adding another option to the array. Discernment is this week's practice.",
    "the gift": "An embarrassment of creative possibilities — the gift of a richly imagining mind, even when it needs grounding.",
    "what to release": "Magical thinking that excuses inaction. Release the comfort of options that are never actually pursued.",
    "the seed": "Plant the intention to discern — to examine each desire not for its shimmer but for its substance.",
    "the obstacle": "Overwhelm and paralysis masquerading as abundance; so many visions that none of them can become real.",
    "first steps": "Pick the one option that, if you set all the others aside, you would most regret not pursuing. Begin there.",
    "what has grown": "A richly imagined inner life that is now demanding expression. The visions have been incubating long enough.",
    "what is illuminated": "The full moon reveals the illusions in the cup array — which desires are genuinely yours and which are borrowed fantasies.",
    "what hides in the light": "Under the shimmering possibilities, the fear of commitment — of choosing one path and closing the others forever.",
    "what must be released": "The cups you are keeping in reserve as escape hatches. Release the fantasy that prevents the real from being built.",
    "how to let go": "Set down the cups one by one until only the truest one remains. The letting go is mostly an act of honesty.",
    "what emerges": "A focused creative vision — stripped of its more fantastical ornaments, but finally capable of being made real.",
  },
  43: { // Eight of Cups
    "mind": "The mind has quietly completed its assessment. What once held fascination no longer does, and the honest response to that knowledge is preparation to leave.",
    "body": "The body already knows the direction. Notice which way it orients when the decision is held lightly — that is the real answer.",
    "spirit": "The soul is a traveller, and some of its deepest callings arrive as a turning away from what once satisfied. This is not abandonment; it is answering.",
    "action": "Walk toward what calls you rather than staying for what is merely familiar. One deliberate step in the new direction is enough for now.",
    "the gift": "The rare courage of leaving something whole rather than waiting for it to fall apart — the gift of trusting that a deeper fulfilment exists.",
    "what to release": "The eight cups you have arranged carefully but no longer drink from. Release the investment in what has genuinely run its course.",
    "the seed": "Plant the intention to seek what your current life cannot give you — not as an escape, but as an honest act of self-direction.",
    "the obstacle": "Guilt and obligation that keep you circling the assembled cups rather than moving on. The leaving feels like a betrayal it is not.",
    "first steps": "Name what you are walking toward, not just what you are leaving behind. The Eight of Cups needs both halves of the equation.",
    "what has grown": "The quiet knowing that began as a faint restlessness has grown into an undeniable summons. You have been preparing for this departure.",
    "what is illuminated": "The full moon makes clear that the emotional architecture you have built no longer fits the shape of who you are becoming.",
    "what hides in the light": "Beneath the dignified departure, sadness — these cups were real and they mattered, even if they are no longer enough.",
    "what must be released": "The life that fitted a former self. It was built with care; it deserves to be left with the same.",
    "how to let go": "Turn your back on the arranged cups deliberately, without drama, and move into the dark. The journey is the point, not the destination.",
    "what emerges": "A self stripped of what no longer served — lighter, less defined by accumulation, and genuinely in motion toward something true.",
  },
  44: { // Nine of Cups
    "mind": "The mind is satisfied in a way it rarely allows itself to be. Receive the contentment without immediately looking for the catch.",
    "body": "The body is in a season of ease and pleasure. Let this be real — the Nine of Cups asks you to enjoy what you have rather than cataloguing what is still missing.",
    "spirit": "The wish granted reveals what the wishing was actually for. The soul's satisfaction is complete when what arrived matches what was wanted at the deepest level.",
    "action": "Savour what has been fulfilled this week — not in complacency, but in genuine appreciation. Gratitude is an action, not just an attitude.",
    "the gift": "The Nine of Cups arrives as wish fulfillment — the generous confirmation that what you reached for was genuinely reachable.",
    "what to release": "The habit of deferring satisfaction — of insisting the cup must be overflowing before it is allowed to be called enough.",
    "the seed": "Plant the intention to feel deeply fulfilled rather than provisionally content — to let satisfaction be a real state rather than a dangerous one.",
    "the obstacle": "Complacency that stops growth; the contentment that says this is enough and then begins to defend the status quo rather than build on it.",
    "first steps": "Identify one specific desire that has been fulfilled this cycle and mark it consciously — not to move on immediately, but to let it land.",
    "what has grown": "The emotional abundance you cultivated has become visible fruition; the wish is not approaching, it is here.",
    "what is illuminated": "The full moon reveals the full satisfaction available to you — and the degree to which you have been willing to receive it.",
    "what hides in the light": "The shadow of the Nine of Cups: self-satisfaction that has stopped asking questions, comfort that no longer wants to be challenged.",
    "what must be released": "The unfulfilled desires that have already been answered but not acknowledged. Let the wish-keeping end.",
    "how to let go": "Close the chapter of wanting this particular thing. It has arrived. The release is an act of grateful completion.",
    "what emerges": "A new capacity for desire — more refined, clearer about what truly satisfies, and no longer willing to settle for the glittering approximation.",
  },
  45: { // Ten of Cups
    "mind": "The mind can rest in the knowledge that the emotional life is genuinely well-founded. This is not naivety — it is the result of real work and real love.",
    "body": "The body is held in a web of belonging. Let it feel the full physical reality of being supported, surrounded, and at home.",
    "spirit": "Complete happiness is not the absence of complexity — it is the presence of love sufficient to hold the complexity. The soul recognises this as home.",
    "action": "Name your belonging aloud this week. Tell the people in your arc what they mean to you — do not let the completion pass without being spoken.",
    "the gift": "Lasting emotional happiness — the arc of the heart reaching its completion in love that is genuinely held and genuinely whole.",
    "what to release": "The belief that happiness at this scale is temporary, borrowed, or requires immediate defence. Release the pre-emptive grief.",
    "the seed": "Plant the intention to build the life that matches the vision of the Ten of Cups — not as a fantasy, but as a practical commitment to what matters.",
    "the obstacle": "Idealism that sets the bar so high that real, available love goes unrecognised because it does not glow exactly as imagined.",
    "first steps": "Take one concrete step toward the emotional home you are building — a conversation, a gesture, a commitment made visible.",
    "what has grown": "The emotional foundation laid in earlier seasons has reached its fullness. The rainbow above the family is not a symbol — it is a report.",
    "what is illuminated": "The full moon reveals the love that was always present — and the moments when you almost missed it by looking for something more spectacular.",
    "what hides in the light": "Under the harmony, the individual sacrifices that made the whole possible. Each person in the arc gave something up; this deserves acknowledgment.",
    "what must be released": "The longing for the Ten of Cups life to be elsewhere, later, larger. It is here. Release the deferral.",
    "how to let go": "Let the cycle of striving be complete. The happiness that is here does not need to be improved before it is allowed to be called enough.",
    "what emerges": "A new chapter that begins from genuine fullness rather than from lack — a rarer and more powerful starting point.",
  },
  46: { // Page of Cups
    "mind": "The mind is dreaming — soft-edged, open to the strange and the intuitive. Follow the image that surfaces; it is not random.",
    "body": "The body is speaking in the language of sensation and impulse. Something felt, not thought, is worth paying close attention to this week.",
    "spirit": "The Page of Cups is the soul in its most receptive state — the vessel before it learns to guard against what it feels. Let that openness breathe.",
    "action": "Follow the creative or emotional impulse without analysing it to death first. The fish in the cup jumped out to say something; listen.",
    "the gift": "The gift of emotional openness and the surprising creative messages that arrive when the heart is undefended.",
    "what to release": "Emotional sophistication that has become a distance — the heart armoured in irony, too wise to be moved.",
    "the seed": "Plant the intention to receive inspiration with genuine wonder — to let what arrives in dreams and impulses be taken seriously.",
    "the obstacle": "Naivety that confuses emotional impressionability with emotional truth; not every feeling is a message, and discernment still applies.",
    "first steps": "Record the dream, the image, the strange impulse. Before analysis, just catch what is arriving and write it down.",
    "what has grown": "An emotional sensitivity that was once a vulnerability has grown into a genuine perceptual gift.",
    "what is illuminated": "The full moon reveals the creative and emotional signals that have been arriving in the quiet — the messages you were not quite ready to hear.",
    "what hides in the light": "Behind the tender openness, a fear of being mocked for feeling too much or imagining too freely.",
    "what must be released": "Emotional information you have been sitting on — the feeling, the creative response, the vulnerable message that has not been sent.",
    "how to let go": "Share what you have been feeling with someone who has earned the trust. The release is the expression.",
    "what emerges": "A deepened creative and emotional vocabulary — a self that has learned to honour its own sensitivity as a source of intelligence.",
  },
  47: { // Knight of Cups
    "mind": "The mind is tilted toward romance this week — toward the ideal, the beautiful, the version of things as they might be at their most luminous.",
    "body": "The body moves at the pace of desire, not of duty. Let it be drawn toward what it loves and give that movement some actual room.",
    "spirit": "The Knight of Cups is the soul that follows the Grail — not because it knows where it leads, but because the call itself is holy.",
    "action": "Pursue the emotional or creative ideal that has been drawing you. Make a gesture toward what you love — grand or small, it must be genuine.",
    "the gift": "Romantic idealism and the capacity to pursue the heart's vision with charm and genuine conviction.",
    "what to release": "The pursuit that has become all gesture and no arrival. Release the Knight who prefers the romantic quest to the actual relationship.",
    "the seed": "Plant the intention to pursue emotional beauty with the courage to arrive — to let the ideal touch the actual.",
    "the obstacle": "Idealisation that cannot survive contact with reality; the pursuit of a feeling rather than a person, a project, or a truth.",
    "first steps": "Make a specific, concrete approach toward what you have been circling romantically or creatively. Proximity, not fantasy.",
    "what has grown": "The emotional pursuit you began earlier in the cycle has brought you within reach. The cup is close enough now to touch.",
    "what is illuminated": "The full moon reveals whether what you have been riding toward is a real destination or a beautiful direction that was always the point.",
    "what hides in the light": "Beneath the romantic ideal, the avoidance of ordinary intimacy — real love has difficult texture that the Knight's vision smooths over.",
    "what must be released": "The romantic quest that has replaced genuine commitment. The Grail was never meant to be only searched for.",
    "how to let go": "Arrive. Set the horse still, hold out the cup, and let what you have been seeking come to rest in your hands.",
    "what emerges": "A more grounded love — one that has survived the transition from pursuit to presence and is richer for the landing.",
  },
  48: { // Queen of Cups
    "mind": "The mind is quietly receiving this week — less analysis, more listening. Trust what comes from below the surface before you explain it.",
    "body": "The body is a tuning fork; it will tell you what is true in a room before your mind has formed a theory. Trust the resonance.",
    "spirit": "The Queen of Cups holds the entire ocean of feeling without drowning in it. This week, the soul's task is the same: feel fully, without being lost.",
    "action": "Offer your emotional intelligence to someone who needs it. Your empathy is not passive — it is one of the most powerful actions available to you.",
    "the gift": "Deep empathy and the capacity to sit with what is true without flinching — the gift of someone who holds the feeling until it becomes wisdom.",
    "what to release": "Emotional enmeshment — the tendency to feel so deeply into another's experience that the boundary between theirs and yours dissolves.",
    "the seed": "Plant the intention to be a safe harbour for the emotional life — yours and others' — in this cycle.",
    "the obstacle": "The inability to move from feeling to action; compassion that absorbs without responding, love that empathises without speaking.",
    "first steps": "Sit with one person's difficulty this cycle — not to fix it, but to be genuinely present with it. Then see what the presence makes possible.",
    "what has grown": "Your capacity for compassionate witnessing has grown into something others come to instinctively, knowing they will be held rather than judged.",
    "what is illuminated": "The full moon reveals the emotional current running beneath the surface of your relationships — what everyone is actually feeling beyond what is being said.",
    "what hides in the light": "The Queen's shadow: absorbing others' emotions as a way of avoiding your own. Whose feelings are you actually sitting with?",
    "what must be released": "The emotional dynamic in which your empathy is given without limit and rarely returned. This is care, but it is not balance.",
    "how to let go": "Allow your own cup to be tended. Receive care as skillfully as you give it — the Queen who can only pour is running dry.",
    "what emerges": "A more boundaried compassion — deeper, strangely, for having learned that it cannot be infinite and remain clean.",
  },
  49: { // King of Cups
    "mind": "The mind is calm in rough water this week. Emotional intelligence is the highest cognitive capacity — let it lead rather than following logic's insistence.",
    "body": "The body holds the emotional storm without being capsized by it. This week, that stability is a resource to be offered to others.",
    "spirit": "The King of Cups knows the depths of feeling and is not afraid of them. The soul's maturity is measured not by what it doesn't feel, but by what it doesn't lose itself in.",
    "action": "Lead with compassionate authority this week — hold the emotional container for those around you without absorbing their chaos as your own.",
    "the gift": "Emotional mastery — not the suppression of feeling, but the wise sovereignty over how feeling is expressed and directed.",
    "what to release": "Emotional suppression that presents as control. Release the calm that is actually distance, not depth.",
    "the seed": "Plant the intention to govern your emotional life with both wisdom and warmth — to be neither controlled by feeling nor disconnected from it.",
    "the obstacle": "Emotional rigidity that calls itself stability; the King who has ruled so long he has forgotten the water moves beneath the throne.",
    "first steps": "In one charged situation this week, choose the measured response rather than the reactive one — and notice what that makes possible.",
    "what has grown": "Emotional intelligence that once required effort has become instinct; the calm in difficult situations is now genuine, not performed.",
    "what is illuminated": "The full moon reveals how much others depend on your emotional steadiness — and what it costs you when they don't acknowledge it.",
    "what hides in the light": "The King's shadow: emotional control that shades into emotional unavailability — the unreadable face that no one can reach.",
    "what must be released": "The role of the emotionally reliable one who must never have needs. The King on his throne is still a person with a heart.",
    "how to let go": "Allow someone to hold space for you. Emotional maturity includes the capacity to be witnessed, not only to witness.",
    "what emerges": "A fuller emotional authority — one that includes vulnerability as a component of genuine strength rather than an exception to it.",
  },
  50: { // Ace of Swords
    "mind": "Something cuts through: a clarity that has been building finally arrives and the mental fog parts. This is the week to think the thought you have been avoiding.",
    "body": "The Ace of Swords in the body is a sharpening — heightened alertness, quickened perception. The nervous system is ready. Direct it consciously.",
    "spirit": "Truth is the Ace of Swords' only mercy. The soul that has been waiting in confusion is given, at last, the precise word that names what is real.",
    "action": "Name the truth that has been circling without landing. Speak it with precision and without cruelty — the sword is for clarity, not for cutting.",
    "the gift": "Mental breakthrough — a clarity so clean it feels like a gift from outside yourself, though it was forming in you all along.",
    "what to release": "The comfortable ambiguity that let you avoid deciding. Release the fog that has been a kind of permission to stay undecided.",
    "the seed": "Plant the intention to found this lunar cycle on one clear, unflinching truth — not a resolution, but an honest assessment.",
    "the obstacle": "The truth that, once spoken, cannot be unspoken and changes the shape of things. The sword hesitates at the threshold.",
    "first steps": "Write the sentence you have not been willing to say clearly. One sentence. Hold it and see if it is real.",
    "what has grown": "The clarity you were reaching toward has grown into genuine understanding. You know something now that you only suspected before.",
    "what is illuminated": "The full moon reveals the precise contour of what has been true all along — the thing that was visible in peripheral vision but never faced directly.",
    "what hides in the light": "Beneath the breakthrough, the losses that clarity creates: the relationship that cannot survive the truth, the story that must be rewritten.",
    "what must be released": "The old mental framework that no longer fits what you know. The sword does not mourn the head it clears — it completes the act.",
    "how to let go": "Speak the truth once, clearly, to the right person. The release is the sentence, not the aftermath.",
    "what emerges": "A new way of thinking — stripped of the comfort of ambiguity, but finally capable of building something solid on honest ground.",
  },
  51: { // Two of Swords
    "mind": "The mind holds two equally weighted truths in suspension and refuses to choose between them. This stalemate is not stupidity — but it cannot be permanent.",
    "body": "The body braces under the weight of an unresolved decision. The jaw, the shoulders — notice where the indecision is being held physically.",
    "spirit": "The blindfold is not always denial; sometimes it is a necessary pause before a decision that will require everything. Know which one this is.",
    "action": "Gather the one piece of information you have been refusing to look at. The blindfold was a protection; the time for its removal is approaching.",
    "the gift": "The peace of the pause — the suspended state that allows both truths to be fully known before a choice is made that cannot be unmade.",
    "what to release": "The pretence that not choosing is not a choice. Release the false neutrality that is quietly choosing the status quo.",
    "the seed": "Plant the intention to make one suspended decision during this cycle — not impulsively, but with the deliberate arrival of the time to choose.",
    "the obstacle": "The refusal to obtain the information that would resolve the stalemate, because knowing would require acting.",
    "first steps": "Lower one sword. Not both — just one. See which option becomes clearer when only half the defence is maintained.",
    "what has grown": "The period of deliberate suspension has grown into a genuine understanding of both sides. You are more informed than you were; the blindfold has done its work.",
    "what is illuminated": "The full moon removes the blindfold entirely — the water behind the figure is revealed, and with it, the scale of the decision that has been held in suspension.",
    "what hides in the light": "Under the composed stillness of the Two of Swords, a fear of the inevitable rupture — choosing means someone or something loses, and you are not yet ready to be the one who chose.",
    "what must be released": "The crossed swords. The defence posture is complete; holding it past its purpose transforms protection into isolation.",
    "how to let go": "Set both swords down at once — not into the water, but onto solid ground. The decision may not have arrived, but the defensive holding can end now.",
    "what emerges": "Movement — the first current of new direction after the long stillness. Whatever comes next, it will come from having finally looked.",
  },
};
