import type { SpreadPositionKey } from "./spreads";

export const CARD_POSITION_DESCRIPTIONS_C: Record<number, Partial<Record<SpreadPositionKey, string>>> = {
  52: { // Three of Swords
    "mind": "Your thoughts are circling a wound that is real. Name it precisely and it loses some of its power over you.",
    "body": "Grief does not stay in the heart — it settles in the chest, the throat, the shoulders. Give the body permission to feel what the mind has been managing.",
    "spirit": "The spirit does not require you to be fine. This week it asks only that you be honest about what has been broken.",
    "action": "Say the difficult thing you have been avoiding. The truth, once spoken, begins its work.",
    "the gift": "This lunar cycle brings the clarity that only pain can produce. What you discover will be worth the ache.",
    "what to release": "The story that the sorrow is permanent. Grief clarifies; it does not define.",
    "the seed": "Plant the intention to mourn well — to let the loss move through you rather than around you.",
    "the obstacle": "The temptation to skip over grief into resolution. The seed needs rain before it needs sun.",
    "first steps": "Acknowledge to yourself — in writing, in speech, in silence — what has actually hurt. This is not weakness; it is honesty.",
    "what has grown": "The hard-won knowledge of what you value. Pain has a way of burning away what doesn't matter.",
    "what is illuminated": "A truth you already knew but were not ready to see. The three swords do not invent the wound — they simply make it visible.",
    "what hides in the light": "The relief buried underneath the sorrow. Some grief contains a secret freedom.",
    "what must be released": "The illusion that was shattered. It served you once; it cannot serve you now.",
    "how to let go": "Mourn it fully rather than managing it. The wound needs to be felt, not solved.",
    "what emerges": "A more honest heart. What comes after real grief is not innocence — it is clarity.",
  },
  53: { // Four of Swords
    "mind": "Your mind needs stillness more than it needs answers this week. Stop processing for long enough to simply rest.",
    "body": "The body is asking for more sleep, more quiet, more horizontal time. This is not laziness — it is repair.",
    "spirit": "The spirit recovers in silence. What looks like withdrawal is actually integration.",
    "action": "Schedule real rest and protect it fiercely. Not recreation — restoration.",
    "the gift": "This cycle offers a truce with yourself. The battle can pause.",
    "what to release": "The belief that rest must be earned. Stillness is not a reward — it is a practice.",
    "the seed": "Plant the intention to replenish before the next push begins. Stillness now is power later.",
    "the obstacle": "The guilt that arrives when you stop moving. The Four of Swords asks you to sit with it rather than flee it.",
    "first steps": "Choose one day this cycle for deliberate withdrawal — no obligations, no outputs, no performance of productivity.",
    "what has grown": "Perspective. The distance that rest creates between you and your problems is a kind of wisdom.",
    "what is illuminated": "How much you have been running on fumes. The full moon shows what the frantic pace concealed.",
    "what hides in the light": "The fear underneath the busyness. Stillness threatens to reveal it. Let it.",
    "what must be released": "The exhaustion you have been performing as diligence. You are allowed to stop.",
    "how to let go": "Lay it down physically. The body knows how to release what the mind keeps picking back up.",
    "what emerges": "A calmer mind and a clearer sense of what actually needs your energy. Stillness is diagnostic.",
  },
  54: { // Five of Swords
    "mind": "Your mind is replaying a conflict and calculating who was right. The calculation is costing more than the original fight.",
    "body": "Victory that hollows you out is not victory. Notice where the body is still clenched around a win that didn't feel like one.",
    "spirit": "The spirit asks: what was the point of winning if this is how it feels? Let the question sit without deflection.",
    "action": "Choose connection over being right. Walk back onto the field, this time without the sword raised.",
    "the gift": "This cycle brings the chance to examine your relationship with conflict. The gift is uncomfortable and real.",
    "what to release": "The need to win cleanly in a situation that was never going to be clean. Some victories require you to leave something on the ground.",
    "the seed": "Plant the intention to compete with integrity — to want outcomes that you can actually live inside.",
    "the obstacle": "Your own pride. The Five of Swords does not hide its shadow — it holds it up and asks you to name it.",
    "first steps": "Reach out to someone you've been keeping at sword's length. You don't have to concede — just open.",
    "what has grown": "The knowledge of your own capacity for ruthlessness. This is not a condemnation — it is information.",
    "what is illuminated": "The ethical cost of a past choice. The full moon shows what the heat of the moment concealed.",
    "what hides in the light": "The loneliness of the winner left standing on an empty field. Even the sword knows.",
    "what must be released": "The justification you've been carrying for a wound you inflicted. Set it down — not to abandon accountability, but to stop weaponizing it.",
    "how to let go": "Admit, privately and without drama, what you wish you had done differently. That admission is its own form of release.",
    "what emerges": "A more honest sense of what you actually want — from conflict, from relationships, from yourself.",
  },
  55: { // Six of Swords
    "mind": "Your mind is crossing toward quieter water. The turbulence is not behind you yet, but the direction has changed.",
    "body": "The body is moving away from something that was draining it. Give it time to recalibrate to safety.",
    "spirit": "The spirit is mid-passage — between the life that was and the life being built. Honour the in-between.",
    "action": "Keep moving. The destination does not need to be clear; it only needs to be calmer than where you left.",
    "the gift": "This cycle offers passage — the transition energy that carries you through without demanding that you figure everything out first.",
    "what to release": "The belief that you must fully understand where you're going before you go. The boat moves; the map comes later.",
    "the seed": "Plant the intention to leave with intention — to move away from difficulty as a choice, not a flight.",
    "the obstacle": "The grief of departure. You can be glad to be leaving and still mourn what the leaving costs.",
    "first steps": "Identify the one thing you are moving away from, and take one visible step in the opposite direction.",
    "what has grown": "The courage to choose a different shore. You did not have to go. You went anyway.",
    "what is illuminated": "What you are actually leaving behind. The full moon illuminates the swords still in the boat — the past travels with you.",
    "what hides in the light": "The fear that the new shore will disappoint you the way the old one did. That fear is worth examining.",
    "what must be released": "The situation, relationship, or habit whose difficulty you have been explaining rather than leaving.",
    "how to let go": "Step into the boat. The act of moving is itself the release — not the resolution of everything, just the departure.",
    "what emerges": "Calmer water. Not a perfect destination — calmer water, and the knowledge that you chose it.",
  },
  56: { // Seven of Swords
    "mind": "Your mind is working several angles at once. Check that the strategy you're building is one you can live with.",
    "body": "The body knows when it is being asked to operate on half-truths. Notice if you feel tight, watchful, ready to bolt.",
    "spirit": "Cunning has its place. The question the spirit is asking is whether this particular cunning is in service of something real.",
    "action": "Be more direct than feels comfortable. The long way around this will cost more than the short way through.",
    "the gift": "This cycle brings tactical intelligence — the ability to see all the angles before committing.",
    "what to release": "The habit of withholding the full truth from people who could handle it. Partial honesty accumulates interest.",
    "the seed": "Plant the intention to be more transparent than feels strategically optimal. The disclosure is the seed.",
    "the obstacle": "Your own cleverness. The Seven of Swords warns that the sharpest mind in the room can still outsmart itself.",
    "first steps": "Identify one thing you have been withholding — from a person, from yourself — and decide what it would mean to stop.",
    "what has grown": "Your capacity to see what others miss. The problem is not the perception — it is what you choose to do with it.",
    "what is illuminated": "A deception that has been running quietly in the background. Not necessarily someone else's. Possibly yours.",
    "what hides in the light": "The loneliness of never being fully known because you have always shown only what you chose to show.",
    "what must be released": "The posture of keeping your options open at the cost of genuine commitment.",
    "how to let go": "Put down one sword you were carrying covertly. Just one. See what happens.",
    "what emerges": "The unexpected relief of being known. Transparency costs something — and then it gives something back.",
  },
  57: { // Eight of Swords
    "mind": "The prison you are describing is largely constructed from thoughts. That is not a dismissal — it is a doorway.",
    "body": "The body is more capable of moving than the mind is currently willing to believe. Start small. Start anywhere.",
    "spirit": "The spirit is not trapped. It has been waiting patiently inside the story of entrapment, ready to walk out.",
    "action": "Remove one bandage. Not all of them — one. See what you can actually see without it.",
    "the gift": "This cycle brings the uncomfortable but liberating recognition that the restriction is not fully external.",
    "what to release": "The narrative that circumstances are entirely beyond your influence. That story is the blindfold.",
    "the seed": "Plant the intention to take one action you have been saying is impossible. Even a small one.",
    "the obstacle": "The fear that if you remove the blindfold, the swords will be even more real than the darkness suggested.",
    "first steps": "Write down the belief that is keeping you still. Then write one sentence that genuinely challenges it.",
    "what has grown": "Survival. You have endured the constraint — now the question is whether you will remain in it by choice.",
    "what is illuminated": "The precise nature of the story you've been telling about your own limitations. The full moon makes its shape clear.",
    "what hides in the light": "The identity built around the imprisonment. If you are not the captive, who are you?",
    "what must be released": "The helplessness you have been rehearsing. It has felt like honesty — it has also been a habit.",
    "how to let go": "Take one step. Not a leap — one step, with the swords still around you, in a direction you have been saying is closed.",
    "what emerges": "Agency. Small at first, then larger. The Eight of Swords cannot survive the first real step.",
  },
  58: { // Nine of Swords
    "mind": "What is tormenting you at 3am is real distress but not reliable prophecy. The mind is not a good fortune teller in the dark.",
    "body": "Sleep, breath, and basic physical care are medicine here. The anxiety is in the body before it becomes thoughts — tend the body first.",
    "spirit": "The spirit is not in danger, even when the mind insists otherwise. Underneath the spiral there is something still and steady. That steadiness is you.",
    "action": "Do not make decisions from inside the spiral. Ground, wait, and then decide.",
    "the gift": "This cycle brings the surfacing of what has been grinding away beneath awareness. What is here is not new — it is finally visible.",
    "what to release": "The belief that worry is preparation. Most of what the Nine of Swords predicts does not happen.",
    "the seed": "Plant the intention to interrupt the spiral consciously — not to suppress it, but to choose when and how you engage it.",
    "the obstacle": "The spiral itself. It will resist being named. Name it anyway.",
    "first steps": "Write down the specific fear that is running loudest. Outside of the mind, it is always smaller.",
    "what has grown": "Sensitivity — the kind that makes you perceptive and the kind that makes you sleepless. Both are true.",
    "what is illuminated": "The shape of your particular anxiety. Not abstract dread — specific fear, with specific contours, now visible.",
    "what hides in the light": "The need underneath the worry. Anxiety is almost always grief or fear of loss wearing a different coat.",
    "what must be released": "The catastrophic narrative your mind has been rehearsing. It has not come true. Release it.",
    "how to let go": "Do the thing you have been dreading. In almost every case, the doing is gentler than the anticipating.",
    "what emerges": "Quiet. Not the silence before a disaster — the silence after the imagined disaster was survived.",
  },
  59: { // Ten of Swords
    "mind": "The worst has happened — or close enough. The mind can stop bracing now. What follows the bottom is up.",
    "body": "The body has been through something. Rest is not surrender — it is the first step of recovery.",
    "spirit": "The spirit has survived. It is prone on the ground with ten swords in its back and it is still, improbably, breathing. That is the card.",
    "action": "Do not try to rise too quickly. Acknowledge the ending fully before you move toward what comes next.",
    "the gift": "This cycle brings completion. It is brutal completion, but completion is the gift — nothing more to dread because what you dreaded has arrived.",
    "what to release": "Whatever you were desperately trying to save that is now over. It is over. The release is already happening.",
    "the seed": "Plant the intention to begin again — not immediately, but when the ground has had time to absorb what was lost.",
    "the obstacle": "The temptation to explain the ending rather than experience it. The ten swords do not require a story. They require honesty.",
    "first steps": "Let today be the day you stop. Stop fighting what is already finished. One full breath of acknowledgment.",
    "what has grown": "The undeniable evidence that you can survive what you were sure would destroy you. You are surviving it.",
    "what is illuminated": "The exact nature of the ending — no softening, no ambiguity. The full moon shows the field clearly. This is done.",
    "what hides in the light": "The beginning. The Ten of Swords is always a sunrise card, even with the darkness still in the frame.",
    "what must be released": "Everything. This is the total clearing — the card that asks for complete surrender because complete surrender is what the moment requires.",
    "how to let go": "Stop resisting the ending. The swords are already in. The resistance is the only thing still hurting you.",
    "what emerges": "Dawn. Always, and without exception, after the Ten of Swords: dawn.",
  },
  60: { // Page of Swords
    "mind": "Your mind is sharp, curious, and collecting information at high speed this week. Be careful what you do with what you find.",
    "body": "Nervous energy is running high. The body needs somewhere to put the alertness — movement, breath, something physical and quick.",
    "spirit": "The spirit is in a watching phase, not a knowing phase. Stay curious. The understanding is still incoming.",
    "action": "Ask the question you have been circling. Then listen with genuine openness rather than waiting to respond.",
    "the gift": "This cycle brings fresh perception — the ability to see clearly, ask sharply, and move before the moment closes.",
    "what to release": "The performance of certainty. The Page of Swords does not know yet, and that not-knowing is actually an asset.",
    "the seed": "Plant the intention to investigate something you have been taking on faith. New information changes everything.",
    "the obstacle": "Vigilance that tips into suspicion. The Page's sharp eyes can also find threats that aren't fully there.",
    "first steps": "Start the research. Gather the data. Ask the person. The Page does not wait for permission to be informed.",
    "what has grown": "Discernment — the ability to read a situation quickly and accurately. Trust this skill more.",
    "what is illuminated": "A detail that changes the picture. Something small has become something significant under the full moon's light.",
    "what hides in the light": "The anxiety beneath the alertness. The Page watches because watchfulness feels like safety.",
    "what must be released": "The half-formed information you have been treating as fact. This is not the moment for provisional conclusions.",
    "how to let go": "Release the need to have the full picture before you act. Move with what you have.",
    "what emerges": "Clarity. Not complete certainty — the Page never offers that — but the first clean line of understanding.",
  },
  61: { // Knight of Swords
    "mind": "Your mind has locked onto something and is moving at full speed. Check the direction before the velocity becomes irreversible.",
    "body": "The body is primed for action — possibly over-primed. Channel the intensity or it will channel itself.",
    "spirit": "The spirit admires conviction. It also asks: is this conviction in service of truth, or only in service of being right?",
    "action": "Charge — but not blindly. Choose the thing most worth your ferocity and spend it there.",
    "the gift": "This cycle brings the energy of total commitment. The Knight of Swords does not do things halfway. Neither will you.",
    "what to release": "Arguments you've been having in your head with people who are not present. The Knight needs a real adversary.",
    "the seed": "Plant the intention to act decisively on a conviction you have been hedging. The moment for caution has passed.",
    "the obstacle": "The tendency to mistake speed for accuracy. Going fast is not the same as going right.",
    "first steps": "Make the decision you have been indefinitely postponing. The Knight does not dither. Neither should you.",
    "what has grown": "Courage. The willingness to move toward difficulty rather than away from it is a real and earned capacity.",
    "what is illuminated": "The target. Whatever you have been building toward, the full moon shows it clearly now. Go.",
    "what hides in the light": "The collateral damage of the charge. The Knight of Swords moves fast and sometimes does not notice who was in the way.",
    "what must be released": "The hesitation that has been wearing the costume of prudence. You know what to do.",
    "how to let go": "Move. The release is in the action — not in thinking about the action or preparing for the action, but in the doing.",
    "what emerges": "Resolution. The Knight of Swords does not leave things unfinished. What begins now will complete.",
  },
  62: { // Queen of Swords
    "mind": "Your mind is at its clearest when you stop trying to make the truth more palatable. This week, let it be what it is.",
    "body": "The body responds to honesty the way it responds to clean air. Clarity is a physical relief.",
    "spirit": "The spirit has been refined by difficulty into something precise and strong. Do not apologize for it.",
    "action": "Tell the truth — calmly, clearly, without cruelty but without softening. The Queen of Swords does not lie.",
    "the gift": "This cycle brings the gift of discernment — the capacity to see clearly what others prefer to blur.",
    "what to release": "The kindness that has become enabling. Protecting people from truth is not compassion.",
    "the seed": "Plant the intention to call things by their real names this lunar cycle. Clarity is a form of respect.",
    "the obstacle": "The coldness that creeps in when clarity becomes detachment. Truth without care is a blade without a handle.",
    "first steps": "Identify one place where you have been less than fully honest to spare someone's feelings. Consider what honesty there would actually cost.",
    "what has grown": "Wisdom — not the inherited kind, but the kind forged in loss and refined into precision.",
    "what is illuminated": "What you have been seeing clearly all along but were not fully letting yourself act on. The full moon confirms it.",
    "what hides in the light": "The grief the Queen has metabolized to become this clear. Her clarity is earned; behind it is everything she has survived.",
    "what must be released": "The performance of uncertainty to seem more approachable. You know what you see. Trust it.",
    "how to let go": "Name the ending. Speak the conclusion. The Queen of Swords does not drag out what is already finished.",
    "what emerges": "Integrity — a life lived in closer alignment with what you actually see and believe.",
  },
  63: { // King of Swords
    "mind": "Your mind is operating at the level of principle this week — not just tactics, but ethics, systems, and what is actually just.",
    "body": "The King of Swords governs well partly by knowing when to rest the body that holds the mind. Tend the instrument.",
    "spirit": "The spirit asks that the mind's authority be held in service of something beyond the self. Precision is a gift; arrogance is its shadow.",
    "action": "Make the decision that is right, not only the one that is convenient. The King of Swords does not govern by preference.",
    "the gift": "This cycle brings clear governance — the capacity to make just decisions and communicate them without flinching.",
    "what to release": "The impulse to wield intelligence as a weapon. The King's sword is for precision, not punishment.",
    "the seed": "Plant the intention to apply your clearest thinking to a situation you have been avoiding for emotional reasons.",
    "the obstacle": "Intellectual rigidity. Certainty can calcify into dogma if it is not held with a degree of humility.",
    "first steps": "Define the principle at stake in a current dilemma. Name it explicitly. Then act from it.",
    "what has grown": "Authority — the earned kind, the kind that others recognize before you claim it.",
    "what is illuminated": "The correct course of action in a situation that has been clouded by competing feelings. The King shows the line.",
    "what hides in the light": "The emotional cost of always leading from logic. The King of Swords feels more than the sword admits.",
    "what must be released": "Judgment that has become condemnation. Cut clean — then put the sword down.",
    "how to let go": "Issue the verdict and release the case. The King does not revisit what has been justly decided.",
    "what emerges": "Order — not imposed from outside, but chosen and maintained from a place of genuine understanding.",
  },
  64: { // Ace of Pentacles
    "mind": "Your mind is recognizing a real opportunity. The pragmatic thought you keep dismissing deserves more attention.",
    "body": "Something in the material world is inviting you in — a new practice, a new physical discipline, a new way of inhabiting daily life.",
    "spirit": "The spirit does not separate the sacred from the material. What is being offered here is also an offering to what is most alive in you.",
    "action": "Accept the tangible opportunity. Say yes to the thing that requires actual doing in the actual world.",
    "the gift": "This cycle brings a seed of material abundance — a beginning that, tended well, will grow into something real.",
    "what to release": "The belief that spiritual depth requires material scarcity. The earth is sacred. So is the gift being offered in it.",
    "the seed": "Plant an intention that has a physical form: a savings goal, a creative project, a health practice, a business idea.",
    "the obstacle": "Waiting for the perfect conditions to begin. The Ace of Pentacles does not wait — it arrives.",
    "first steps": "Identify the one concrete action that would begin the material thing you have been dreaming about. Take it this week.",
    "what has grown": "A foundation. What has been built quietly in the physical dimension of your life is more real than you have acknowledged.",
    "what is illuminated": "The value of what you have already built. The Ace arrives into soil that has been prepared — the preparation is visible now.",
    "what hides in the light": "The discomfort with receiving material abundance. Some people are more comfortable with longing than with having.",
    "what must be released": "The poverty mindset that has been operating beneath awareness, treating security as something that happens to other people.",
    "how to let go": "Open the hand. Receive what is being given without immediately calculating what it will cost.",
    "what emerges": "The first shoot. The beginning of something that will, in time, become solid ground.",
  },
  65: { // Two of Pentacles
    "mind": "Your mind is tracking multiple priorities and doing better than it thinks it is. The trick is not to add more.",
    "body": "The body needs rhythm more than it needs more effort. Find a sustainable cadence and protect it.",
    "spirit": "The spirit does not ask for stillness right now — it asks for grace in motion. The dance is the practice.",
    "action": "Prioritize ruthlessly. You cannot carry everything with equal attention. Choose what gets the most of you.",
    "the gift": "This cycle brings the energy of adaptability — the capacity to stay in motion without losing balance.",
    "what to release": "The idea that you will reach a point where everything is managed. The Two of Pentacles is not a temporary state.",
    "the seed": "Plant the intention to do fewer things better rather than more things adequately.",
    "the obstacle": "The juggler's addiction to adding another ball. Know when enough is in the air.",
    "first steps": "Write down everything you are currently managing. Identify one item that is genuinely optional. Set it down.",
    "what has grown": "Flexibility. You have become more resourceful under constraint than you realize.",
    "what is illuminated": "How much is actually in motion — the full complexity of what you are managing comes clear under the full moon.",
    "what hides in the light": "The exhaustion underneath the competent juggling. The figure in the card is smiling, but watch the eyes.",
    "what must be released": "One commitment that is no longer worth the energy it requires. You know which one it is.",
    "how to let go": "Remove one ball from the air intentionally. Notice that the rest continue moving without it.",
    "what emerges": "A more sustainable rhythm. Not less ambition — less chaos.",
  },
  66: { // Three of Pentacles
    "mind": "Your mind is being asked to collaborate rather than operate alone. The best thinking is happening in dialogue right now.",
    "body": "The body thrives with other bodies — shared labor, shared space, the particular energy of work done together.",
    "spirit": "The spirit recognizes that what is built with others is different in kind from what is built alone. That difference is the point.",
    "action": "Bring someone else in. The thing you have been building in isolation is ready for another perspective.",
    "the gift": "This cycle brings the gift of genuine collaboration — the alchemy that happens when distinct skills are brought to bear on the same thing.",
    "what to release": "The reluctance to share credit or show unfinished work. Collaboration requires vulnerability before it produces excellence.",
    "the seed": "Plant the intention to build something with another person rather than for them or despite them.",
    "the obstacle": "The belief that working alone is purer or more efficient. Sometimes it is. This time, it isn't.",
    "first steps": "Identify the collaborator you have been reluctant to approach. Make the ask.",
    "what has grown": "A shared project with real structural integrity — something that exists because more than one person put themselves into it.",
    "what is illuminated": "The specific contribution you make that others cannot replicate. Your distinctness is the gift you bring to the collaboration.",
    "what hides in the light": "The ego friction that good collaboration always eventually surfaces. See it clearly; it doesn't have to stop the work.",
    "what must be released": "The role of the expert who already knows. In this cycle, be the learner in the room.",
    "how to let go": "Trust the other builders. Release the specific vision of how it must be done and discover what it wants to become.",
    "what emerges": "Something better than any one of you could have made alone. That is what the Three of Pentacles promises.",
  },
  67: { // Four of Pentacles
    "mind": "Your mind is oriented toward security. Check whether the grip is protective or whether it has become the problem.",
    "body": "The body is holding. Tension in the jaw, the hands, the gut — the physical expression of not letting go.",
    "spirit": "The spirit does not thrive inside a closed fist. Enough is real; hoarding is a different thing.",
    "action": "Release one resource you have been guarding more than using. Let it move.",
    "the gift": "This cycle brings the energy of consolidation — a chance to assess what you have and decide what is truly worth protecting.",
    "what to release": "The security that has become a cage. The Four of Pentacles knows the difference between a foundation and a fortress.",
    "the seed": "Plant the intention to hold resources with open hands — enough to steward them, not enough to choke them.",
    "the obstacle": "Fear. Specifically, the fear that if you release your grip, everything will be taken from you.",
    "first steps": "Give something away — time, money, attention, knowledge — that you have been holding back. Note that you survive the giving.",
    "what has grown": "A foundation. What you have conserved and protected is real and present. Acknowledge it.",
    "what is illuminated": "The inventory of what you actually have versus what you fear losing. The full moon often shows that the two lists are different.",
    "what hides in the light": "The control underneath the conservation. Some hoarding is about safety; some is about power.",
    "what must be released": "Something you have been holding past its usefulness — out of habit, out of fear, out of the feeling that having it proves something.",
    "how to let go": "Open the hands slowly. You do not have to release everything at once. One thing. Then assess.",
    "what emerges": "The surprising lightness that comes from holding less. The Four of Pentacles, released, becomes the Six.",
  },
  68: { // Five of Pentacles
    "mind": "Your mind is in scarcity mode — fixated on what is lacking, missing what is present. This is a distortion to gently correct.",
    "body": "The body has been neglected or pushed past what it can sustain. Material needs are not shameful — they are real.",
    "spirit": "The spirit in winter still exists. The warmth is closer than the cold makes it seem. Look for the light in the window.",
    "action": "Ask for help. The Five of Pentacles is a card of unnecessary solitary suffering. Someone can help if you let them.",
    "the gift": "This cycle brings the humbling and clarifying experience of need — the knowledge of what you actually require to be okay.",
    "what to release": "The pride that is keeping you from accepting what is being offered. The people inside the church did not lock the door.",
    "the seed": "Plant the intention to reach for support rather than endure in silence. This is not weakness — it is wisdom.",
    "the obstacle": "The shame that has attached itself to the hardship. The difficulty is real; the shame is optional.",
    "first steps": "Contact the resource, the person, or the institution that can actually help with the material problem you've been managing alone.",
    "what has grown": "Resilience, yes — but also a catalogue of what you can endure. The question now is whether endurance is still required.",
    "what is illuminated": "The nature of the scarcity — whether it is material, relational, spiritual, or some combination. The full moon names it precisely.",
    "what hides in the light": "The community that has been present and available, waiting for you to turn toward it.",
    "what must be released": "The identity of the person in hardship. It has been real. It is not permanent. Let it go.",
    "how to let go": "Accept the help that is being offered. Receiving is the practice here.",
    "what emerges": "Warmth. The Five of Pentacles released is not luxury — it is basic, real, necessary warmth.",
  },
  69: { // Six of Pentacles
    "mind": "Your mind is working through questions of fairness, reciprocity, and what you actually owe and are owed. These questions deserve honest attention.",
    "body": "The body is involved in the exchange — whether you are giving your physical energy, receiving support, or both. Track what flows.",
    "spirit": "The spirit asks: is the exchange you are part of genuinely mutual, or is it secretly transactional in a way that costs both people?",
    "action": "Give generously in the place you have been withholding. Or: receive graciously in the place you have been refusing.",
    "the gift": "This cycle brings the energy of right relationship with giving and receiving — the flow that is neither hoarding nor depletion.",
    "what to release": "The giving that comes from guilt rather than abundance. That kind of giving exhausts the giver and subtly diminishes the receiver.",
    "the seed": "Plant the intention to create one genuinely balanced exchange in your life — something that nourishes both parties.",
    "the obstacle": "The discomfort of equal footing. Many people are more comfortable in the role of giver or receiver than in real mutuality.",
    "first steps": "Identify whether you are currently playing one role exclusively. Take one step toward balance.",
    "what has grown": "Generosity — the real kind, rooted in enough, freely given, without strings.",
    "what is illuminated": "The power dynamics in your giving and receiving. The full moon shows who holds the scales and whether they are balanced.",
    "what hides in the light": "The conditions attached to the gift. Even generous people sometimes give in ways that bind.",
    "what must be released": "Charity that comes from a need to feel superior, or dependency that comes from a need to feel cared for.",
    "how to let go": "Give without tracking the return. Or: ask for what you need without apologizing for the need.",
    "what emerges": "A more honest economy — of time, attention, money, care — that sustains everyone inside it.",
  },
  70: { // Seven of Pentacles
    "mind": "Your mind is doing the slow work of long-term thinking. Stay in this mode — the quick returns will come, but first: patience.",
    "body": "The body is in a maintenance phase. Water it, rest it, keep it moving steadily. This is how gardens grow.",
    "spirit": "The spirit is asking you to trust the timeline. What is growing is growing. It does not need you to dig it up to check.",
    "action": "Assess honestly. Stand back from the work and evaluate what is actually growing versus what you hoped would grow.",
    "the gift": "This cycle brings the long view — the capacity to tend something that will not bear fruit immediately.",
    "what to release": "The demand for immediate return on a long-term investment. The vine does not respond to urgency.",
    "the seed": "Plant the intention to work on something whose payoff is years away. The Seven of Pentacles honors this kind of faith.",
    "the obstacle": "Impatience. The card is about the pause before the harvest — and the pause is harder than the planting.",
    "first steps": "Identify the long-term project you have been neglecting because it doesn't pay off yet. Give it an hour this week.",
    "what has grown": "More than you have been acknowledging. Stand back and look at what has actually accumulated.",
    "what is illuminated": "The real state of the investment — what is thriving, what is struggling, and what needs to be cut back.",
    "what hides in the light": "The doubt that has been quietly eating at the long-term faith. It is normal. Name it and return to the tending.",
    "what must be released": "The crop you have been tending past its season. Some things are ready to harvest and leave behind.",
    "how to let go": "Harvest what is ready. Do not leave it on the vine past its moment out of sentiment.",
    "what emerges": "Fruit. The real, material, tangible result of sustained effort. It was always coming — it is here now.",
  },
  71: { // Eight of Pentacles
    "mind": "Your mind is in a mode of focused repetition — practicing, refining, building mastery one iteration at a time. This is what it is supposed to feel like.",
    "body": "The body learns through repetition. Whatever skill you are building, the body is keeping score. Trust the accumulation.",
    "spirit": "The spirit honors dedication. The sacred is in the work itself — not in the finished product, but in the returning.",
    "action": "Show up to the craft. Not inspired, not energized necessarily — just present, doing the work again.",
    "the gift": "This cycle brings the energy of diligence — the unglamorous, essential work of getting better through sustained practice.",
    "what to release": "The expectation that mastery should feel different from this. This is what mastery feels like: another repetition.",
    "the seed": "Plant the intention to develop one skill through deliberate, patient practice this lunar cycle.",
    "the obstacle": "Boredom. The Eight of Pentacles is not an exciting card. Neither is mastery, most of the time.",
    "first steps": "Begin the practice session you have been putting off. Thirty minutes. One more iteration.",
    "what has grown": "Skill — genuine, measurable, earned. The work has been accumulating even when it didn't feel like it.",
    "what is illuminated": "How far you have actually come. The full moon shows the whole arc of the work, not just the current session.",
    "what hides in the light": "The perfectionism that has been masquerading as high standards. Sometimes the Eight of Pentacles gets stuck in refinement.",
    "what must be released": "The unfinished work you have been polishing indefinitely instead of completing. Done is a form of mastery too.",
    "how to let go": "Ship it. Submit it. Show it. The release from the workshop into the world is part of the practice.",
    "what emerges": "Competence — the solid, reliable, earned kind. It does not announce itself. It simply works.",
  },
  72: { // Nine of Pentacles
    "mind": "Your mind is arriving at a genuine sense of your own sufficiency. Let that recognition land fully.",
    "body": "The body has been the instrument of the effort — give it now the reward of pleasure, ease, and the sensory enjoyment it has earned.",
    "spirit": "The spirit is savoring. There is no spiritual practice more underrated than the full enjoyment of what you have built.",
    "action": "Receive your own abundance. Not with guilt, not with plans for what comes next — just receive it.",
    "the gift": "This cycle brings the gift of earned autonomy — the particular satisfaction of a life made by your own effort and judgment.",
    "what to release": "The habit of immediately setting the next goal before fully inhabiting the current achievement.",
    "the seed": "Plant the intention to enjoy what you have built before building more. The garden deserves to be walked in.",
    "the obstacle": "The discomfort with sufficiency. Some people are more at home in striving than in having.",
    "first steps": "Identify one area of your life where you have genuinely arrived, and spend deliberate time appreciating it this week.",
    "what has grown": "Self-reliance — not the armored kind, but the rooted kind. You know you can provide for yourself.",
    "what is illuminated": "The abundance that has been quietly accumulating. The full moon shows what the busy doing obscured.",
    "what hides in the light": "The loneliness that can live alongside independence. The Nine of Pentacles is glorious and solitary. Both are true.",
    "what must be released": "The relentless forward motion that has prevented you from standing in what you have made.",
    "how to let go": "Put down the project. Walk in the garden. The next beginning can wait one moment longer.",
    "what emerges": "Satisfaction — the real kind, the kind that doesn't need to be justified or immediately traded for ambition.",
  },
  73: { // Ten of Pentacles
    "mind": "Your mind is thinking in generational terms — not just what serves you now, but what will endure. This is the right scale for what you are building.",
    "body": "The body is part of a lineage. What you do now with your physical health will be felt downstream. Tend the inheritance.",
    "spirit": "The spirit recognizes that belonging to something larger than the self is not diminishment — it is rootedness.",
    "action": "Invest in something that outlasts you. A relationship, a practice, a foundation, a teaching.",
    "the gift": "This cycle brings the energy of legacy — the possibility of building something that endures past the moment of its making.",
    "what to release": "The fear that stability is boring. The Ten of Pentacles knows that enduring things are built in the unglamorous middle.",
    "the seed": "Plant the intention to create something with longevity — a practice, a project, a relationship — that serves future versions of yourself and perhaps others.",
    "the obstacle": "The weight of family or generational patterns that have been inherited rather than chosen. Legacy cuts both ways.",
    "first steps": "Identify one concrete thing you want to be present in your life ten years from now. Take one action toward it today.",
    "what has grown": "A life that has accumulated meaning, connection, and material sufficiency. Stand in it for a moment.",
    "what is illuminated": "The full picture of what has been built — not just the current project, but the whole life that surrounds it.",
    "what hides in the light": "The inherited wound alongside the inherited wealth. Family systems carry both, and both are visible now.",
    "what must be released": "What was passed down that no longer serves — habits, beliefs, patterns that belong to a generation before yours.",
    "how to let go": "Name the pattern clearly. Choose differently. That choice, repeated, becomes the new inheritance.",
    "what emerges": "A foundation — for yourself, for those who come after, for the life you are actively choosing to build.",
  },
  74: { // Page of Pentacles
    "mind": "Your mind is in beginner mode — studious, attentive, taking nothing for granted. This is exactly the right orientation for what you are learning.",
    "body": "The body is a learner too. Whatever new physical practice or discipline you are approaching, give it the Page's patient attention.",
    "spirit": "The spirit is grounded. The Page of Pentacles kneels in the earth and takes the time to understand what is actually there.",
    "action": "Study the thing you have been wanting to understand. Give it serious, sustained attention rather than a quick overview.",
    "the gift": "This cycle brings the gift of beginner's mind in the material realm — the capacity to approach resources, skills, and practical matters with genuine openness.",
    "what to release": "The shame of not already knowing. The Page has not failed by being new — that is the position from which all mastery begins.",
    "the seed": "Plant the intention to learn one practical skill from scratch this lunar cycle, with full patience for the difficulty of beginning.",
    "the obstacle": "The tendency to stay in research mode indefinitely. At some point the Page must begin to practice, not just to study.",
    "first steps": "Enroll in the course, read the first chapter, make the first appointment, take the first lesson. Begin.",
    "what has grown": "Curiosity about the physical world — how things work, how things are made, what is possible with sustained practical attention.",
    "what is illuminated": "The specific gap in practical knowledge that has been holding you back. The full moon names it without judgment.",
    "what hides in the light": "The perfectionism that keeps beginners from ever showing their beginner's work. The Page must be seen trying.",
    "what must be released": "The pretense of expertise. In this area, you are new. That is not a problem — it is information.",
    "how to let go": "Ask the obvious question. The one you have been too proud to ask because it reveals how much you don't know.",
    "what emerges": "Competence in its earliest, most promising form — the first genuine understanding of how the material works.",
  },
  75: { // Knight of Pentacles
    "mind": "Your mind is methodical this week — patient, thorough, unwilling to cut corners. Trust this slower tempo.",
    "body": "The body responds to regularity. The Knight of Pentacles does not sprint — it maintains a reliable, sustainable pace.",
    "spirit": "The spirit is present in the repeated ordinary act. Devotion, in the Knight's understanding, looks a lot like showing up again.",
    "action": "Do the reliable thing. Not the inspired thing, not the audacious thing — the reliable thing, done well, on time.",
    "the gift": "This cycle brings the energy of steadiness — the capacity to do what needs to be done without needing it to be exciting.",
    "what to release": "The restlessness that makes you want to pivot before the current direction has had time to prove itself.",
    "the seed": "Plant the intention to be the most reliable version of yourself in one important domain this lunar cycle.",
    "the obstacle": "The slowness that tips into stubbornness. The Knight of Pentacles can become immovable when movement is exactly what is needed.",
    "first steps": "Identify the task that keeps getting deferred because it is slow and unglamorous. Schedule it for tomorrow.",
    "what has grown": "Trust — the quiet, accumulated kind, built through consistent follow-through over time.",
    "what is illuminated": "How much of your current stability is the product of past reliability. The full moon shows the whole road.",
    "what hides in the light": "The yearning for something more dramatic underneath the methodical exterior. The Knight feels this too.",
    "what must be released": "The approach that has become routine past the point of usefulness. Reliability is a virtue; ruts are not.",
    "how to let go": "Finish. Complete the thing. The Knight of Pentacles does not abandon work — it completes it and then evaluates.",
    "what emerges": "Progress — measurable, material, undeniable. Not fast. Real.",
  },
  76: { // Queen of Pentacles
    "mind": "Your mind is thinking practically and generously at once — how to make the material conditions of life better, for yourself and for others.",
    "body": "The body is home. The Queen of Pentacles knows that a well-tended body is the foundation of everything else.",
    "spirit": "The spirit is domestic in the deepest sense — it makes sacred what it tends to. Everything you touch this week can be an act of care.",
    "action": "Create comfort. For yourself, for your home, for the people in your care. The Queen does not neglect the immediate.",
    "the gift": "This cycle brings the energy of warm resourcefulness — the capacity to make abundance out of what is present.",
    "what to release": "The self-neglect that has been masquerading as generosity. You cannot pour from an empty cup — the Queen knows this.",
    "the seed": "Plant the intention to tend your own material life — your home, your body, your finances — with the same care you give others.",
    "the obstacle": "The tendency to give until depleted without replenishing. The Queen of Pentacles is generous because she is also well-fed.",
    "first steps": "Do one act of domestic care this week — cook a real meal, clean the space you live in, buy yourself something nourishing.",
    "what has grown": "A life that feels like home. The Queen's gift is that she makes wherever she is into somewhere worth being.",
    "what is illuminated": "The abundance that has been present and unacknowledged. The full moon shows the full pantry, the full heart.",
    "what hides in the light": "The exhaustion of being the one who holds everyone's material life together. The Queen tends; she also needs tending.",
    "what must be released": "The overextension — the way the practical care of others has been crowding out the care you owe yourself.",
    "how to let go": "Receive. Let someone else bring the meal, tend the space, hold the weight for a moment. The Queen can be held.",
    "what emerges": "Replenishment — the feeling of a self that has been fed and is now genuinely able to feed others.",
  },
  77: { // King of Pentacles
    "mind": "Your mind is operating at the level of stewardship — thinking about what you have, what it produces, and how to make it last.",
    "body": "The King of Pentacles is rooted in the body — sensory, solid, present. Let the physical pleasure of being alive in the world be part of this week.",
    "spirit": "The spirit understands that abundance, rightly held, is a form of generosity. What you have built can now serve something beyond you.",
    "action": "Make the decision that secures the long-term foundation. The King is not extravagant — he is strategic with what he has.",
    "the gift": "This cycle brings the energy of mastery over the material — not as accumulation for its own sake, but as the capacity to create lasting security.",
    "what to release": "The anxiety about abundance — the suspicion that having enough makes you complicit in something, or vulnerable to losing it.",
    "the seed": "Plant the intention to manage what you have with the King's steady hand: patiently, responsibly, generously.",
    "the obstacle": "Materialism that has crossed into identity — the sense that your worth is the measure of your wealth.",
    "first steps": "Review the material fundamentals: finances, home, health, practical commitments. Identify where the stewardship has lapsed.",
    "what has grown": "Mastery — over resources, over practical life, over the capacity to build and sustain.",
    "what is illuminated": "The full account of what you have accumulated and what it is for. The King asks: in service of what?",
    "what hides in the light": "The vulnerability underneath the solidity. The King of Pentacles has built so much precisely because loss was once real.",
    "what must be released": "The hoarding that has outlived its reason. You are no longer in the scarcity that taught you to hold tight.",
    "how to let go": "Invest. Give. Circulate what you have accumulated into something that multiplies it by moving it.",
    "what emerges": "A legacy — the kind that grows from what is given away as much as from what is kept.",
  },
};
