import type { SpreadPositionKey } from "./spreads";

export const CARD_POSITION_DESCRIPTIONS_A_REVERSED: Record<number, Partial<Record<SpreadPositionKey, string>>> = {
  0: { // The Fool (reversed)
    "mind": "Thoughts scatter without landing anywhere useful — the mind jumps at every shiny edge and commits to none. The restlessness is not freedom; it is avoidance wearing freedom's face.",
    "body": "The body trembles at the threshold, feet refusing to lift. What presents as caution is closer to paralysis — the animal that has forgotten it can move.",
    "spirit": "The soul knows the leap is required and keeps finding reasons to delay it. Naivety has curdled into recklessness or frozen into dread — neither serves what is being asked.",
    "action": "Stop manufacturing reasons to wait. The deliberation has become a substitute for the thing itself — one imperfect step forward is worth more than a thousand perfect plans.",
    "the gift": "The reversed Fool's shadow gift is the revelation of what you are actually afraid of — beneath the bravado or the paralysis, a specific fear is running the show. Name it.",
    "what to release": "Release the performance of fearlessness. You are not obligated to leap without terror; you are only obligated to leap. The pretense of ease is its own obstacle.",
    "the seed": "Plant the intention of grounded beginning — not the reckless plunge nor the endless hesitation, but the first step taken with eyes open to the risk and chosen anyway.",
    "the obstacle": "The obstacle is your own untested assumptions about what waits at the bottom. You have been afraid of an outcome you invented.",
    "first steps": "Write down the single worst thing that could happen. Look at it. Then ask yourself if you can survive it. You probably can. Now consider that you were afraid of that.",
    "what has grown": "What has grown from reversed Fool energy is a tangle — beginnings abandoned, starts without follow-through, the stubble of unchosen paths. The growth is real but directionless.",
    "what is illuminated": "The full moon reveals how many leaps you talked yourself out of, how many beginnings you dressed as wisdom when they were really fear. The unlived stories are visible now.",
    "what hides in the light": "Even under the full moon, the reversed Fool hides this: the belief that you are protecting yourself when you are only protecting the version of yourself that never has to be tested.",
    "what must be released": "Release the unbegun thing — not by beginning it, but by finally deciding. Either leap or lay it down. The hovering at the edge is the wound.",
    "how to let go": "Let go the way you would remove a splinter — not gently, not ceremonially, but directly. The reversed Fool releases by finally making the choice it has been circling.",
    "what emerges": "What emerges when the paralysis breaks is not certainty — it is motion. The first movement after long stillness, clumsy and alive.",
  },
  1: { // The Magician (reversed)
    "mind": "The mind performs competence rather than embodying it this week — running the same impressive loops while avoiding the question of whether anything real is being made.",
    "body": "Physical energy is scattered, ungrounded, burning off in all directions without landing. The conduit is open but the current has no destination.",
    "spirit": "The spirit is deceiving itself about its own readiness. Potential is being worshipped in place of actual work — the altar is set but the ritual goes uncelebrated.",
    "action": "Stop preparing to begin and begin. The Magician reversed has all the tools laid out and has been polishing them for weeks. Pick one up and use it imperfectly.",
    "the gift": "The shadow gift here is the exposure of self-deception — the gap between what you claim to be capable of and what you have actually done becomes visible this cycle. That gap is information.",
    "what to release": "Release the identity of someone who could do this if circumstances were different. Circumstances will not improve while you wait; the work makes its own conditions.",
    "the seed": "Plant the intention of honest application — to direct one specific, real, finite effort toward one specific, real, finite goal. No more and no less than that.",
    "the obstacle": "The obstacle is the manipulation running beneath the surface — ways you have been bending perception (your own or others') to avoid the accountability of actual production.",
    "first steps": "Audit the tools laid out on your altar. Which ones have you never actually used? Choose the most neglected and use it today, badly, without ceremony.",
    "what has grown": "What has grown from scattered will is scattered results — the evidence of potential that never cohered into completion. The full moon makes this visible without mercy.",
    "what is illuminated": "The light reveals the magician who has been performing: the show of capability that has been covering for the absence of follow-through. The audience sees it now.",
    "what hides in the light": "The deeper shadow here is the manipulation that happens so naturally you have stopped noticing it — the small bends of truth, the managed impressions. These need examination.",
    "what must be released": "Release the project you have been representing as active when it has been dormant for longer than you will admit. Clear the altar. Set down the unfinished working.",
    "how to let go": "Let go with the precision the Magician, even reversed, still possesses — name exactly what you are releasing, to whom, and why. No vagueness.",
    "what emerges": "What emerges when the performance drops is actual capability — smaller than the performance promised, but real, and that reality is worth more than the illusion.",
  },
  2: { // The High Priestess (reversed)
    "mind": "The mind is louder than the knowing beneath it. External voices, demands for logic, the pressure to explain — all of it is drowning out the signal that was trying to reach you.",
    "body": "The body has been speaking and going unheard — the low hum of instinct pressed down by the need to be reasonable. Something physical is asking for your attention right now.",
    "spirit": "The inner wisdom has been suppressed, not because it is absent but because you are afraid of what it will say. The silence is not peaceful; it is enforced.",
    "action": "Stop seeking external validation for a decision you have already made internally. The High Priestess reversed does not need more time to know — she needs to stop talking herself out of what she knows.",
    "the gift": "The shadow gift is the revelation of what you have been keeping secret, even from yourself. The suppressed knowing has been shaping decisions in the dark. Bring it up.",
    "what to release": "Release the need to justify your intuitions to people who will not understand them. Some knowing is not for translation.",
    "the seed": "Plant the intention of reclaimed interiority — to stop outsourcing your knowing to those who ask for evidence, and to begin trusting the current that runs beneath the argument.",
    "the obstacle": "The obstacle is premature disclosure: you have been speaking your inner truth before it was ready to be heard, burning it in the explaining, and now you trust it less.",
    "first steps": "Keep the next important knowing entirely to yourself. Do not tell anyone. Let it consolidate in silence for one full week and see what it becomes.",
    "what has grown": "What has grown in this cycle has been half-strangled by noise and external pressure. The roots are there but tangled — the inner knowing needs tending before it can surface clearly.",
    "what is illuminated": "The full moon illuminates what you already knew and refused to act on — the truth that has been sitting quietly in the depths while you demanded more evidence from above.",
    "what hides in the light": "The reversed High Priestess hides this even now: a secret you are keeping from yourself, not out of ignorance but out of the fear of what knowing would require you to do.",
    "what must be released": "Release the relationship or situation you have been tolerating despite every interior signal telling you it is wrong. The Priestess reversed has no more patience for willful deafness.",
    "how to let go": "Let go not through analysis but through the body — find the quiet in the chest that arrives when the right decision is already made, and let that guide the release.",
    "what emerges": "What emerges when the external noise drops is the steady underground current that was always there. Quieter than you expected. More reliable than anything else you have.",
  },
  3: { // The Empress (reversed)
    "mind": "The mind is caught in scarcity this week — either grasping for more or denying itself entirely, unable to simply receive what is already present and sufficient.",
    "body": "The body has been neglected or smothered — either starved of the pleasure and care it requires, or over-managed, over-supplemented, controlled. Neither is nourishment.",
    "spirit": "The spirit's natural creativity is blocked, dammed at the source. What wants to grow cannot find ground because something is either withholding what it needs or drowning it.",
    "action": "Attend to what has been genuinely neglected — not in the mode of guilt but in the mode of honest repair. The Empress reversed asks for one act of real self-tending this week.",
    "the gift": "The shadow gift is the exposure of where you have been blocking abundance — the specific way you withhold from yourself or over-give until the well runs dry. Both patterns are visible now.",
    "what to release": "Release the belief that you must earn comfort, beauty, or rest. The Empress reversed has been running a scarcity ledger that does not belong to her.",
    "the seed": "Plant the intention of unconditional self-nourishment — to give yourself what you require this cycle before deciding whether you have earned it.",
    "the obstacle": "The obstacle is the smothering that disguises itself as love — the control of another's growth through over-tending, or the self-control that starves your own creative ground.",
    "first steps": "Identify the single most neglected need — physical, creative, relational — and address it without apology or negotiation. Just one. That is enough to start the flow.",
    "what has grown": "What has grown in the reversed Empress's field is stunted or overgrown — either the careful little that lack produces, or the tangled excess that neglect eventually generates.",
    "what is illuminated": "The full moon illuminates the wound at the root of abundance — the place where you first learned to withhold from yourself, and the cost it has been accruing ever since.",
    "what hides in the light": "The mother wound hides deeper still: not just the withholding but the fear beneath it — that if you allow yourself to receive, something terrible will be owed.",
    "what must be released": "Release the creative project, the caretaking role, or the relationship you have been feeding at the cost of your own ground. The soil needs fallow time.",
    "how to let go": "Let go through abundance, not sacrifice — allow yourself something generous and unearned as the act of release. Receive as practice for releasing.",
    "what emerges": "What emerges when the block is cleared is not immediately a flood but a trickle — the first honest movement of creativity that asks only to be noticed and followed.",
  },
  4: { // The Emperor (reversed)
    "mind": "The mind this week is either running tyrannical loops of control or has collapsed into formlessness — both are the Emperor's shadow, equally dysfunctional, equally demanding attention.",
    "body": "The body is caught in a system that does not serve it — too rigid, too punishing, or without structure at all. Both extremes produce the same exhaustion.",
    "spirit": "The spirit has been caged by its own rules. What began as governance has become imprisonment — the structures were supposed to serve the life, not replace it.",
    "action": "Identify one rule you are currently enforcing on yourself or others and break it this week — not by accident, but deliberately. The Emperor reversed releases structure by naming it and laying it down.",
    "the gift": "The shadow gift of the reversed Emperor is the visibility of rigidity — the places where structure became calcification, where authority became authoritarianism. Useful data.",
    "what to release": "Release the inherited authority — the rules you have been following because they were handed down, not because you examined and chose them.",
    "the seed": "Plant the intention of chosen structure — to build this cycle only the frameworks that genuinely serve your actual life, not the life someone else designed for you.",
    "the obstacle": "The obstacle is the tyrant within — the part of you that enforces order through punishment rather than invitation, that rules through fear because fear is the only governance it knows.",
    "first steps": "Identify the single rule or structure in your life that functions as a cage rather than a foundation. Name the person or belief it came from. Begin the process of questioning it.",
    "what has grown": "What has grown under the reversed Emperor is either a fortress with no occupants or a life without walls — in both cases, the structure is not protecting anything real.",
    "what is illuminated": "The full moon exposes the loneliness inside the fortress: the cost of having organized your life around control rather than connection, authority rather than warmth.",
    "what hides in the light": "The reversed Emperor hides vulnerability behind procedural obstruction — there is a wound underneath the inflexibility that the rigidity was built to protect. It is still there.",
    "what must be released": "Release the authority you have been wielding over something that does not need to be governed — most likely yourself, and most likely in the domain that matters most.",
    "how to let go": "Let go by dismantling one rule — formally, deliberately, with full awareness of what it cost to keep it. The Emperor releases through conscious abdication.",
    "what emerges": "What emerges when the cage opens is not chaos but a tentative softness — the thing that was being protected by the rigidity, finally having room to breathe.",
  },
  5: { // The Hierophant (reversed)
    "mind": "The mind this week is entangled in received doctrine — thinking inside a framework it has never examined, following channels cut by others without asking whether they lead anywhere true.",
    "body": "The body has been following someone else's ritual without conviction. The practiced motions produce none of the meaning they were supposed to — the form is there, the substance has gone.",
    "spirit": "The spirit is suffocating under dogma — either the oppressive weight of an institution that no longer serves, or the empty rebellion that destroyed without discerning what was worth keeping.",
    "action": "Examine what you believe versus what you were told to believe. This week the action is discernment — pull the received wisdom apart and keep only what survives honest scrutiny.",
    "the gift": "The shadow gift is the rupture from inherited meaning — the painful but necessary moment when the institution fails you and you are forced to find what you actually believe.",
    "what to release": "Release the allegiance you have been maintaining out of fear of excommunication. The tradition cannot give you what you need from it if it was never designed for people like you.",
    "the seed": "Plant the intention of self-authored faith — to spend this cycle building a framework of meaning from the ground up, keeping the pieces that survived and composting the rest.",
    "the obstacle": "The obstacle is the corrupt authority — the teacher, institution, or belief system that has been demanding conformity in exchange for belonging, and delivering shame instead of wisdom.",
    "first steps": "Name one inherited belief and write down who gave it to you and what it has cost you to keep it. The naming and the attribution are the first crack in the doctrine.",
    "what has grown": "What has grown is a religious or institutional entanglement that has been subtly warping how you see yourself — the doctrine has been growing into the shape of your identity.",
    "what is illuminated": "The full moon illuminates the ways the tradition has been serving the institution rather than the seeker — the gap between what was promised and what was delivered.",
    "what hides in the light": "The reversed Hierophant hides the seeker's complicity — the part of you that chose the dogma because thinking for yourself was harder, and the cost of that choice.",
    "what must be released": "Release the formal affiliation that has become a performance. You have outgrown the container; continuing to dress in its robes helps neither you nor the tradition.",
    "how to let go": "Let go through honest departure — name what you received, name what was false, and walk out the door without either burning it behind you or looking back.",
    "what emerges": "What emerges from the wreckage of received doctrine is a raw, tentative, genuinely personal relationship with the sacred — smaller than before, but yours.",
  },
  6: { // The Lovers (reversed)
    "mind": "The mind is rationalizing a misalignment it has already noticed — running loops to justify a choice that the deeper self has already named as a betrayal of values.",
    "body": "The body knows the answer. It has been producing the answer in tension, nausea, or exhaustion for longer than you have been listening. The misalignment is physical.",
    "spirit": "The soul recognizes the disharmony and is grieving it — not loudly, but in the register of persistent low-grade wrongness that no amount of arrangement can resolve.",
    "action": "Stop negotiating with the misalignment. The Lovers reversed asks for honesty about what is actually true in this connection or choice, even if that truth is uncomfortable.",
    "the gift": "The shadow gift is the clarity of misalignment made visible — the reversed Lovers reveals exactly where your choices and your values have diverged, and the cost of that divergence.",
    "what to release": "Release the relationship, the path, or the version of yourself that requires you to look away from what you genuinely value in order to function.",
    "the seed": "Plant the intention of values alignment — to spend this cycle bringing one major life domain into honest alignment with what you actually believe matters, not what you have settled for.",
    "the obstacle": "The obstacle is the temptation that has already won — the thing you chose over your values, and the ongoing work of justifying that choice rather than revisiting it.",
    "first steps": "Name, without softening, what value is being compromised in the current situation. Not what you wish were true but what is actually true. Start from that.",
    "what has grown": "What has grown in the soil of misalignment is a rift — between who you present as and who you are, between what you said you valued and what you chose. The full moon makes it wide.",
    "what is illuminated": "The full moon shows the disharmony in its full dimensions — the ways the union (with a person, a path, a version of yourself) has been costing more than it has been giving.",
    "what hides in the light": "The reversed Lovers hides the deepest betrayal: not what was done to you, but where you participated in the undoing of something you knew was aligned with your true self.",
    "what must be released": "Release the false union — the agreement, relationship, or self-conception that was built on attraction rather than genuine shared values. The bond was real; it is also done.",
    "how to let go": "Let go with the honesty the Lovers demand even in their shadow — speak the misalignment clearly, to yourself first, then if needed to the other. No soft edges.",
    "what emerges": "What emerges from genuine misalignment named and addressed is not immediate harmony but the possibility of it — the space in which something true could eventually grow.",
  },
  7: { // The Chariot (reversed)
    "mind": "The mind is fragmenting under the pull of contradictory imperatives, each demanding full attention, none receiving enough. The chariot is not moving — it is spinning in place.",
    "body": "Physical energy is either burning out through aggression misdirected at the wrong targets, or collapsing from the effort of holding forces that are actively pulling apart.",
    "spirit": "The spirit has confused movement with progress. Speed and force are not the same as direction — the Chariot reversed is going somewhere emphatically but no longer knows where.",
    "action": "Stop pushing. The Chariot reversed asks for a controlled deceleration — not surrender, but the deliberate choice to halt before the crash that is currently approaching.",
    "the gift": "The shadow gift is the exposure of what you have been calling drive when it was really avoidance — the forward motion that kept you from having to sit with what was behind you.",
    "what to release": "Release the aggression that has been operating without examination — the force applied to situations that required presence rather than velocity.",
    "the seed": "Plant the intention of direction before momentum — to commit this cycle to knowing where you are going before you pour energy into getting there.",
    "the obstacle": "The obstacle is the crash — the place ahead where the opposing forces, no longer held in any common direction, finally tear the mechanism apart. It is still preventable.",
    "first steps": "Name the two or more forces pulling your energy in conflicting directions. Write them down. Circle the one direction that has the most of your actual will behind it — not the loudest, the deepest.",
    "what has grown": "What has grown from unchanneled drive is damage — territory claimed and then lost, relationships flattened by forward motion that could not brake, results that outlasted their usefulness.",
    "what is illuminated": "The full moon illuminates the wreckage of the campaign's end — not defeat, but the exhaustion after winning without knowing what the victory was for.",
    "what hides in the light": "The Chariot reversed hides the grief underneath the aggression — the sadness that the drive has been outrunning, that stops being avoidable when the wheels do.",
    "what must be released": "Release the war footing — the constant mobilization, the identity organized around struggle and advancement. The campaign is over. The body needs to stop being a weapon.",
    "how to let go": "Let go slowly, deliberately — the Chariot reversed releases not with a burst but with a controlled deceleration, one degree of pressure at a time.",
    "what emerges": "What emerges when the crash is chosen rather than arrived at is the ability to ask: now what? The question the Chariot reversed never had time to hear.",
  },
  8: { // Strength (reversed)
    "mind": "The mind is undermining itself — the quiet voice of self-doubt has been allowed to run for so long that it now speaks with the authority of fact.",
    "body": "Physical instinct has been suppressed past the point of health, or overridden with force where gentleness was required. The body is either mute or unmanageable.",
    "spirit": "The soul is afraid of its own darkness. The beast has been starved rather than tended, and a starved beast eventually escapes through the only door available.",
    "action": "Locate the instinct you have been suppressing — not to release it blindly but to hear what it is trying to communicate before it finds another way to speak.",
    "the gift": "The shadow gift is the revelation of cowardice — the specific place where you chose force when gentleness was needed, or fled when presence was required. Both are recoverable.",
    "what to release": "Release the strategy of suppression. You cannot keep the beast in the basement forever; the longer it stays locked away, the more dangerous the unlocking becomes.",
    "the seed": "Plant the intention of compassionate witness — to approach the feared inner thing with the same open-handed steadiness the figure in the card approaches the lion.",
    "the obstacle": "The obstacle is the self-doubt that has grown in the absence of real engagement — the more you have avoided the difficult thing, the larger and more certain its danger has come to seem.",
    "first steps": "Name the instinct, fear, or inner darkness you have been managing through avoidance. Give it a name that is honest. Approach it one step closer than you did yesterday.",
    "what has grown": "What has grown from the reversed Strength is a working truce that has broken down — the animal is loose, or the suppression has become a cage you are living in too.",
    "what is illuminated": "The full moon reveals the specific form your cowardice has taken — the lion you fled from, and the cost of the flight to everyone including you.",
    "what hides in the light": "The reversed Strength hides this: the legitimate anger that was suppressed along with the fear, the real force that is not dangerous but has been treated as though it is.",
    "what must be released": "Release the grip — whether the grip of suppression or the grip of force. Open the hand. The struggle has been exhausting the wrong thing.",
    "how to let go": "Let go through presence: sit with the difficult thing, unheld, without trying to manage its direction. The release is the willingness to simply be with it.",
    "what emerges": "What emerges when the suppression ends is not chaos but integration — the reclaimed instinct, no longer driven by hunger, finally available as a source of real strength.",
  },
  9: { // The Hermit (reversed)
    "mind": "The mind has turned its lantern inward until there is no light left for navigation — the solitude has become a hall of mirrors, thought feeding only on thought.",
    "body": "The body has been denied contact, warmth, and the presence of others for longer than is nourishing. Isolation has crossed the line from practice into deprivation.",
    "spirit": "The spirit sought the cave for wisdom and found instead a comfortable shelter from the risk of belonging. The lantern is still lit but it illuminates only the same walls.",
    "action": "Return. The Hermit reversed has stayed on the mountain past the point of wisdom; the action this week is the descent, the return to the world with whatever was found.",
    "the gift": "The shadow gift is the revelation of why the cave was chosen — the wound that made solitude feel safer than connection, which is different from making it wiser.",
    "what to release": "Release the justification of withdrawal as spiritual practice when it has become avoidance of the human contact that was always part of the healing.",
    "the seed": "Plant the intention of selective return — not the dissolution of solitude, but the deliberate re-entry into connection with the specific people or communities the withdrawal was keeping you from.",
    "the obstacle": "The obstacle is the addiction to the cave — the way absence from difficulty has come to feel like wisdom, when it is actually the refusal to test what was found in solitude.",
    "first steps": "Reach out to one person you have been avoiding through the mechanism of your solitude. Not to explain the absence. Just to be present.",
    "what has grown": "What has grown in the reversed Hermit's cave is a refined isolation — more justified, more comfortable, more defended. The roots have gone deeper into the wrong soil.",
    "what is illuminated": "The full moon illuminates the loneliness beneath the chosen solitude — the specific hunger that the withdrawal was also trying to solve, and failing to.",
    "what hides in the light": "The reversed Hermit hides the fear of being truly known — the terror that if you descend the mountain, what you found there will not survive contact with another person's reality.",
    "what must be released": "Release the hermitage as permanent dwelling. The lantern was lit to guide others home; carrying it down the mountain is what it was always for.",
    "how to let go": "Let go by stepping outside — literally, physically, into the presence of other people. The reversed Hermit releases through re-entry, not more reflection.",
    "what emerges": "What emerges from the descent is the teacher who was always latent — the wisdom forged in solitude now made real by contact with the world that needs it.",
  },
  10: { // Wheel of Fortune (reversed)
    "mind": "The mind is clutching a spoke on a wheel that is turning — the grip is exhausting everything, and the wheel turns anyway. Resistance is not steering.",
    "body": "The body is absorbing the cost of fighting a cycle it cannot stop — the tension of someone who has been braced against movement for too long.",
    "spirit": "The spirit has confused endurance with wisdom, and resistance with agency. The wheel does not ask permission; it only asks that you not break yourself trying to hold it still.",
    "action": "Identify the one thing in your life where you are expending enormous energy resisting an inevitable change. Stop. Use that energy for the direction the wheel is already going.",
    "the gift": "The shadow gift of the reversed Wheel is the revelation of false control — the places where the illusion of agency has been costing real energy with no real effect.",
    "what to release": "Release the belief that this situation, this relationship, this configuration of circumstances can be held in place by force of will. It cannot. It is already turning.",
    "the seed": "Plant the intention of graceful surrender — not passivity, but the active choice to move with the momentum of the cycle rather than perpendicular to it.",
    "the obstacle": "The obstacle is the specific clinging — the thing or moment or relationship you are refusing to allow to pass. Name the spoke. Name why you are holding it.",
    "first steps": "Identify what is already changing despite your resistance to it. Stop spending energy on the resistance this week. Just stop. See what the wheel does when you let go.",
    "what has grown": "What has grown in the shadow of the reversed Wheel is stagnation masquerading as stability — the clinging to a configuration that has been over for longer than you have admitted.",
    "what is illuminated": "The full moon illuminates where you are in the cycle — and the evidence that you have been fighting a turn that was always going to happen, and that has mostly already happened.",
    "what hides in the light": "The reversed Wheel hides the part you played in the stagnation — the choices that maintained the stuck position, the refusals that the wheel kept trying to move you past.",
    "what must be released": "Release this entire configuration of circumstances. Not one element — the whole turn. The spoke you have been holding is not a lifeline; it is what is keeping you at the bottom.",
    "how to let go": "Let go by ceasing the active resistance — not a dramatic release but simply the removal of opposition. Let the wheel move. Feel the dizziness of resuming the turn.",
    "what emerges": "What emerges when the resistance ends is momentum — the disorienting, necessary forward motion of a cycle that has finally been allowed to complete.",
  },
  11: { // Justice (reversed)
    "mind": "The mind is working with a corrupted set of scales this week — its assessments feel logical but are being tilted by an agenda it has not admitted to itself.",
    "body": "The body holds the imbalance as tension, asymmetry, exhaustion in the places that have been carrying more than their share. It knows what the mind is still rationalizing.",
    "spirit": "The soul is caught in self-justification — the ongoing inner work of making the story come out right, which is not the same as making the story true.",
    "action": "Write down your account of the conflict — then write the other party's account as if you were their advocate. Read both. The gap between them is where the reversed Justice lives.",
    "the gift": "The shadow gift is the exposure of bias — the hidden weight on the scales, the way your story about the situation has been serving a conclusion rather than the truth.",
    "what to release": "Release the version of the story in which your hands are entirely clean. The part you played does not destroy you; the refusal to see it keeps the scales from balancing.",
    "the seed": "Plant the intention of honest accountability — to approach this cycle's central conflict willing to name your contribution, however uncomfortable that naming is.",
    "the obstacle": "The obstacle is the judgment corrupted by agenda — the way the language of fairness and principle is being used to dress a conclusion that was reached before the evidence was gathered.",
    "first steps": "Find the one element of the situation you have consistently omitted from your account of it. Sit with it without immediately finding a counter-argument.",
    "what has grown": "What has grown from the reversed Justice is a record that looks balanced but is not — the accounting has been managed, and the full moon now requires the real ledger.",
    "what is illuminated": "The full moon illuminates the bias in your judgment — not to condemn you, but to show you that you cannot receive fairness from a system you are tilting.",
    "what hides in the light": "The reversed Justice hides the punisher's pleasure — the part of you that uses the language of accountability to wound, and calls the wounding righteous.",
    "what must be released": "Release the grievance you are maintaining as moral position. It may have been legitimate; it has become a story you tell to justify continued engagement with the wound.",
    "how to let go": "Let go through the specific act of acknowledgment — name what happened, including your part, and close the ledger with deliberate fairness applied equally in all directions.",
    "what emerges": "What emerges from honest reckoning is equilibrium — the unsatisfying, quiet, real peace of a balance finally achieved without a thumb on the scale.",
  },
  12: { // The Hanged Man (reversed)
    "mind": "The mind has been calling stalling 'waiting' for long enough that it can no longer tell the difference. The sacred pause has been extended until it is no longer sacred — just stuck.",
    "body": "The body is hanging by choice in a position that has become genuinely uncomfortable, and the discomfort is no longer teaching anything. The suspension has served its purpose.",
    "spirit": "The soul is practicing martyrdom instead of wisdom — the performance of patient suffering that does not actually lead anywhere, that is sustained because it feels spiritual to endure.",
    "action": "End the voluntary suspension. Whatever you have been waiting for has either arrived or will not. Either way, the hanging is over. Cut yourself down.",
    "the gift": "The shadow gift is the revelation of what you have been using the pause to avoid — the decision, the confrontation, the change that the indefinite waiting was keeping at bay.",
    "what to release": "Release the story that this is a productive waiting period. The Hanged Man reversed knows somewhere that it is no longer suspended in wisdom but in avoidance.",
    "the seed": "Plant the intention of action after understanding — to take the single step that the waiting has been building toward, even if the vision is not yet complete.",
    "the obstacle": "The obstacle is the comfortable suffering — the way the suspended state has become its own reward, offering the identity of someone who bears difficulty without the requirement of actually changing anything.",
    "first steps": "Name the action you have been delaying by calling it waiting. Give it a date. The Hanged Man reversed does not need more time — it needs a deadline.",
    "what has grown": "What has grown from extended suspension is a kind of spiritual callous — the capacity to tolerate a stuck state for so long that motion begins to feel like the risk.",
    "what is illuminated": "The full moon illuminates the length of the pause — how long you have been here, what the waiting has cost, and what was never going to arrive regardless of how long you held on.",
    "what hides in the light": "The reversed Hanged Man hides the addiction to the suspended state — the way the absence of a decision keeps all options theoretically open, and the terror of choosing that the waiting is protecting.",
    "what must be released": "Release the suspension itself. The wisdom has been extracted from the waiting; what remains is only the cost of continuing to hold the position.",
    "how to let go": "Let go by cutting the rope — directly, actively, without waiting for the perfect moment to do it. The Hanged Man reversed releases through action, not through more surrender.",
    "what emerges": "What emerges from the end of the pause is forward motion — awkward at first, disorienting after so long in stillness, but unmistakably alive.",
  },
  13: { // Death (reversed)
    "mind": "The mind is refusing to let something die. It keeps finding new reasons to maintain what it knows is over — new angles, new possibilities, new framings of what is already a corpse.",
    "body": "The body is exhausted by the effort of keeping something alive that has ended. The fatigue is not illness — it is the cost of resuscitation performed past the point of possibility.",
    "spirit": "The soul recognizes the ending and is afraid of it — not because the ending is not real, but because it cannot yet see what comes after, and the unknown is worse than the known loss.",
    "action": "Stop the resuscitation. One honest accounting of what is actually over, followed by one concrete step toward genuine ending, is what the reversed Death requires this week.",
    "the gift": "The shadow gift is the exposure of the pattern that refuses to end — the specific shape of what you cannot let die, and therefore what you cannot allow to transform.",
    "what to release": "Release the thing that is already over but that you are maintaining through willpower, money, narrative, or identity. The Death reversed is not asking you to be fine; it is asking you to stop.",
    "the seed": "Plant the intention of honest completion — to allow this cycle's required ending to actually end, however uncomfortable the completion feels, because transformation waits on the other side.",
    "the obstacle": "The obstacle is the undead pattern — the habit, relationship, identity, or belief that refuses to end because you will not stop feeding it. It is not alive; it is animated by your refusal.",
    "first steps": "Name what is already dead in the clearest language you can manage. Not 'struggling' or 'difficult' or 'in transition.' Say: this is over. See what that costs and whether you can bear it.",
    "what has grown": "What has grown from the refusal to let go is a haunting — the dead thing still occupying the space where something alive could grow, if you would allow the ground to be cleared.",
    "what is illuminated": "The full moon illuminates the ending you have been refusing to look at directly — the full scope of what is over, which is always smaller and more survivable than the fear of it.",
    "what hides in the light": "The reversed Death hides the terror underneath the clinging — not grief, which is honest, but the specific fear that you will not survive the transformation, that you will be nothing without this.",
    "what must be released": "This is the full moon and the reversed Death: the undead thing must now be laid down completely. Not diminished, not reframed. Set down entirely.",
    "how to let go": "Let go by performing the ending — literally, if possible. A ceremony, a letter, a final act of completion. The reversed Death requires ritual to break the stagnation.",
    "what emerges": "What emerges from the genuine ending the reversed Death finally allows is not immediately visible. The ground must lie fallow first. Trust that the ground knows what to do.",
  },
  14: { // Temperance (reversed)
    "mind": "The mind is operating in extremes — swinging between total immersion and total avoidance, unable to find the measured engagement that would actually move the work forward.",
    "body": "The body is suffering from excess or from the crash that follows it — the aftermath of imbalance, the physical cost of the all-or-nothing approach.",
    "spirit": "The soul is in the aftermath of its own impatience — scattered, incomplete, still holding the broken pieces of a transformation it tried to rush. The spirit's work this week is to accept that the alchemy requires beginning again.",
    "action": "Return to the practice of incremental engagement — the small, consistent doses that the Temperance card knows are more powerful than the occasional flood. Less, more often.",
    "the gift": "The shadow gift is the evidence of what excess costs — the reversal shows exactly where the imbalance has been producing diminishing returns, which is information the upright card could not deliver.",
    "what to release": "Release the extremism — the insistence that the real thing is only the intense thing, that a moderate engagement is the same as no engagement. The alchemist knows better.",
    "the seed": "Plant the intention of patient integration — to enter this cycle willing to stay with the middle path even when it feels inadequate to the size of what you are trying to create.",
    "the obstacle": "The obstacle is impatience that has been dressed as passion — the belief that the dramatic gesture, the complete commitment, the all-consuming effort is the only valid form of caring.",
    "first steps": "Identify the thing you have been doing in bursts and then abandoning. Commit to a reduced, sustainable version of it for this cycle. Less than feels meaningful. Do it consistently.",
    "what has grown": "What has grown from imbalance is a record of broken rhythms — the projects begun in fever and abandoned in crash, the relationships exhausted by intensity.",
    "what is illuminated": "The full moon illuminates the results of the alchemical failure — the compound that was forming, broken open too soon, its elements now scattered and requiring patient recollection.",
    "what hides in the light": "The reversed Temperance hides the avoidance inside the excess — the way going to extremes keeps you from having to be in the middle place, where the real work is done.",
    "what must be released": "Release the formula you have been forcing. The work was almost done; your impatience ruined the last step. Set it down. Begin the long patience again.",
    "how to let go": "Let go through deliberate deceleration — the Temperance release is not a letting-go of control but a return to moderate, steady, sustainable rhythm after the storm.",
    "what emerges": "What emerges from the broken excess is the possibility of beginning the alchemy again, this time with knowledge of what breaks it. The reversal was also instruction.",
  },
  15: { // The Devil (reversed)
    "mind": "The chains are becoming visible. What the mind once accepted as permanent is beginning to look like a choice — this recognition is uncomfortable, necessary, and the beginning of everything.",
    "body": "The body is registering the cost of what it has been bound to — the specific physical toll of the addiction, compulsion, or avoidance that the mind has been tolerating.",
    "spirit": "The soul is waking to its captivity. Whether the Devil reversed brings awareness before the chains tighten further or after a moment of genuine recognition depends entirely on what you do with the discomfort.",
    "action": "Do not act on the compulsion this week — not as suppression, but as experiment. Notice what the craving is actually pointing toward. The absence of the behavior contains the information.",
    "the gift": "The shadow gift is the key becoming visible — the reversed Devil shows you that you have been holding the key to your own chains, which is the most terrifying and liberating discovery possible.",
    "what to release": "Release the narrative that the chain is part of who you are. The Devil reversed is the moment of recognition: this is a behavior, not an identity. The distinction matters enormously.",
    "the seed": "Plant the intention of conscious disengagement — not willpower, which the Devil has already defeated, but the deliberate building of space between the impulse and the action.",
    "the obstacle": "The obstacle is the pleasure of the loosening — the Devil reversed can mean awareness of chains, but it can also mean the chains drawn tighter before the awareness breaks through. Watch which it is.",
    "first steps": "Tell someone the truth about the chain. Not to be helped, necessarily — just to say it aloud to a witness. The secrecy is part of the mechanism. Break the secrecy first.",
    "what has grown": "What has grown in the shadow is being examined, perhaps for the first time. The reversed Devil under the full moon is the forced accounting — what the compulsion has actually cost.",
    "what is illuminated": "The full moon illuminates the exact mechanism: not just the chain but how you maintain it, what you get from it, and what the original wound is that it was built to address.",
    "what hides in the light": "The reversed Devil hides the seduction that is still operating even as the awareness grows — the part of you that is grateful for the recognition and still does not want to leave.",
    "what must be released": "This is the moment of release the reversed Devil makes possible. Not willpower. Not discipline. The full-moon visibility that makes the chain impossible to ignore — and the choice to step out.",
    "how to let go": "Let go by looking at the chains and finding the key you have been holding. The unlocking is usually simpler than expected. The complexity was always in the looking.",
    "what emerges": "What emerges from the Devil's loosened grip is not immediately freedom but the felt experience of choice — which turns out to be a thing the captive self had forgotten entirely.",
  },
  16: { // The Tower (reversed)
    "mind": "The mind knows the structure is compromised and is working overtime to maintain the pretense of its solidity. The energy of denial is enormous and increasingly unsustainable.",
    "body": "The body is absorbing the shock that the mind is refusing to acknowledge — the low hum of dread, the interrupted sleep, the systems running hot on the fuel of maintained fiction.",
    "spirit": "The collapse is happening internally rather than externally. No one else can see the Tower falling, which makes the isolation of the implosion worse.",
    "action": "Choose the controlled disruption over the eventual collapse. One deliberate act of dismantling what you know is not working is worth ten years of maintained false structure.",
    "the gift": "The shadow gift of the reversed Tower is the window of choice before the fall — you can see the crack, you can act before the lightning strikes. Most people do not get this warning.",
    "what to release": "Release the lie you are telling yourself to keep the structure standing. The reversed Tower asks you to name it, not to someone else — to yourself, in the dark, right now.",
    "the seed": "Plant the intention of preemptive honesty — to dismantle the false structure with your own hands before it falls on you, which is the only form of Tower energy you can actually control.",
    "the obstacle": "The obstacle is the collapse avoided at cost — the catastrophizing about a change that is actually manageable, the maintenance of an unbearable situation because the change seems worse.",
    "first steps": "Identify the structural compromise — the premise your current life is organized around that you suspect, somewhere, is false. Take one step toward honesty about it this week.",
    "what has grown": "What has grown in the reversed Tower is a complex internal architecture of maintenance — the elaborate work required to keep the false structure standing is now the primary occupation.",
    "what is illuminated": "The full moon illuminates the internal collapse — the Tower that only you can see, the rubble you have been sweeping up every morning before anyone else wakes.",
    "what hides in the light": "The reversed Tower hides the relief that is on the other side of the collapse — the part of you that knows the structure needs to fall and is exhausted from preventing it.",
    "what must be released": "Release the lie that is load-bearing. It does not have to fall apart to be put down; you can set it down deliberately. But it must go.",
    "how to let go": "Let go by choosing the smaller disruption now over the larger one later — walk out of the building before the lightning comes. This is not cowardice; this is the wisdom the upright Tower could not afford.",
    "what emerges": "What emerges from the chosen dismantling is something the forced collapse never offers: the opportunity to decide what to build next before the dust settles.",
  },
  17: { // The Star (reversed)
    "mind": "The mind has protected itself from further disappointment by closing off the avenue of hope. The cynicism is rational; it is also costing more than it is saving.",
    "body": "The body is depleted in ways that have become normalized — chronically low energy, disrupted sleep, the diminished appetite of someone who has stopped expecting to be nourished. These are not background conditions; they are the reversed Star's physical report.",
    "spirit": "The spirit has drawn a curtain between itself and the star — the disillusionment was real, and the protective cynicism that followed was reasonable. But the curtain has been closed for a long time now.",
    "action": "Take one small act of hope — not declaration, not performance, but the quiet private choice to move toward one thing that represents the future you want. Do it without announcing it.",
    "the gift": "The shadow gift is the specific shape of the disillusionment — the reversed Star names exactly what kind of hope was destroyed, and therefore what kind of faith must be rebuilt more carefully.",
    "what to release": "Release the cynicism that has been protecting you from renewed disappointment. It succeeded. It also succeeded at keeping the star from reaching you.",
    "the seed": "Plant the intention of tested faith — not the naive openness of the first time, but the harder, more precious trust that has survived the Tower and chosen to reach upward anyway.",
    "the obstacle": "The obstacle is the disillusionment calcified into worldview — the way a specific wound has been generalized into a comprehensive refusal of hope, so that no particular hope has to be refused.",
    "first steps": "Find the one remaining small thing you actually believe in — not what you wish you believed, not what you are supposed to believe. The genuinely small, genuinely living ember. Hold it.",
    "what has grown": "What has grown in the reversed Star's cycle is a protective scar over the wound that closed the hope — durable, functional, and an obstacle to the very thing it was formed to protect.",
    "what is illuminated": "The full moon illuminates the closed curtain — and through a gap in it, the star that has been there the whole time, patient, not requiring your acknowledgment to continue shining.",
    "what hides in the light": "The reversed Star hides the waiting — the part of you that will not do the work of self-restoration because it is waiting for someone else to prove the faith is warranted first.",
    "what must be released": "Release the identity of the disillusioned one. The wound was real; it has also become a role. The star cannot reach someone who has made a home of the darkness after the Tower.",
    "how to let go": "Let go of the cynicism through one small act of genuine self-restoration — pour water into the dry ground of yourself without requiring that it show results before you believe in it.",
    "what emerges": "What emerges from the cautious reopening of the reversed Star is not naive joy but something more durable — hope that has survived disillusionment, which is the only kind that lasts.",
  },
  18: { // The Moon (reversed)
    "mind": "The confusion is either beginning to lift — the fog of the Moon thinning enough to reveal the actual shape of things — or it is deepening, the illusions crystallizing into something harder to dissolve.",
    "body": "The body carries the Moon's distortions physically — disrupted sleep, anxiety that manifests as chest tightness or nausea, the hypersensitivity of someone who has been navigating uncertainty for too long. These sensations are signal, not noise.",
    "spirit": "The reversed Moon is the moment when the dream either breaks toward dawn or calcifies into delusion. The spirit must choose — consciously, deliberately — to move toward the light on the shore.",
    "action": "Name one thing that you know is an illusion and choose to see it clearly this week, regardless of how much comfort the fog has been providing.",
    "the gift": "The shadow gift is the partial clarity that the reversal offers — the Moon reversed is not the full light of the Sun, but the first edge of genuine perception after the distortion.",
    "what to release": "Release the fear you have been using to navigate — the reversed Moon asks you to recognize that the monsters in the path are the size the Moon made them, not the size they actually are.",
    "the seed": "Plant the intention of clear-eyed emergence — to allow this cycle to complete the Moon's work of surfacing what was hidden, even when what surfaces is unflattering.",
    "the obstacle": "The obstacle is the calcifying illusion — the fear or distortion that the reversed Moon can allow to harden into fixed belief rather than dissolve into clarity, depending on which way it turns.",
    "first steps": "Choose one story you have been telling yourself about a situation or a person and check it against one piece of concrete evidence. Just one. Begin returning to the actual.",
    "what has grown": "What has grown in the Moon's cycle is either an emerging truth or a deepened confusion — the full moon will show which path was taken, and what the psychic material has become.",
    "what is illuminated": "The full moon with the reversed Moon is an unusual clarity — the confusion lifts or is forced to lift, and what was distorted becomes briefly, sharply visible in its actual proportions.",
    "what hides in the light": "The reversed Moon hides what will remain unresolved — the things that go back under even when most of the distortion clears, that will return on the next cycle.",
    "what must be released": "Release the dream you have been inhabiting. The useful portion of the Moon's cycle is complete; what remains is the illusion that has been providing comfort without providing truth.",
    "how to let go": "Let go by waking up — the specific, deliberate choice to return to waking consciousness, to the dry ground of the actual, to the shore that has been there the whole time.",
    "what emerges": "What emerges from the Moon reversed is a cautious, imperfect clarity — not the full Sun, but enough light to recognize the path and take the next step without being swallowed.",
  },
  19: { // The Sun (reversed)
    "mind": "The mind is performing joy rather than experiencing it — the brightness has become a mask, and underneath the cheerful presentation something darker has not been allowed to speak.",
    "body": "The body is being forced into a radiance it does not feel. The insistence on vitality and presence is exhausting what it was supposed to celebrate.",
    "spirit": "The spirit is dimmed not by darkness but by the ego's demand to appear bright. The genuine warmth is being blocked by the performance of it.",
    "action": "Let yourself be less radiant this week. The Sun reversed asks permission to be dim, uncertain, and unimpressive — and that permission, paradoxically, is the only way back to real warmth.",
    "the gift": "The shadow gift is the exposure of what performative joy has been covering — the reversed Sun names the depression, the dimming, the grief that has been shining through a forced smile.",
    "what to release": "Release the obligation to be the warmth in the room. The Sun reversed asks you to let someone else carry the light for a while and see what you feel like underneath the role.",
    "the seed": "Plant the intention of authentic vitality — not the performed version but the quiet, honest version that does not require an audience and is not responsible for anyone else's warmth.",
    "the obstacle": "The obstacle is the ego blocking the genuine light — the arrogance that needs the warmth to be noticed, the grandiosity that has replaced simple joy with the performance of it.",
    "first steps": "Do one thing purely and privately for the pleasure of it — no witnesses, no documentation, no audience. Let it be for you alone. This is where the real Sun lives.",
    "what has grown": "What has grown under the reversed Sun is a performance that has become increasingly expensive to maintain — the warmth output no longer matches the internal supply.",
    "what is illuminated": "The full moon with the reversed Sun illuminates everything, including the exhaustion beneath the radiance — the person behind the bright persona who has been waiting for permission to rest.",
    "what hides in the light": "The reversed Sun hides the deflation — the sense of meaninglessness that creeps in when the performance succeeds but the performer feels nothing. The applause does not reach the actual self.",
    "what must be released": "Release the triumph, the scoreboard, the identity of the one who radiates. The Sun reversed under the full moon asks for the release of the performance itself.",
    "how to let go": "Let go without celebration — the reversed Sun's release is quiet, private, the simple act of stopping the performance and sitting in the honest dark for a moment.",
    "what emerges": "What emerges from the dropped performance is the first genuine warmth in a long time — small, unperformed, not enough to fill a room, and completely, entirely real.",
  },
  20: { // Judgement (reversed)
    "mind": "The call has been heard and the mind is constructing reasons not to answer it — the rationalization is sophisticated, the logic is impeccable, and it is all in service of remaining asleep.",
    "body": "The body is bracing for the reckoning it knows is coming — the tension of someone who has heard the trumpet and pulled the covers over their head, hoping the sound will stop.",
    "spirit": "The soul is refusing its own awakening. The call has been sounding for long enough that the refusal is no longer innocent — it is a choice being made repeatedly.",
    "action": "Answer one call you have been refusing. Not the most terrifying one — begin with the one whose refusal you are most confident you can justify, and examine that confidence.",
    "the gift": "The shadow gift is the revelation of what you are protecting by refusing the reckoning — the reversed Judgement names the specific comfortable identity or story that the awakening would disrupt.",
    "what to release": "Release the old judgments you have been mistake-taking for truth — the assessments of yourself and others formed under pressure, in survival mode, that have calcified into permanent verdict.",
    "the seed": "Plant the intention of courageous accounting — to enter this cycle willing to conduct one honest self-evaluation, without either condemning yourself or excusing what genuinely warrants examination.",
    "the obstacle": "The obstacle is the refusal itself — not a temporary delay but an active, ongoing, daily decision not to answer the call that has been sounding. The refusal has become an identity.",
    "first steps": "Name the call you have been refusing. Not what you are supposed to be called to — what you actually sense is asking for your response, that you have been avoiding. Write it down.",
    "what has grown": "What has grown in the shadow of the refused Judgement is a kind of deadness — the flatness of a life organized around never being surprised by itself, never awakened to more.",
    "what is illuminated": "The full moon illuminates the call in its full clarity — the trumpet blast that has been sounding beneath the noise of your daily life, finally audible in the full-moon quiet.",
    "what hides in the light": "The reversed Judgement hides the self-appointed judge — the internal critic who uses the language of awakening to wound rather than liberate, and who is the real reason the call is refused.",
    "what must be released": "Release the identity built for the life you are leaving — the version of yourself assembled under old conditions, for old purposes. It saved you. It is now the thing the trumpet is calling you past.",
    "how to let go": "Let go with the full turning of the body toward the call — not slowly, not tentatively. The Judgement reversed releases through the complete act of finally answering.",
    "what emerges": "What emerges from the answered call is not the person who refused it — it is the one underneath, less defended, more awake, answering to something that was always larger than survival.",
  },
  21: { // The World (reversed)
    "mind": "The mind is at the finish line and will not cross it — running the same final laps, adding the same qualifications, refusing to declare what is plainly complete.",
    "body": "The body is tired of almost arriving. The withholding of completion is metabolically expensive; the body wants to set down the journey and rest in the place it has already reached.",
    "spirit": "The soul is standing at the threshold of its own wholeness and turning back — not because the completion is not real, but because claiming it means the familiar journey is over.",
    "action": "Tell someone directly: this is finished. Say it out loud to a witness. The reversed World releases the completion through the speech act of declaring it done, not through more internal acknowledgment.",
    "the gift": "The shadow gift is the exposure of why completion is being withheld — the specific fear underneath the final yard: the void after arrival, the loss of the journey's shape.",
    "what to release": "Release the restlessness that has been driving the extra lap. The World reversed is not unfinished work — it is finished work not claimed. The problem is not the doing; it is the receiving.",
    "the seed": "Plant the intention of full arrival — to spend this cycle actually inhabiting the completion rather than immediately treating it as a launching pad for the next insufficient beginning.",
    "the obstacle": "The obstacle is the terror of the ending that is also a beginning — the World reversed withholds completion because the next cycle, the Fool's edge again, is visible on the other side of it.",
    "first steps": "Acknowledge the completion — out loud, to someone who witnessed the work. Not modestly, not performatively. Say: this is done. Let the saying be real.",
    "what has grown": "What has grown is everything that was set in motion — and the fruit is sitting unharvested, complete and real, while you continue adding unnecessary effort to what is already whole.",
    "what is illuminated": "The full moon illuminates the finish line you are standing at but have not crossed — the distance between where you are and where you refuse to declare yourself arrived is now visible as what it is: nothing.",
    "what hides in the light": "The reversed World hides the void — the emptiness that follows real completion, which the withheld completion has been protecting you from. The void is real. It is also the space where the next cycle begins.",
    "what must be released": "Release the chapter in its entirety — not one element, not the problematic parts, but the whole complete arc of this work. Set it down as a finished thing. Let it be over.",
    "how to let go": "Let go with the reverence that the World, even reversed, knows is required — name what it was, honor what it took, and close the door with the full weight of genuine completion.",
    "what emerges": "What emerges when the crossing is finally made is the Fool again — but carrying everything, standing at the next edge, and now knowing that the journey is survivable.",
  },
  22: { // Ace of Wands (reversed)
    "mind": "The mind has encountered the spark and immediately found reasons it will not work — the creative impulse is being evaluated rather than received, and evaluation is extinguishing what it touches.",
    "body": "The body's creative fire is blocked at the source — dammed energy that wants to move but cannot find the outlet, the restlessness of uninitiated potential.",
    "spirit": "The spirit received a flame and did not fan it. The creative invitation arrived and was declined, and the ember is cooling. There is still time, but not much.",
    "action": "Pick up the creative tool you have been avoiding and make one gesture — not the completed work, not the plan, just the single first mark. The blocked Ace needs only the smallest opening.",
    "the gift": "The shadow gift is the revelation of what is blocking the creative threshold — the reversed Ace of Wands names the specific obstacle between you and beginning. That obstacle is the whole teaching.",
    "what to release": "Release the creative project that has been sitting unchosen for so long that it has become a source of guilt rather than inspiration. Either begin it or formally surrender it.",
    "the seed": "Plant the intention of low-stakes beginning — a tiny creative act, stripped of all significance and expectation, performed for no one, completed without judgment.",
    "the obstacle": "The obstacle is the delay at the creative threshold itself — the moment of hesitation that the reversed Ace of Wands represents, extended into habit. The threshold is still there. Cross it.",
    "first steps": "Spend ten minutes on the blocked creative thing. Not to make it good. Not to finish it. Ten minutes as the only commitment, with permission to stop afterward.",
    "what has grown": "What has grown from the creative block is frustration — the accumulation of unclaimed sparks, the restlessness of a self that knows it makes things and has been kept from doing so.",
    "what is illuminated": "The full moon illuminates the creative potential that was received but not acted on — the gap between the spark and the gesture is now fully visible, and so is the cost of the delay.",
    "what hides in the light": "The reversed Ace hides the real fear beneath the delay: not failure but the responsibility of beginning, which is also the responsibility of following through once the fire takes.",
    "what must be released": "Release the creative inhibition — the story that makes beginning impossible. Under the full moon, the Ace of Wands reversed burns the hesitation. What remains is the ember.",
    "how to let go": "Let go through a single act of creative expression — anything made, anything begun, the act of making itself as the release from the blocked state.",
    "what emerges": "What emerges when the blocked Ace is finally given permission is not the masterwork but the opening — the tentative, necessary first gesture that makes everything subsequent possible.",
  },
  23: { // Two of Wands (reversed)
    "mind": "The mind is using planning as a substitute for deciding — the overview from the high window has become a permanent dwelling, and the ships that should have sailed are still in harbor.",
    "body": "The body is restless on familiar ground, and the restlessness is being managed rather than responded to. The ache for the horizon is real; the refusal to move toward it is costing vitality.",
    "spirit": "The spirit sees the larger horizon and is afraid of it — the Two of Wands reversed is the soul that holds the globe but will not commit to the direction that globe is asking it to travel.",
    "action": "Make the decision between the two paths you have been surveying. Not the perfect decision — the actual one, made with the information available, before the window closes.",
    "the gift": "The shadow gift is the revelation of what the familiar feels like when the horizon is refused — the Two of Wands reversed shows you what remaining at the parapet eventually costs.",
    "what to release": "Release the comfortable vantage point. You have been using the view as an excuse not to move. The survey was useful. Its continued use is avoidance.",
    "the seed": "Plant the intention of chosen direction — to commit this cycle to one horizon, one path, one ship launched into actual water rather than kept in the safety of harbor.",
    "the obstacle": "The obstacle is indecision elevated to philosophy — the belief that keeping all options open is wisdom when it is in fact the refusal to let the weight of a genuine choice land.",
    "first steps": "Name the two wands — the two actual paths or commitments before you — in the most concrete language available. Then eliminate one. The elimination is the step.",
    "what has grown": "What has grown from indecision is the paralysis of a vision never launched — the accumulation of surveyed horizons that have been described but never sailed toward.",
    "what is illuminated": "The full moon illuminates the horizon you have been avoiding — closer than fear suggested, more navigable than the delay required you to believe, still available.",
    "what hides in the light": "The reversed Two of Wands hides this: the decision has already been made somewhere in the self. The surveying is covering for a commitment that is already quietly forming.",
    "what must be released": "Release the planning as permission-seeking. No one is going to give you the signal. The Two of Wands reversed releases through the act of departure, not through more preparation.",
    "how to let go": "Let go of the parapet by stepping away from it — the departure itself is the release. The Two reversed lets go by finally choosing the direction and moving.",
    "what emerges": "What emerges from the chosen direction is the person who left — and the particular freedom available only to someone who has committed to a horizon and started moving toward it.",
  },
  24: { // Three of Wands (reversed)
    "mind": "The mind is watching a horizon that is not returning what it was promised — the poor planning is becoming visible, and the ships are delayed or sailing the wrong direction.",
    "body": "The body is carrying the weight of extended overextension — the Three of Wands reversed is the physical cost of expansion launched in too many directions at once.",
    "spirit": "The spirit is learning the difference between vision and fantasy — the reversed Three of Wands is the moment when the ships are later than promised and the question of whether they are coming at all begins to form.",
    "action": "Return to the ground-level work. The expansion has outpaced the foundation; the action this week is repair of the infrastructure rather than further launch.",
    "the gift": "The shadow gift is the education in what does not work — the reversed Three of Wands names precisely what aspect of the planning was inadequate, which the upright card could not have shown you.",
    "what to release": "Release the expectation of returns on a schedule that did not account for reality. The ships may still arrive; they will not arrive when originally planned.",
    "the seed": "Plant the intention of realistic expansion — to commit this cycle to one direction of growth that the current foundation can genuinely sustain, rather than the many directions it cannot.",
    "the obstacle": "The obstacle is the delayed return making the doubt louder — the impatience and second-guessing that arrives when results do not match vision, that can prematurely abandon what still has a chance.",
    "first steps": "Audit what was launched — which initiatives are genuinely delayed and which are genuinely failing. Separate them honestly. Attend to the ones with remaining life.",
    "what has grown": "What has grown in this cycle is enterprise that has exceeded its own capacity — the expansion is real, but it has outrun the infrastructure, and the full moon makes this visible.",
    "what is illuminated": "The full moon illuminates the overextension — the ships launched in too many directions, the energy thinned to the point where none of them are moving with adequate wind.",
    "what hides in the light": "The reversed Three of Wands hides this: the part of the enterprise that is genuinely working, obscured by the noise of what is not. Both are real. Find what is working.",
    "what must be released": "Release the expansion that has no foundation — the initiative, direction, or vision that was launched on enthusiasm rather than capacity. Consolidate before the overextension collapses everything.",
    "how to let go": "Let go by turning inland from the horizon — the ships that are coming will arrive without your vigil. Return to the building. The foundation needs more attention than the horizon.",
    "what emerges": "What emerges from the pruned overextension is a leaner, more sustainable enterprise — the Three of Wands reversed releases in order to rebuild something that can actually sustain the scale of the vision.",
  },
  25: { // Four of Wands (reversed)
    "mind": "The mind is restless inside what should feel like celebration — unable to settle into the stability that has been built, already scanning for the next construction, the belonging felt but not inhabited.",
    "body": "The body is in a space that should feel like home but does not quite — the foundations are real, but something in the structure is incomplete, and the body knows it.",
    "spirit": "The soul is seeking community and arriving at the threshold of it but cannot quite enter — the belonging is visible, desired, and yet something in the reversed Four of Wands keeps the door slightly ajar.",
    "action": "Stop building long enough to inhabit what has been built. The Four of Wands reversed asks for the deliberate act of settling in — not because the home is perfect, but because arrival requires a choice.",
    "the gift": "The shadow gift is the exposure of what makes belonging feel unsafe — the reversed Four of Wands names the wound under the restlessness, the specific history that makes stability feel like a trap.",
    "what to release": "Release the restlessness that masquerades as ambition. You are not looking for the better place — you are avoiding the feelings that arrival brings.",
    "the seed": "Plant the intention of chosen rootedness — to commit this cycle to the community or home you have already built, however imperfect, before seeking the more perfect version that does not yet exist.",
    "the obstacle": "The obstacle is the incomplete celebration — the refusal to mark what has been accomplished, which means the accomplishment remains unreal, which means the foundation feels less solid than it is.",
    "first steps": "Gather the people who witnessed the building and mark the arrival — not a performance, but a genuine act of communal acknowledgment that the threshold has been crossed.",
    "what has grown": "What has grown in this cycle is a structure waiting to become a home — the materials are all there, but the community has not yet been invited in, and community is what makes a structure live.",
    "what is illuminated": "The full moon illuminates the distance between the stability built and the stability felt — the gap is not in the foundation but in the willingness to trust it.",
    "what hides in the light": "The reversed Four of Wands hides the fear beneath the celebration: the dread that what has been built can be taken, that warmth is always provisional, that belonging is always revocable.",
    "what must be released": "Release the need for the arrival to be perfect before it counts. The celebration the reversed Four of Wands demands is the imperfect, genuine, right-now acknowledgment of what actually exists.",
    "how to let go": "Let go of the provisional quality — the holding of belonging at arm's length. The Four of Wands reversed releases by stepping fully through the door and letting it close behind you.",
    "what emerges": "What emerges from the chosen arrival is genuine rootedness — not the performance of belonging, but the felt sense of it, available only to someone who has finally allowed the ground to be home.",
  },
};
