import type { SpreadPositionKey } from "./spreads";

export const CARD_POSITION_DESCRIPTIONS_B_REVERSED: Record<number, Partial<Record<SpreadPositionKey, string>>> = {
  26: { // Five of Wands (reversed)
    "mind": "The conflict has moved underground — competing thoughts no longer argue openly but corrode quietly. Name what the noise is actually about before it names you.",
    "body": "Suppressed combativeness lodges in the jaw and the fists. The body is fighting a war you have decided not to acknowledge.",
    "spirit": "The soul knows the difference between righteous friction and pointless striving — and it has grown exhausted by the latter. What are you still fighting that is not worth the fire?",
    "action": "Stop engaging the skirmish on its own terms. Withdraw, examine whether the fight is yours, and re-enter only if the answer is yes.",
    "the gift": "Hidden in the reversed Five: the moment when you finally refuse to pick up the wand. The grace of walking away from a contest that was never sacred.",
    "what to release": "The compulsion to be in friction — the identity that has formed around struggle, without which you are not sure who you are.",
    "the seed": "Plant the intention to channel competitive energy inward, toward the only contest that actually matters: the one with yesterday's version of yourself.",
    "the obstacle": "Conflict that has become its own reward, burning through resources with no clear opponent and no possible victory.",
    "first steps": "Identify the one argument you have been maintaining out of habit rather than conviction. Drop it this week. Notice what the silence reveals.",
    "what has grown": "What began as creative friction has curdled into chronic irritation. The cycle's harvest is a map of every energy drain you permitted.",
    "what is illuminated": "The full moon shows the conflict was never about what you said it was about. The real contest has been with yourself, and you have been losing on a technicality.",
    "what hides in the light": "Even under full illumination, the fear behind the fighting remains obscured: not that you will lose, but that without the battle you will not know what you want.",
    "what must be released": "The unspoken rivalry that has been poisoning a working relationship. It has done its damage; continued silence only compounds it.",
    "how to let go": "Lay the wand flat on the ground — not in defeat, but as a deliberate choice to stop feeding the fire with your presence.",
    "what emerges": "Unexpected quiet — and in the quiet, a creative impulse that the noise had been drowning out for months.",
  },
  27: { // Six of Wands (reversed)
    "mind": "The mind is rehearsing a victory that has not arrived, or replaying one that has already lost its shine. Both are ways of avoiding the present terrain.",
    "body": "The body carries the deflation of delayed or hollow recognition — a subtle collapse in the shoulders, a performance for an audience that didn't come.",
    "spirit": "The soul that needs the crowd to confirm its worth has tied its depth to something the crowd may not give. What would remain if the recognition never came?",
    "action": "Stop performing for the approval and do the work in private for a while. Real authority does not require witnesses to be real.",
    "the gift": "The reversed Six offers the uncomfortable gift of discovering what you are willing to do when no one is watching and no parade is coming.",
    "what to release": "The ego's investment in being seen to succeed. Release the performance that has been substituting for the thing itself.",
    "the seed": "Plant the intention to measure progress by internal markers alone this cycle — let the validation be yours to give or withhold.",
    "the obstacle": "Ego inflation that sets the bar for success so high — and so dependent on others' reactions — that real accomplishment goes uncelebrated.",
    "first steps": "Name one achievement this week to yourself, privately, without waiting to see whether anyone else notices it first.",
    "what has grown": "The hunger for recognition has grown into a dependency that distorts every interaction. The cycle's harvest is a mirror showing what has been driving the work.",
    "what is illuminated": "The full moon reveals the gap between public persona and private truth — and whether the victory being performed is something you actually wanted.",
    "what hides in the light": "Beneath the reversed crown, the suspicion that you have been celebrated for the wrong things, and that the real work still waits unwitnessed.",
    "what must be released": "The narrative of deserved recognition that has not arrived. The story itself has become the wound.",
    "how to let go": "Dissolve the expectation of the parade. Gratitude for what was accomplished, without the audience, is the only release that holds.",
    "what emerges": "A quieter confidence — stripped of its need for confirmation, and therefore more portable, more sovereign, harder to take away.",
  },
  28: { // Seven of Wands (reversed)
    "mind": "The mind is ceding ground it does not need to surrender, mistaking exhaustion for defeat and retreat for wisdom. Not every challenge requires a defence.",
    "body": "Defensiveness wired into the nervous system is misfiring — the body is braced for threats that have already passed. The guard can lower now.",
    "spirit": "The soul that has stood too long in a defensive crouch forgets it was capable of open posture. What would it mean to stop defending and simply exist?",
    "action": "Stop reflexively protecting every position. Choose what is genuinely worth defending, and let the rest be taken without combat.",
    "the gift": "The reversed Seven strips away the false elevation — what remains when the high ground is surrendered may be more honest and more liveable.",
    "what to release": "Reactivity masquerading as principled defence. Know the difference between a line worth holding and a wall you have built around fear.",
    "the seed": "Plant the intention to choose your battles with discernment rather than adrenaline — to defend only what is truly sacred.",
    "the obstacle": "Defensiveness so automatic it has become a way of engaging the world, excluding genuine collaboration and unguarded exchange.",
    "first steps": "Let one challenge go unanswered this week. Note what happens. Sometimes the silence is its own kind of strength.",
    "what has grown": "The habit of vigilance has grown past its usefulness. The cycle shows not a defended position but an isolated one, and the cost of the long stand.",
    "what is illuminated": "The full moon reveals how much energy has gone into holding a position rather than building something from it. The view from the hill has stayed the same.",
    "what hides in the light": "Even under full illumination, the original wound that made the high ground feel necessary in the first place remains in shadow.",
    "what must be released": "The identity of the embattled defender. It was useful once; now it attracts the very challenges it was meant to repel.",
    "how to let go": "Come down from the hill. The act of descending is not capitulation — it is the choice to stop organising your life around a siege.",
    "what emerges": "Surprising openness — the discovery that what you were protecting was never as fragile as the defensive posture suggested.",
  },
  29: { // Eight of Wands (reversed)
    "mind": "Thoughts are firing but not landing — a mental scatter where information is abundant but signal is absent. Slow the intake before adding more to the queue.",
    "body": "The body is stuck in starting energy with nowhere to go. Thwarted momentum becomes physical restlessness, headaches, the frustration of a current with no channel.",
    "spirit": "The soul knows the difference between a delay and a sign, but the reversed Eight obscures which this is. Sit with the obstruction before naming it.",
    "action": "Stop pushing harder against what is blocked. Find the actual obstruction and address it directly rather than adding force.",
    "the gift": "The enforced pause of the reversed Eight is an invitation to discover whether the destination is still correct — delays can be redirection in disguise.",
    "what to release": "The frustration with the slowdown that is burning more energy than the work itself. Release the grip and let the timing be what it is.",
    "the seed": "Plant the intention to communicate with precision rather than volume — to say the clearest thing once, rather than the urgent thing many times.",
    "the obstacle": "Miscommunication that compounds with each new attempt to correct it. The faster the arrows fly, the further they land from the intended target.",
    "first steps": "Identify the single communication that has gone awry in this cycle and address only that one, clearly and without appended grievances.",
    "what has grown": "What should have arrived quickly has arrived late, distorted, or not at all. The cycle's harvest is a clear lesson about what breaks when pace overtakes intention.",
    "what is illuminated": "The full moon reveals where the obstruction truly is — not in circumstances but in a message that was never sent or a direction that was never chosen.",
    "what hides in the light": "Beneath the stalled momentum, relief — a part of you that was glad for the delay because the destination was not entirely certain.",
    "what must be released": "The frantic pace that preceded the stoppage. The wands need to be retrieved before they are sent again.",
    "how to let go": "Set down the urgency. Not every delay is an emergency, and this one has something to teach if you stop fighting it long enough to listen.",
    "what emerges": "Restored direction — and when the wands finally move again, they move with the precision that the original rush made impossible.",
  },
  30: { // Nine of Wands (reversed)
    "mind": "Old wounds are interpreting new situations, and the mind is responding to threats that are no longer present with defences built for a different battle.",
    "body": "The body is locked in the posture of past injury — bracing against what already happened. The tension is a record, not a warning.",
    "spirit": "The soul is exhausted not by the present moment but by the accumulated weight of every previous one it refused to put down. What history are you still carrying as a weapon?",
    "action": "Stand down. The fight is not happening the way your nervous system insists it is — and staying at high alert is the only remaining threat.",
    "the gift": "The reversed Nine reveals what stubbornness has been protecting: a wound so old it has become part of the architecture. That is worth knowing.",
    "what to release": "The conviction that you cannot afford to lower your guard — the belief that rest means defeat. It does not.",
    "the seed": "Plant the intention to complete this cycle rather than to survive it. Completion requires a different posture than endurance.",
    "the obstacle": "Past damage flooding the present — the inability to assess current circumstances without filtering them through everything that hurt before.",
    "first steps": "Name one present situation that you are experiencing through the lens of a past wound. Distinguish them. They are not the same.",
    "what has grown": "Vigilance that began as wisdom has become compulsion. The cycle's harvest is the recognition of how much energy protectiveness has consumed.",
    "what is illuminated": "The full moon shows the battle lines you drew in a previous season still staked out in your present life, where they no longer belong.",
    "what hides in the light": "Even under the full moon, the original injury that made the fortress necessary stays in shadow — it is the wound that built the walls.",
    "what must be released": "The identity organised around having survived. What you survived is real; making it the defining story is a choice, and it can be unmade.",
    "how to let go": "Set the final wand down not in surrender but in recognition: the battle this wand was for is over. It ended. You made it.",
    "what emerges": "The self that exists beyond the struggle — less armoured, more curious, surprised by how much it enjoys the silence of no longer being at war.",
  },
  31: { // Ten of Wands (reversed)
    "mind": "The mind is finally recognising that the burden was never entirely yours to carry — and in that recognition, something long-compressed begins to breathe.",
    "body": "The back is beginning to straighten. The body is discovering what it feels like when the load is actually set down rather than merely shifted.",
    "spirit": "The soul that has confused suffering with virtue is being shown that putting things down is not abandonment — it is the act of arriving.",
    "action": "Redistribute the load this week. Delegation is not failure; it is the intelligence required to complete the journey without destroying yourself in the process.",
    "the gift": "The reversed Ten brings the gift of impossible burden finally sorted — the moment when over-responsibility is challenged and found to be a choice.",
    "what to release": "Martyrdom. The suffering that has been worn quietly as proof of dedication — set it down, not with drama, but with finality.",
    "the seed": "Plant the intention to arrive at the destination with energy intact. The journey does not require everything you have left.",
    "the obstacle": "The habit of accumulation — the inability to say no before the bundle becomes impossible, and then the inability to set it down once it is.",
    "first steps": "Give back one responsibility that was never legitimately yours. Name it, return it, and resist the guilt that will follow.",
    "what has grown": "The crisis point of over-extension has finally been reached. The cycle's harvest is the undeniable evidence that this cannot continue as it is.",
    "what is illuminated": "The full moon reveals the exact weight of what has been carried, and who has been benefiting from your willingness to carry it.",
    "what hides in the light": "Even under full light, the question of what you would do without the burden stays dark — the load has become the structure, and without it, the shape is unclear.",
    "what must be released": "The specific obligation — the role, the project, the promise — that has been crushing the work that actually matters.",
    "how to let go": "Drop the bundle at the door. Not tidily, not with ceremony — just set it down and step back before you can pick it up again.",
    "what emerges": "Spaciousness — the surprising amount of room that was always there beneath the weight, now suddenly available for the life that was waiting.",
  },
  32: { // Page of Wands (reversed)
    "mind": "The mind is generating heat without light — ideas sparking and dying before they can be caught, enthusiasm consuming itself in the absence of focus.",
    "body": "Ungrounded fire in the body: the restlessness of someone who wants to begin everything and can commit to nothing. Energy needs a container.",
    "spirit": "The soul's creative appetite has turned impatient, consuming the seed before it can root. Hunger this intense requires discipline, not more fuel.",
    "action": "Choose one creative impulse and follow it past the point where the excitement fades. The discipline is the practice, not the beginning.",
    "the gift": "Scattered energy reversed reveals the raw creative force beneath the chaos — the same fire that burns through plans can, directed, burn through obstacles.",
    "what to release": "The intoxication of new beginnings that prevents any single beginning from becoming a middle. Release the serial starting.",
    "the seed": "Plant the intention to see one creative impulse through to a real output — not perfection, just something finished that did not exist before.",
    "the obstacle": "Recklessness burning the fuel before the vehicle is ready. Enthusiasm that outpaces preparation every time.",
    "first steps": "Pick up the one creative project already started and abandoned. Work on it for an hour without beginning something new.",
    "what has grown": "The pattern of bright starts and quiet abandonments has accumulated into a graveyard of half-finished things. The cycle's harvest is uncomfortable inventory.",
    "what is illuminated": "The full moon shows the gap between the identity of a creative person and the evidence of creation — the Page who talks about fire more than tending it.",
    "what hides in the light": "Even in full illumination, the fear that drives the scatter remains: if you commit fully to one thing and it fails, there are no other beginnings left to retreat to.",
    "what must be released": "The fantasy of the brilliant idea that only needs the right moment. The moment is always now; the rest is avoidance.",
    "how to let go": "Release the shiny new impulse before you have acted on the last one. The Page learns discipline by saying no to itself once.",
    "what emerges": "A creative identity with actual roots — the first sense of what you can do when you stay long enough to find out.",
  },
  33: { // Knight of Wands (reversed)
    "mind": "The mind is charging ahead of its evidence — arrogance filling the space where information should be, confidence substituting for knowledge.",
    "body": "The body is burning fast and dirty: all acceleration, no recovery, the physiological signature of someone who will outpace their own capacity.",
    "spirit": "The soul's passion has curdled slightly into performance — a bravado that is starting to convince itself it does not need to check in with the truth.",
    "action": "Stop. Not permanently — just long enough to confirm that the direction chosen is still correct. Charge resumes after recalibration.",
    "the gift": "The reversed Knight's crash reveals how much genuine fire was underneath the posturing — what survives the fall is the real thing.",
    "what to release": "The assumption that forward motion is always the right motion. Release the identification with speed that makes course correction feel like failure.",
    "the seed": "Plant the intention to lead with genuine passion this cycle rather than its performed version — fire that comes from centre, not from the gallery.",
    "the obstacle": "Arrogance that has sealed itself against correction — the Knight who has confused confidence with invulnerability.",
    "first steps": "Ask someone you trust whether the current direction is sound. Not for permission — for the genuine intelligence of a second perspective.",
    "what has grown": "What began as bold action has grown into a pattern of not listening. The cycle's harvest is a map of every bridge burned by moving too fast.",
    "what is illuminated": "The full moon reveals where recklessness was dressed as courage, and where the charge was more about avoiding stillness than reaching a destination.",
    "what hides in the light": "Under the reversed Knight's bravado, the exhaustion of someone who has not stopped long enough to feel how tired they actually are.",
    "what must be released": "The story that slowing down means losing. The Knight who can't stop is not powerful — it is driven, and those are different things.",
    "how to let go": "Dismount. Literally change your pace for a day and see what catches up with you when you are no longer outrunning it.",
    "what emerges": "A matured charge — speed in service of direction, passion that has learned to include the intelligence of the pause.",
  },
  34: { // Queen of Wands (reversed)
    "mind": "The mind is scanning for competition rather than creative possibility — warmth has contracted into jealousy, seeing other flames as threats to its own light.",
    "body": "Possessiveness shows in the body before it reaches the mouth. Notice where the warmth has tightened into grip.",
    "spirit": "The soul's natural radiance is being clouded by comparison. The Queen dimmed by envy is not less powerful — she is powerful in the wrong direction.",
    "action": "Return to your own creative work rather than watching anyone else's. Your fire does not shrink because another burns — it only seems to when you stare at theirs.",
    "the gift": "Reversed, the Queen reveals the shadow that has always accompanied the brightness: the fear that the light can run out, that warmth is finite and must be hoarded.",
    "what to release": "Creative possessiveness — the need to be the only flame in a given room. Let other lights exist without measuring yourself against them.",
    "the seed": "Plant the intention to lead from genuine warmth rather than competitive energy — to let your influence expand through generosity, not dominance.",
    "the obstacle": "Confidence tipped into domination — the creative authority that no longer invites collaboration because it has stopped believing in the value of anything it didn't start.",
    "first steps": "Genuinely celebrate one other person's creative success this week. Not performance — actual pleasure in their fire.",
    "what has grown": "What began as creative confidence has grown edges. The cycle shows how warmth, unchecked, becomes a climate that others need permission to enter.",
    "what is illuminated": "The full moon reveals the moments when radiance became control — when the warmth was conditional on others reflecting it back correctly.",
    "what hides in the light": "Even under full illumination, the original insecurity that jealousy was built on stays hidden: the Queen who was once told her fire was too much.",
    "what must be released": "The creative domain you are holding beyond its season — the project, the role, the relationship where warmth has become ownership.",
    "how to let go": "Pass the torch without conditions. Real creative authority is the only kind that generates more of itself in the giving.",
    "what emerges": "A fiercer and freer warmth — the radiance that returns when it is no longer being rationed by fear.",
  },
  35: { // King of Wands (reversed)
    "mind": "The mind is confusing its vision with reality — mistaking the map for the territory and becoming irritable when the territory refuses to conform.",
    "body": "Imperious energy lodges in the chest and jaw — the physical signature of authority that has stopped listening and started demanding.",
    "spirit": "The soul's visionary capacity is real, but it is being directed by ego rather than by genuine fire. The difference is felt as tyranny by those in the orbit.",
    "action": "Consult someone who will tell you what they actually think. The King who only hears agreement is building on a foundation of mirrors.",
    "the gift": "The reversed King strips the throne of its performance — what remains when the authority is questioned may be the first honest look at whether the vision is still alive.",
    "what to release": "The expectation that others should follow simply because the vision is yours. Leadership earns its following; it does not inherit it.",
    "the seed": "Plant the intention to lead in service of the vision rather than in service of the self — to ask what the work needs rather than what confirms your authority.",
    "the obstacle": "Impulsiveness undermining the very authority it draws on — the King who acts from ego and then cannot understand why others have stopped trusting the direction.",
    "first steps": "In one decision this week, ask for input before deciding. Not as theatre — as genuine inquiry into what you cannot see from the throne.",
    "what has grown": "The visionary fire has become demanding rather than inspiring. The cycle's harvest is an honest accounting of how many people have quietly left the kingdom.",
    "what is illuminated": "The full moon reveals where the King's certainty became rigidity — the exact moment the vision stopped being updated by new information.",
    "what hides in the light": "Even under full illumination, the private doubt that drives the imperious exterior remains invisible: the tyrant is often the most frightened person in the room.",
    "what must be released": "The throne maintained by force of will rather than genuine authority. Power that is not freely given must be constantly defended, and the defence is exhausting.",
    "how to let go": "Step down from the elevated position long enough to stand on level ground with those you lead. The vision does not require the height to be real.",
    "what emerges": "A sovereign energy that no longer needs to dominate to be present — the authority that comes from conviction rather than from the room it has filled.",
  },
  36: { // Ace of Cups (reversed)
    "mind": "The mind has constructed arguments against receiving — emotional logic that makes walls sound like wisdom and distance sound like discernment.",
    "body": "The body is braced against tenderness; something in the musculature has forgotten it is safe to soften. The cup is present, but tipped away from receiving.",
    "spirit": "The soul is standing at the threshold of a new emotional beginning with its back turned. The fear is not that the cup is empty — it is that it will spill.",
    "action": "Lower one defence this week. Not all of them, just one. Choose someone or something worth the risk and let the cup tilt toward receiving.",
    "the gift": "The reversed Ace reveals the exact shape of the armour — which means it also reveals the exact shape of the opening that the armour was built to protect.",
    "what to release": "The grief that has been treated as a permanent condition rather than a wound in the process of healing. Something has been mourned long enough.",
    "the seed": "Plant the intention to be available to a new emotional beginning — not to force one, but to stop actively preventing it.",
    "the obstacle": "Previous loss blocking current receptivity — the cup that was once dropped making it impossible to hold the new one without bracing for impact.",
    "first steps": "Identify one small act of emotional receiving and do it without immediately explaining it away. Let the kindness land before the analysis begins.",
    "what has grown": "The walls built after the last wound have grown into architecture — entire rooms that love cannot reach because the entrances have been sealed.",
    "what is illuminated": "The full moon reveals the cup sitting beside you, full, waiting — and the length of time you have been deliberately not looking at it.",
    "what hides in the light": "Even under full illumination, the grief that built the wall resists being seen directly. The original loss is still protecting itself.",
    "what must be released": "The conviction that emotional self-protection is the same as emotional wisdom. They are not the same, and the body knows the difference.",
    "how to let go": "Allow yourself to be moved — by one conversation, one piece of music, one moment of unexpected beauty. Permission to feel is the entire practice.",
    "what emerges": "Tentative emotional appetite — the cup slowly uprighting, the small shock of discovering that receiving is still possible.",
  },
  37: { // Two of Cups (reversed)
    "mind": "The mind is rehearsing both sides of the connection but finding them misaligned — a growing awareness that what was mirrored may have been projection rather than recognition.",
    "body": "The body senses the imbalance before the mind admits it — the slight tension of giving more than is being returned, the fatigue of compensating.",
    "spirit": "The soul seeks its equal, and the reversed Two asks whether this connection is genuinely reciprocal or beautifully arranged codependence.",
    "action": "Speak what has been left unsaid about the imbalance in this connection. The mirror cannot be repaired without being looked at directly.",
    "the gift": "Reversed, the Two reveals the attachment patterns operating beneath the love — the ways of connecting that were inherited rather than chosen.",
    "what to release": "The relationship dynamic in which you are doing the work for both parties. The cup you keep refilling for someone who is not tending their own.",
    "the seed": "Plant the intention to require genuine reciprocity — not as a demand, but as the honest minimum that makes real connection possible.",
    "the obstacle": "Codependence masquerading as intimacy — the entanglement that feels like union but has quietly absorbed one person's distinctness.",
    "first steps": "Name one thing you have been giving in this connection that has not been returned. Not as accusation — just as honest inventory.",
    "what has grown": "The imbalance that was always present has grown visible. The cycle's harvest is clarity about who has been the cup and who has been drinking.",
    "what is illuminated": "The full moon shows the broken mirror for what it is — two people who once saw each other clearly and have since been reflecting their own need back.",
    "what hides in the light": "Even under full illumination, the original moment of genuine recognition that made the imbalance worth tolerating remains warm and intact.",
    "what must be released": "The version of this connection that exists in the mind rather than in reality — the relationship as it was, as it might be, rather than as it is.",
    "how to let go": "Part with the acknowledgment that what was real between you was real — and that real things can still end. The ceremony is still deserved.",
    "what emerges": "A clearer knowledge of what equal partnership feels like — a standard, hard-won, that will not be abandoned again.",
  },
  38: { // Three of Cups (reversed)
    "mind": "The mind is weary of the social performance — the warmth required on cue, the celebration of things that no longer feel worth celebrating.",
    "body": "The body wants to withdraw from collective energy; its cup is not empty but it is not interested in being raised again just yet.",
    "spirit": "The soul that has overextended in community is quietly starving for solitude. Not all isolation is avoidance — sometimes it is the only honest response to exhaustion.",
    "action": "Give yourself permission to step back from social obligation without guilt. Not everything that gathers is nourishing, and this is a week for honest accounting.",
    "the gift": "Reversed, the Three reveals what the celebration has been covering: the isolation that genuine community would make unnecessary.",
    "what to release": "Forced conviviality — the performance of belonging that substitutes for the real thing and drains you in proportion to its effort.",
    "the seed": "Plant the intention to distinguish between the community that feeds you and the community you maintain out of obligation or fear of being outside.",
    "the obstacle": "Overindulgence that has numbed rather than celebrated — the gathering that has become a way of not being alone with the truth.",
    "first steps": "Decline one social obligation this week that is genuinely optional. Spend that time in honest solitude and see what surfaces.",
    "what has grown": "What began as community has grown into performance. The cycle's harvest is the discovery of how little of the celebration was truly mutual.",
    "what is illuminated": "The full moon shows the true nature of the circle — who is there for shared joy and who is there to be seen being there.",
    "what hides in the light": "Even under full illumination, the genuine longing for community that the reversed Three conceals — the isolation that the overindulgence was trying to cure.",
    "what must be released": "The social identity built around being the one who gathers people. What remains when you stop organising the warmth?",
    "how to let go": "Step back from the circle without drama or announcement. See who notices and what they do about it.",
    "what emerges": "A smaller, quieter, more genuinely held community — and the surprising discovery that it was always available, once the noise of the larger gathering was removed.",
  },
  39: { // Four of Cups (reversed)
    "mind": "The mind is beginning to surface from its long withdrawal — blinking at the world with cautious curiosity, registering again what had gone invisible during the contraction.",
    "body": "Stiffness is loosening; the body that had settled into stillness is reawakening its appetite for movement and contact and stimulation.",
    "spirit": "The soul's necessary retreat has completed its work. What was refused during the withdrawal is being reconsidered with fresher eyes.",
    "action": "Look up. The cup that was being extended has not been withdrawn — it is still there. The apathy has served its purpose; it can be set down now.",
    "the gift": "Reversed, the Four reveals what became visible only in the stillness — the missed opportunity that the withdrawal made possible to finally recognise.",
    "what to release": "The numbness that was appropriate once and has since become a habit of disengagement. The depression served its purpose; thank it and ask it to leave.",
    "the seed": "Plant the intention to re-engage with the one thing that was refused or overlooked during the withdrawal. It is likely still available.",
    "the obstacle": "The residue of apathy — the lingering conviction that nothing will be different this time, that the cup will disappoint the way others have.",
    "first steps": "Accept the offer that has been sitting at the edge of your attention. Not with enthusiasm — just with an open hand.",
    "what has grown": "The period of inward turning has grown into genuine insight. The cycle's harvest is a list of what actually matters, clarified by the absence of distraction.",
    "what is illuminated": "The full moon shows the cup that was there all along — and the length of time it waited without being acknowledged, without being withdrawn.",
    "what hides in the light": "Even as re-engagement begins, the fear that reaching out will return the old dissatisfaction remains half-hidden — the reason the arms were crossed in the first place.",
    "what must be released": "The posture of the withdrawn one. It protected something real; now it is preventing the thing that was being protected from being used.",
    "how to let go": "Reach out. One small, specific gesture toward what was passed over. The release is the extension of the hand.",
    "what emerges": "Renewed participation — tentative but genuine, coloured by the clarity that only a period of real withdrawal can provide.",
  },
  40: { // Five of Cups (reversed)
    "mind": "The mind is beginning to turn from the spilled cups toward the ones still standing — not in denial of the loss, but in the first honest acknowledgment that something remains.",
    "body": "The body is lighter — not healed, but no longer locked in the posture of grief. The shoulders are moving toward open.",
    "spirit": "The soul is discovering that grief does not have to be permanent residence. Recovery is not betrayal; it is the proof that love could be lost in the first place.",
    "action": "Turn around and look at what did not spill. Give it specific attention — this is the active work of recovery, and it is as important as the mourning.",
    "the gift": "Reversed, the Five brings the quiet grace of a grief that has done its full work — the clearing that becomes possible only after genuine loss has been genuinely felt.",
    "what to release": "Prolonged mourning that has tipped from processing into performance — the grief that has become an identity rather than a passage.",
    "the seed": "Plant the intention to carry the two remaining cups forward into the new cycle — not as consolation, but as the actual substance of what continues.",
    "the obstacle": "The guilt of recovery — the suspicion that moving on is a betrayal of what was lost, that grief must be permanent to be honourable.",
    "first steps": "Name the two cups that are still standing. Name them specifically — the relationships, the capacities, the truths that the loss could not take.",
    "what has grown": "The grief has completed a full arc this cycle. The harvest is not the loss — it is the tenderness and the gratitude that the loss made possible.",
    "what is illuminated": "The full moon shows the bridge and the village lights beyond it — and whether you are finally willing to walk toward them.",
    "what hides in the light": "Even in recovery, the exact texture of what was lost stays in shadow — present as warmth, not as wound, and no less real for being held that way.",
    "what must be released": "The three spilled cups. They have been mourned. They do not need to be mourned again in order to honour them.",
    "how to let go": "Walk toward the bridge. The act does not require certainty — it only requires the willingness to take a step in the direction of the living.",
    "what emerges": "A reclaimed emotional life — not the one that existed before the loss, but something that carries the loss as depth rather than as wound.",
  },
  41: { // Six of Cups (reversed)
    "mind": "The mind is living upstream — in a past that has been edited into something more perfect than it was, returning there so often that the present blurs.",
    "body": "The body is being asked to live in two times at once. The physical restlessness of nostalgia — reaching back, longing for a texture of life that no longer exists.",
    "spirit": "The soul is using memory as sanctuary and the present as the place it endures while waiting to return. This is a gentle kind of self-exile.",
    "action": "Bring the quality you are reaching for in the past into the present. Not the situation — the quality. Name it and enact it here.",
    "the gift": "Reversed, the Six reveals what is being avoided by living in memory — the particular discomfort of the present that the past makes bearable to endure.",
    "what to release": "The past as a better place. Honour it, carry what it gave you, and then return to the only life that is actually available to be lived.",
    "the seed": "Plant the intention to nourish the present with the same tenderness that nostalgia gives the past — to become the kind gardener of now.",
    "the obstacle": "An old pattern reactivating under the guise of comfort — a familiar dynamic from an earlier chapter re-emerging dressed in the warmth of the known.",
    "first steps": "Identify what specifically you are retreating to when the past becomes compelling. What is happening in the present that makes it preferable?",
    "what has grown": "The habit of nostalgic escape has grown into a subtle refusal of the present. The cycle's harvest is the recognition of how much of now has gone unlived.",
    "what is illuminated": "The full moon shows the past at its true size — real, formative, finished, and no longer a country with an open border.",
    "what hides in the light": "Even under full illumination, the specific sweetness of the memory that anchors the nostalgia remains immune to scrutiny. Some things are loved past the point of examination.",
    "what must be released": "The comparison between the past and the present that the present can never survive. The game is rigged; the past has had time to be edited.",
    "how to let go": "Let the memory be what it was — real, worth keeping — while releasing its claim on the present. Gratitude is the thing that makes this possible.",
    "what emerges": "A gentler orientation toward now — the present freed from competition with an idealised past, finally allowed to be imperfect and alive.",
  },
  42: { // Seven of Cups (reversed)
    "mind": "The fog is beginning to lift. The mind that was flooded with shimmering options is starting to see which are viable and which were always beautiful distractions.",
    "body": "The body is settling as the fantasy dissipates — the restlessness of too many options resolving into the quieter readiness of having finally chosen.",
    "spirit": "The soul is returning from the dreamscape with something real in hand — the vision that survived the encounter with daylight is the one worth building.",
    "action": "Commit to the one option that has remained after honest examination. The clarity has arrived; act before the new fog of new options rolls in.",
    "the gift": "Reversed, the Seven brings the clarifying gift of illusions fallen away — the sober inventory that follows the enchantment.",
    "what to release": "The last beautiful distraction — the option you are still holding because it is genuinely enticing even though you know it is not real.",
    "the seed": "Plant the intention to move forward on the basis of what is true rather than what is appealing. Reality is not less nourishing than the fantasy.",
    "the obstacle": "The residual pull of the cups that were set down — the brief regret that visits when the chosen path hits its first difficult stretch.",
    "first steps": "Take one concrete action toward the option chosen. Not preparation — action. The clarity is real only when it moves into the world.",
    "what has grown": "The confusion that dominated earlier in the cycle has grown into discernment. The harvest is the capacity to choose that was built through the disorienting abundance.",
    "what is illuminated": "The full moon burns through the remaining fog — the cups are no longer shimmering, they are just cups, and one of them is the right one.",
    "what hides in the light": "Even as clarity arrives, the question of whether the right cup was chosen stays in shadow for a while. Certainty comes after commitment, not before.",
    "what must be released": "The identity of someone with infinite options. A choice means foreclosing other choices, and that is not loss — it is how things become real.",
    "how to let go": "Set down the unchosen cups without ceremony. They were never as solid as they seemed; release them without mourning what they represented.",
    "what emerges": "A grounded creative purpose — something that can be described plainly, worked on daily, and completed. The antidote to the enchanting fog.",
  },
  43: { // Eight of Cups (reversed)
    "mind": "The mind is staying past the point of wisdom — constructing reasons to remain in what it has already assessed as finished, rationalising the avoidance of departure.",
    "body": "The body knows the leaving is necessary and is carrying the tension of a decision that has been made at one level and refused at another.",
    "spirit": "The soul is being kept in a situation it has outgrown by fear dressed as loyalty. The cups are arranged; the arrangement is complete; the reverence is now avoidance.",
    "action": "Name what you are afraid of in the leaving. Then ask whether the fear is proportionate to what staying is costing.",
    "the gift": "Reversed, the Eight reveals the attachment that the dignified departure was always about — the specific cup that is hardest to walk away from.",
    "what to release": "The hope that if you stay long enough, the thing that has run its course will replenish itself. This is not optimism — it is the refusal to complete.",
    "the seed": "Plant the intention to leave before it becomes emergency exit — to choose departure while it is still a dignified act rather than a collapse.",
    "the obstacle": "Fear of the unknown that the leaving opens — the blank beyond the eight arranged cups that looks like nothing rather than like possibility.",
    "first steps": "Name the thing you are walking toward, not just what you are reluctant to leave behind. The Eight reversed needs a destination before the feet will move.",
    "what has grown": "The delay has grown into a specific kind of suffering — the particular ache of knowing and not acting, of staying out of inertia rather than love.",
    "what is illuminated": "The full moon shows clearly that the emotional architecture here no longer fits — and that you have known this for longer than you have admitted.",
    "what hides in the light": "Even under full illumination, the specific attachment — the one cup in the arrangement that made all the others worth assembling — remains tender and resists being left.",
    "what must be released": "The habit of arrangement — the energy spent maintaining the appearance of a life that has already been internally vacated.",
    "how to let go": "Leave before the situation demands it. The dignity of the departure is still available — but only if you take it while it is still a choice.",
    "what emerges": "Movement — belated, somewhat bruised, but real. The first honest step in a new direction after a very long time of facing the old one.",
  },
  44: { // Nine of Cups (reversed)
    "mind": "The mind is satisfied on the surface while something underneath remains hungry. The wish was granted but the wishing was for the wrong thing, or not entirely the right one.",
    "body": "Overindulgence is the body's verdict — too much of what felt like pleasure, applied past the point where it nourished and into the point where it numbed.",
    "spirit": "The soul is discovering that material satisfaction and genuine contentment are different countries. The cups are full; the fullness is not reaching the deep place.",
    "action": "Distinguish between what feels satisfying and what actually is. One honest inventory before continuing to consume what is no longer serving.",
    "the gift": "Reversed, the Nine reveals the specific shape of what the wish was actually for — the deeper desire that the granted one was gesturing toward but did not reach.",
    "what to release": "Complacency that has sealed itself against growth — the satisfaction that says this is enough and then defends the status quo against any new wanting.",
    "the seed": "Plant the intention to get honest about what genuine fulfilment requires — not what looks like fulfilment from the outside, but what actually satisfies from within.",
    "the obstacle": "Overindulgence masking an emptiness — filling the cups repeatedly because the satisfaction does not last, and not yet asking why.",
    "first steps": "Sit with the dissatisfaction rather than immediately reaching for the next cup. What the restlessness points toward is more useful than what it reaches for.",
    "what has grown": "The pattern of seeking satisfaction in external accumulation has matured into evidence of its own limitation. The cycle's harvest is the honest question: is this enough?",
    "what is illuminated": "The full moon reveals the hollow in the wish fulfillment — the nine cups full and the figure still somehow unreached by what they contain.",
    "what hides in the light": "Even under full illumination, the specific unnamed desire that no cup has ever answered stays in shadow — the thing the overindulgence was always trying to address.",
    "what must be released": "The strategy of satisfaction-seeking that has stopped working. Not the desire — just the approach that has proven unable to meet it.",
    "how to let go": "Put down the cup without refilling it immediately. Sit in the pause between satisfaction and the next wanting. The answer lives there.",
    "what emerges": "A cleaner desire — less ornamented, more honestly known, capable finally of recognising what would actually fulfil it.",
  },
  45: { // Ten of Cups (reversed)
    "mind": "The mind is maintaining the image of harmony while registering the discord beneath it — holding the rainbow steady through sheer effort of will.",
    "body": "The body carries the exhaustion of sustained performance — the physical toll of being the one who keeps the peace so that no one else has to feel the cost.",
    "spirit": "The soul is longing for the real version of what the image promises — for the genuine joy rather than its careful maintenance. Outward perfection is its own kind of loneliness.",
    "action": "Name what is not working in the circle. Not to destroy it — but because what is named can be addressed and what is unspoken continues to corrode.",
    "the gift": "Reversed, the Ten reveals the individual sacrifices that were made to sustain the harmony — each person's private cost made briefly visible.",
    "what to release": "The pretence of completion when there is still genuine work to be done. The rainbow is a symbol, not a fact, and symbols require honest tending.",
    "the seed": "Plant the intention to build genuine community rather than maintained community — to let the people in your arc be real rather than arranged.",
    "the obstacle": "The gap between the family or community you are performing and the one you actually inhabit — the distance between the image and the daily texture.",
    "first steps": "Have one honest conversation with someone in your circle about what is actually happening, rather than what should be. The courage is the first step.",
    "what has grown": "The discord that was swallowed for the sake of harmony has grown into its own kind of pressure. The cycle's harvest is the truth that was stored rather than spoken.",
    "what is illuminated": "The full moon shows the faces in the arc at their actual expressions — not the shared-moment pose, but the daily reality of each person's private terrain.",
    "what hides in the light": "Even under full illumination, the genuine love that underlies the strained harmony refuses to be made smaller than the discord. Both things are true.",
    "what must be released": "The image of the emotional life rather than the life itself — the version maintained for others' comfort or social presentation.",
    "how to let go": "Let the circle be messy enough to be real. Harmony that cannot survive difficulty was decoration; harmony that can survive it is home.",
    "what emerges": "A more honest belonging — a circle that has been tested and chosen to remain, held together by something more durable than the image of happiness.",
  },
  46: { // Page of Cups (reversed)
    "mind": "The mind is generating emotional impressions faster than it can evaluate them — mistaking every feeling for a message, confusing sensitivity with information.",
    "body": "The body is picking up signals from the environment without the filter of discernment — absorbing moods and atmospheres that are not its own.",
    "spirit": "The soul is young in its emotional vocabulary and is practicing with intensity rather than accuracy. Not every fish that jumps from the cup was meant for you.",
    "action": "Before acting on the emotional impulse, ask whether it is information or weather. Both are real; only one requires a response.",
    "the gift": "Reversed, the Page reveals the rawness of emotional intelligence before it has learned to hold itself — the gift is the sensitivity itself, awaiting the skills to use it well.",
    "what to release": "Emotional impressionability mistaken for depth — the reactivity that looks like feeling but is closer to being buffeted by what is happening around you.",
    "the seed": "Plant the intention to develop emotional discernment alongside emotional sensitivity — to distinguish between what the heart is receiving and what it is generating.",
    "the obstacle": "Unreliable emotional information — moods that change without clear cause, feelings that lead toward action and then evaporate before arrival.",
    "first steps": "Give the emotional impulse twenty-four hours before acting on it. Not to dismiss it — to see whether it is still there, and therefore worth trusting.",
    "what has grown": "The emotional sensitivity that was once a gift has grown toward dependence — a world so filtered through feeling that reliable perception has become difficult.",
    "what is illuminated": "The full moon shows the daydream at its full scale — both the genuine creative intelligence in it and the ways it has been substituting for actual action.",
    "what hides in the light": "Even under full illumination, the genuine creative gifts embedded in the emotional sensitivity resist being separated from the static. They are tangled together.",
    "what must be released": "The emotional message that has been sitting unsent because it might not be received the way it was intended. The unreliable information is less dangerous out than in.",
    "how to let go": "Share what you have been feeling with someone trustworthy, with the explicit acknowledgment that it may be partial or mistaken. The release is in the honesty, not the accuracy.",
    "what emerges": "The beginning of emotional intelligence — not just emotional sensitivity, but the capacity to work with what is felt rather than be carried by it.",
  },
  47: { // Knight of Cups (reversed)
    "mind": "The mind is in love with the idea of the thing rather than the thing itself — the feeling of pursuit more than any possible arrival, the mood more than the reality.",
    "body": "The body is carrying the particular frustration of desire that never lands — a restlessness that cannot be sated because it was never aimed at something real.",
    "spirit": "The soul is chasing its own reflection in every pool it passes, calling the reflection the beloved. The quest for feeling has replaced the willingness to arrive.",
    "action": "Put down the quest long enough to examine whether what you are pursuing is a destination or a direction — a place to arrive or a feeling to inhabit indefinitely.",
    "the gift": "Reversed, the Knight reveals the attachment to the pursuit itself — the discovery that the romantic ideal was always more comfortable than the real, textured thing it was pointing toward.",
    "what to release": "The pursuit that has become an end in itself — the beautiful motion toward something that is never allowed to arrive because arrival would end the motion.",
    "the seed": "Plant the intention to let what you have been seeking actually find you — to become still enough that the Grail can be offered rather than eternally chased.",
    "the obstacle": "Idealisation so complete that every real version of the thing disappoints — the mood that cannot survive contact with an actual person, project, or place.",
    "first steps": "Name one concrete way to move toward what you have been pursuing romantically or creatively. Not a gesture — a specific, unglamorous step.",
    "what has grown": "The habit of romantic pursuit has grown into a way of avoiding real commitment. The cycle's harvest is the gap between what was sought and what was ever allowed to be found.",
    "what is illuminated": "The full moon reveals the difference between the quest and the Grail — and whether the Knight has been riding away from arrival all along.",
    "what hides in the light": "Even under full illumination, the specific beauty of the pursuit — the genuine aliveness of moving toward something — resists being called avoidance, because it is not only that.",
    "what must be released": "The romantic quest that has replaced the relationship, the project, the life. The Grail was never meant to remain only a direction.",
    "how to let go": "Arrive. Set the horse still. Let the thing you have been seeking meet you in the actual, ordinary moment rather than at the horizon.",
    "what emerges": "A more grounded love — present rather than approaching, available rather than questing, and richer for having survived the transition from motion to stillness.",
  },
  48: { // Queen of Cups (reversed)
    "mind": "The mind is awash in other people's emotional weather — having absorbed so much that it can no longer clearly identify which feelings are its own.",
    "body": "The body has taken on what the empathy could not metabolise — other people's anxiety, grief, or need living in the joints and the gut as if it were native.",
    "spirit": "The soul has been giving beyond its boundaries, and the cost is a kind of spiritual confusion — the well that has been drawn from so frequently it no longer knows its own depth.",
    "action": "Create a boundary with someone or something that has been drawing on your emotional reserves without return. The action is a sentence, or a door closed.",
    "the gift": "Reversed, the Queen reveals the shadow of empathy — the ways that profound sensitivity can, without boundaries, become a form of self-erasure.",
    "what to release": "The pattern of absorbing others' emotional pain as a way of avoiding your own — the empathy that looks outward so it never has to look in.",
    "the seed": "Plant the intention to tend your own emotional life with the same care you extend to others — to become the Queen who can also receive.",
    "the obstacle": "The absence of emotional boundaries — the inability to feel without merging, to care without dissolving, to be present without disappearing.",
    "first steps": "Identify whose feelings you are currently carrying. Name them as theirs rather than yours. This is the first act of a real boundary.",
    "what has grown": "The pattern of emotional over-extension has grown into a structural imbalance. The cycle's harvest is the recognition of how little has been reserved for the self.",
    "what is illuminated": "The full moon reveals the emotional current operating below the surface — what everyone is feeling, yes, but also what the Queen is feeling and has not said.",
    "what hides in the light": "Even under full illumination, the Queen's own deepest emotional need remains unspoken — the person who holds everyone else's feelings is often the last to be asked about her own.",
    "what must be released": "The emotional dynamic in which your empathy is offered without limit. The one who holds everything for everyone is not a Queen — she is a vessel, and vessels empty.",
    "how to let go": "Receive care. Actively, specifically, from someone who has earned the right to give it. The release is the act of allowing yourself to be held.",
    "what emerges": "A boundaried empathy — deeper for what was learned, cleaner for the lines that were drawn, and no longer confused about whose ocean is whose.",
  },
  49: { // King of Cups (reversed)
    "mind": "The composed surface is working too hard — the emotional intelligence that is usually a gift has been pressed into service keeping something contained that is beginning to rise.",
    "body": "The sea is rising beneath the throne. The body that has been calm-presenting is carrying a pressure that the performance of equanimity has been unable to process.",
    "spirit": "The soul's mastery of emotion is becoming mastery over emotion — a subtle but critical difference. What is being suppressed in the name of stability is waiting for a tide.",
    "action": "Find a private, contained space to let the internal turbulence move. Not to perform it — to actually feel it, before it finds its own outlet.",
    "the gift": "Reversed, the King reveals the cost of emotional authority — the depth of what was mastered, and the living water still moving beneath the apparent stillness.",
    "what to release": "The performance of calm that has become indistinguishable from actual calm — the composure that no longer serves anyone, least of all the King who wears it.",
    "the seed": "Plant the intention to let emotional truth be witnessed — not broadcast, but shared, with someone who has earned the intimacy.",
    "the obstacle": "External calm masking internal turbulence — the emotional volatility or manipulation that emerges sideways when the containment finally fails.",
    "first steps": "Admit to yourself what you are actually feeling beneath the equanimity. One sentence. This is not performance — it is the first accurate reading in some time.",
    "what has grown": "The control that was once wisdom has grown into distance. The cycle's harvest is the recognition that no one can reach the King anymore — including the King himself.",
    "what is illuminated": "The full moon reveals what the composed surface was concealing — not weakness, but a living emotional reality that was never meant to be permanently submerged.",
    "what hides in the light": "Even under full illumination, the specific feeling that the King has been working hardest to contain remains submerged. It knows better than to surface in the light.",
    "what must be released": "The role of the emotionally reliable one who cannot have needs. The crown is real; the person wearing it is also a person.",
    "how to let go": "Allow the sea to move. Not the storm — just the natural motion of water that has been held still too long. Movement is not catastrophe.",
    "what emerges": "A more fully inhabited emotional authority — one that includes the capacity to feel the depths it has been governing, and is stronger for the honesty.",
  },
  50: { // Ace of Swords (reversed)
    "mind": "The mind is sharp enough to cut but is turning the blade inward — using its analytical precision against itself rather than in service of clarity.",
    "body": "The nervous system is overclocked — the sword's electric quality running without ground, producing headaches, jaw tension, the physical signature of unresolved mental energy.",
    "spirit": "The soul is circling a truth it already knows and refusing to land. The clarity is present — it is the willingness to act on it that has failed to arrive.",
    "action": "Stop turning the sword on yourself. Point it at the actual problem — the specific situation requiring a clear decision — and make one clean cut.",
    "the gift": "Reversed, the Ace reveals the truth that has been present all along but deliberately avoided — the gift of finally knowing what you have known and refused to acknowledge.",
    "what to release": "The mental loops that simulate thinking while preventing conclusion. Release the analysis that has become its own form of avoidance.",
    "the seed": "Plant the intention to found this cycle on one true, unflinching sentence — even if what it names changes everything that currently stands.",
    "the obstacle": "The truth that is present but refused — the conclusion that the mind has reached and the will has not yet permitted.",
    "first steps": "Write the one sentence you have been arguing yourself out of for weeks. Read it once. That is the sword landing.",
    "what has grown": "The confusion has grown around a truth rather than in the absence of one. The cycle's harvest is the recognition of what has been deliberately kept unclear.",
    "what is illuminated": "The full moon illuminates the sword in its reversed position — the clarity inverted, pointing down, and the precise moment of choosing to look away from what is known.",
    "what hides in the light": "Even under full illumination, the specific truth that the confusion was built to obscure remains just out of direct view. The mind knows where it is.",
    "what must be released": "The protective fog — the deliberately maintained ambiguity that has been easier than the decision the clarity would require.",
    "how to let go": "Speak the truth once, clearly, to the right person or to yourself alone. The sword does not need to be wielded to cut — it only needs to be held upright.",
    "what emerges": "The first breath after a long holding — the surprising relief of a truth finally said aloud, even when what follows it is difficult.",
  },
  51: { // Two of Swords (reversed)
    "mind": "The blindfold is coming off — not gently, but because the weight of what is being withheld from the self has become heavier than the fear of seeing.",
    "body": "The braced posture is beginning to ache. The body that has been holding two swords in suspension is announcing, in its own language, that this cannot continue indefinitely.",
    "spirit": "The soul has been using the peace of the suspended decision as a permanent address. The reversed Two asks: what would you do if you had to choose today?",
    "action": "Seek out the information that has been deliberately refused. It exists. The refusal to look has not made it unavailable — it has only made it more controlling.",
    "the gift": "Reversed, the Two offers the gift of the decision finally forced — the moment when the suspension becomes its own kind of suffering and the choosing becomes a relief.",
    "what to release": "The false peace of deliberate ignorance — the composed stillness that depends on not knowing what is directly behind you.",
    "the seed": "Plant the intention to decide. Not impulsively — but with the acknowledgment that this suspension has a cost, and the cost has been mounting.",
    "the obstacle": "The information that would resolve the stalemate is available but still being refused, because knowing would require acting and acting would require loss.",
    "first steps": "Obtain the one piece of information that has been avoided. Read the message. Look at the account. Have the conversation. The sword cannot land without a target.",
    "what has grown": "The indecision has grown into a structure — an elaborate architecture of not-knowing that has become harder to maintain than any possible decision.",
    "what is illuminated": "The full moon removes the blindfold entirely — the water is revealed behind the figure, and with it, the scale of what was being protected against by the not-choosing.",
    "what hides in the light": "Even under full illumination, the part of you that knows exactly which way you would choose remains very still, hoping not to be asked directly.",
    "what must be released": "The defensive crossing of swords — the posture that was protection and has become isolation, keeping out the decision and everything else along with it.",
    "how to let go": "Lower one sword. Not both — just one. See which truth becomes clearer when the defence is halved. The whole decision does not have to be made at once.",
    "what emerges": "The first current of movement after the long stillness — not certainty, but direction, and the surprising discovery that choosing, even imperfectly, is less painful than the suspension was.",
  },
};
