import type { SpreadPositionKey } from "./spreads";

export const CARD_POSITION_DESCRIPTIONS_A: Record<number, Partial<Record<SpreadPositionKey, string>>> = {
  0: { // The Fool
    "mind": "Your thoughts scatter like seeds on wind — not lost, but seeking soil. Let the mind range freely this week without demanding it arrive anywhere.",
    "body": "The body wants to run before it remembers it can walk. Honor the animal impulse toward movement, but watch for the cliff edge underfoot.",
    "spirit": "The soul arrives naked and unencumbered, trailing no past. This is the week to remember that your deepest self has never been wounded — only the roles it played.",
    "action": "Take the one step you have been deliberating into abstraction. Not all of it — just the first foot off the ledge.",
    "the gift": "This cycle arrives carrying the gift of blank space — the untouched canvas, the unmarked path, the story not yet written.",
    "what to release": "Release the need to know where you are going before you go. The map is not the territory; the territory does not yet exist.",
    "the seed": "Plant the intention of radical beginnership — to approach this cycle as though you have never done this before, because in truth, you have not.",
    "the obstacle": "The obstacle is your own accumulated wisdom, whispering that you already know how this ends. You do not.",
    "first steps": "Walk out the door you have been standing in front of. One literal step into the unknown counts as the whole journey begun.",
    "what has grown": "The thing that has grown is your willingness — the quiet, stubborn fact that you showed up and leapt even without a net.",
    "what is illuminated": "The full moon reveals how much space you have actually been given, and how little of it you claimed as your own.",
    "what hides in the light": "Even under full illumination, the Fool conceals recklessness disguised as faith — examine which leaps were truly free and which were flight.",
    "what must be released": "Set down the persona of the perpetual beginner; at some point innocence becomes a shield against accountability.",
    "how to let go": "Let go the way the Fool does — by simply ceasing to grip. No ceremony. Turn and walk.",
    "what emerges": "What emerges is the first outline of a self you are actively choosing, rather than one that happened to you.",
  },
  1: { // The Magician
    "mind": "The mind is a workshop this week, every tool laid out and gleaming. The question is not whether you have what you need — it is whether you pick it up.",
    "body": "Physical energy channels upward like a conduit between earth and sky. Work with your hands, use your voice, let the body be the instrument of your intention.",
    "spirit": "The spirit stands at the altar of its own making, arms raised, the four elements present. This is the week to remember that you are the ritual.",
    "action": "Choose one goal and direct every available resource toward it with unwavering deliberateness — scatter nothing this week.",
    "the gift": "This cycle's gift is focused potency — the rare alignment of will, skill, and timing that makes things not just possible but inevitable.",
    "what to release": "Release the habit of spreading yourself across every opportunity at once; the Magician's power comes from the channeled point, not the diffuse field.",
    "the seed": "Plant the intention of deliberate creation — choose one thing you will bring into being and name it clearly under this new moon's dark.",
    "the obstacle": "The obstacle is the magician's temptation toward performance: appearing capable rather than becoming it.",
    "first steps": "Gather your materials — physical, mental, relational — and lay them before you. Name each resource you actually have.",
    "what has grown": "What has grown is concrete: a thing you made, a skill you sharpened, a structure that stands because you willed it into standing.",
    "what is illuminated": "The full moon shows the gap between your capability and your application — you have more tools than you have been using.",
    "what hides in the light": "The shadow here is manipulation dressed as manifestation — the Magician can bend reality, and can also bend truth.",
    "what must be released": "Release the project, the goal, the working that has consumed its full measure of your effort. Its completion is real whether or not it looks finished.",
    "how to let go": "Release with intention the same way you created with intention — consciously, deliberately, naming what you are setting down.",
    "what emerges": "What emerges is mastery in a new domain; the Magician's table will be set again, but this time with different instruments.",
  },
  2: { // The High Priestess
    "mind": "The mind does not need more information this week — it needs silence deep enough to hear what it already knows.",
    "body": "The body speaks in a language older than thought this week; attend to its whispers before they become shouts.",
    "spirit": "The spirit dwells behind the veil, deeper than conscious reach. This week it asks only that you stop talking long enough to listen.",
    "action": "Do not act yet. Sit with the question. The High Priestess's action is the deliberate pause before the word is spoken.",
    "the gift": "This cycle's gift is access to the underground river — the current of knowing that flows beneath logic and language.",
    "what to release": "Release the compulsion to explain your knowing. Not every truth needs to be legible to the people around you.",
    "the seed": "Plant the intention of deepened listening — to yourself first, then outward. Let the seed rest in silence rather than willing it to sprout.",
    "the obstacle": "The obstacle is the world's demand for proof. The intuitive path yields no receipts, and this cycle will test your willingness to trust without evidence.",
    "first steps": "Keep the dream journal. Read the symbol that keeps returning. The first step here is paying attention to what you have been dismissing.",
    "what has grown": "What has grown lives underground, invisible to others — an interior knowing that has been quietly consolidating since the new moon.",
    "what is illuminated": "The full moon illuminates the truth you already knew but could not yet name. Now you can say it aloud.",
    "what hides in the light": "What hides in the light is the shadow of the oracle: the part of you that uses mystery as a way to remain unavailable.",
    "what must be released": "Release the secret you have been keeping from yourself. The High Priestess under the full moon has no more patience for willful not-knowing.",
    "how to let go": "Let go in the manner of water — without dramatic gesture, simply finding the lower ground and moving toward it.",
    "what emerges": "What emerges from the veil is a version of you with fewer pretenses and a steadier relationship with the parts of yourself you used to look away from.",
  },
  3: { // The Empress
    "mind": "The mind wants to tend, to nurture, to watch things grow rather than force them. Let thought meander through the garden this week without needing to harvest.",
    "body": "The body is the Empress's domain — its hungers, its pleasures, its need for warmth and beauty. Feed it well this week without apology.",
    "spirit": "The spirit is rooted in the physical this week, not apart from it. The sacred is in the soil, in the meal, in the thing your hands make.",
    "action": "Care for something living — a relationship, a creative project, a garden, your own body. The Empress acts through tending.",
    "the gift": "This cycle brings fertility — not just of the womb but of any container made ready and warm. Creative abundance wants to fill what you open.",
    "what to release": "Release the belief that productivity is the measure of your worth. The Empress produces nothing and yet from her, everything grows.",
    "the seed": "Plant the intention of abundance consciousness — the quiet conviction that there is enough, that you are enough, that the earth beneath you is generous.",
    "the obstacle": "The obstacle is the place where nurturing tips into over-giving, where the Empress exhausts the soil by never letting the field rest.",
    "first steps": "Create one space — physical, temporal, emotional — that is warm, beautiful, and abundant. Let it be both the practice and the promise.",
    "what has grown": "What has grown is lush and unmistakable; the Empress does not produce things that stay invisible. Look at what is full and green.",
    "what is illuminated": "The full moon reveals the depth of your capacity to create and sustain — you have been more generative than you have allowed yourself to know.",
    "what hides in the light": "The shadow here is the mother wound: the part of you that controls through nurturing, or craves the nurturing it has never given itself.",
    "what must be released": "What is ripe must be picked; what is overripe must be composted. The Empress knows when the season has turned.",
    "how to let go": "Let go the way the tree drops fruit — not in grief but in completion, trusting that the seed inside will carry the work forward.",
    "what emerges": "What emerges is a new relationship to abundance: less grasping, more allowing; less producing, more receiving.",
  },
  4: { // The Emperor
    "mind": "The mind this week needs structure — clear categories, firm boundaries between projects, a map of the territory before you enter it.",
    "body": "The body benefits from discipline this week, not punishment. Consistent rhythms, adequate rest, the dignity of a schedule kept.",
    "spirit": "The spirit does not float free this week but takes a throne — the inner life needs governance, not just exploration.",
    "action": "Build the framework. Write the plan. Set the rule for yourself that you will actually follow. Sovereignty begins with self-governance.",
    "the gift": "This cycle's gift is structural clarity — the Emperor arrives to show you where chaos has been draining your power and how to reclaim it.",
    "what to release": "Release the structures that were inherited rather than chosen — the rules you follow because someone once told you they were rules.",
    "the seed": "Plant the intention of considered authority: to build, this cycle, a structure that serves your actual life rather than performing order for others.",
    "the obstacle": "The obstacle is the rigidity that passes for stability — the Emperor's shadow is a kingdom built too thick to let new life through the walls.",
    "first steps": "Identify the one domain of your life where chaos has been ruling unopposed, and draw a single clear boundary there.",
    "what has grown": "What has grown is a structure — a habit, a boundary, a system — that now stands on its own and no longer requires constant maintenance.",
    "what is illuminated": "The full moon shows which foundations were built to last and which were built to impress. One will stand; one will not.",
    "what hides in the light": "The Emperor in full light casts a long shadow: the fear of vulnerability disguised as command, the loneliness inside the fortress.",
    "what must be released": "The reign is complete; it is time to hand the scepter to whoever or whatever comes next. You built it; you do not have to be it forever.",
    "how to let go": "Let go with dignity — formally, deliberately, as a ruler abdicates rather than a soldier retreating.",
    "what emerges": "What emerges is leadership from a new posture: not from the throne but from beside it, guidance rather than command.",
  },
  5: { // The Hierophant
    "mind": "The mind looks for teachers this week — for tradition, lineage, the accumulated wisdom of others who have walked this path before.",
    "body": "Ritual is the body's way of knowing. Establish a physical practice this week that carries meaning, however small.",
    "spirit": "The spirit hungers for belonging to something larger — a tradition, a community, a lineage of meaning that extends past one lifetime.",
    "action": "Seek a teacher, a mentor, or a tradition. The Hierophant's action is the formal act of learning from what has been handed down.",
    "the gift": "This cycle's gift is initiation — entry into a body of knowledge or community of practice that will change how you understand yourself.",
    "what to release": "Release the lone-wolf mythology. Wisdom was not meant to be reinvented by each individual alone; it was meant to be transmitted.",
    "the seed": "Plant the intention of studied devotion: to commit this cycle to learning something from within a tradition, not just beside it.",
    "the obstacle": "The obstacle is dogma — the moment the institution's preservation becomes more important than the truth it was built to transmit.",
    "first steps": "Find the community, the text, or the teacher that holds the knowledge you are approaching, and make the first act of formal approach.",
    "what has grown": "What has grown is wisdom with roots — understanding that is now connected to a tradition rather than floating free.",
    "what is illuminated": "The full moon reveals which of your beliefs came from genuine study and which came from unexamined inheritance.",
    "what hides in the light": "The shadow is the cult of personality and the comfort of conformity — the way institutions protect themselves at the expense of the individual seeker.",
    "what must be released": "Release your allegiance to a teaching you have outgrown. Gratitude and departure are not contradictions.",
    "how to let go": "Let go through formal acknowledgment — honor what the tradition gave you before you step beyond its walls.",
    "what emerges": "What emerges is a self-authored spirituality, informed by everything you received but no longer defined by it.",
  },
  6: { // The Lovers
    "mind": "The mind faces a fork this week — not between good and bad, but between two genuine goods. Clarity on your deepest values is the only map that will serve you.",
    "body": "The body knows its alignments and its misalignments; it will tell you clearly which choice is yours if you are willing to feel the answer.",
    "spirit": "The soul this week is in a state of deep recognition — the sacred encounter with another or with a part of itself that has been held at distance.",
    "action": "Make the choice you have been avoiding. The Lovers card does not wait; it asks for commitment to what you genuinely value over what you merely want.",
    "the gift": "This cycle brings the gift of resonance — encounters, connections, and inner alignments that feel fated because they are authentic.",
    "what to release": "Release the relationship, internal or external, that requires you to be less than you are in order to sustain it.",
    "the seed": "Plant the intention of conscious union — to approach this cycle's connections (with others, with work, with yourself) as sacred choices rather than accidents.",
    "the obstacle": "The obstacle is the fear of choosing — because choosing means foreclosing, and the Lovers card demands the full commitment that preference requires.",
    "first steps": "Name, honestly and privately, what you truly value most in this domain. Do not edit it for palatability.",
    "what has grown": "What has grown is the depth of a connection — the thing between you and another (or between you and your calling) that now has real roots.",
    "what is illuminated": "The full moon illuminates the places where your values and your choices have diverged, and the cost of that divergence.",
    "what hides in the light": "The shadow is projection: the beloved self you see in another, the disowned self you blame in them when they disappoint.",
    "what must be released": "Release the relationship or alliance that has served its purpose but no longer reflects who either party is becoming.",
    "how to let go": "Let go with love — this is the Lovers' way. Not with indifference, not with bitterness, but with the dignity of genuine care.",
    "what emerges": "What emerges is a clearer picture of who you are and what you will stand beside — the self that knows its own yes and its own no.",
  },
  7: { // The Chariot
    "mind": "The mind this week is a charioteer driving two horses of opposing nature. Victory comes not from silencing one but from holding both in directed forward motion.",
    "body": "Physical momentum is available this week — harness it deliberately. The body is capable of more than you have been demanding from it.",
    "spirit": "The spirit wins its battles not through spiritual bypass but through mastery of the opposing forces within — the Chariot's victory is always interior first.",
    "action": "Move. Do not wait for perfect conditions or perfect resolve. Harness what you have and drive it in one direction with everything you can bring.",
    "the gift": "This cycle's gift is the will to overcome — the fierce, clear energy that rises when you decide to move through resistance rather than around it.",
    "what to release": "Release the illusion that harmony means the absence of opposition. The Chariot moves forward precisely because the tension is held, not resolved.",
    "the seed": "Plant the intention of directed will — to commit this cycle to one overarching movement and subordinate everything else to that advance.",
    "the obstacle": "The obstacle is loss of control: the moment the opposing forces in harness pull against each other rather than forward, and the chariot veers.",
    "first steps": "Name the two opposing forces in your situation — the conflicting desires, fears, or demands. Name them, then ask: what single direction do I want both to serve?",
    "what has grown": "What has grown is hard-won ground — territory you claimed through sheer determination, mile by contested mile.",
    "what is illuminated": "The full moon shows how much distance you have actually covered, and which internal battles you have already won without giving yourself credit.",
    "what hides in the light": "The shadow of the Chariot is conquest without consideration: the drive to win that flattens everything it does not recognize as enemy or ally.",
    "what must be released": "The campaign is over. Release the war footing; the state of constant mobilization has done its work.",
    "how to let go": "Let go the reins slowly, deliberately — the horses have been running hard, and a sudden release is as dangerous as a refusal to stop.",
    "what emerges": "What emerges is a new question: having won, what now? The Chariot carries you to the threshold of a different kind of problem.",
  },
  8: { // Strength
    "mind": "The mind this week is asked to hold difficulty without flinching — not to solve the beast, but to look at it steadily and refuse to be afraid.",
    "body": "True physical strength this week is not force; it is the sustained exertion that comes from calm, the endurance available when panic does not waste the reserves.",
    "spirit": "The spirit's courage this week is quieter than heroism — the daily choice to remain open, compassionate, and whole in the face of what frightens you.",
    "action": "Approach the difficult person, the frightening creative risk, the shadow you have been circling. Approach it gently, without armor, as the figure in the card approaches the lion.",
    "the gift": "This cycle's gift is the discovery that the thing you feared is not as wild as you believed — and that your gentleness is stronger than your defense.",
    "what to release": "Release the strategy of force. You have been trying to overcome by will what can only be tamed by presence.",
    "the seed": "Plant the intention of compassionate courage — the willingness to stay in the difficult place long enough for it to yield something true.",
    "the obstacle": "The obstacle is the grip of instinct — the part of you that wants to run or dominate rather than remain in calm relationship with what is feared.",
    "first steps": "Identify the one thing you have been avoiding through distraction, busyness, or delegated courage. Walk toward it. Bring only your attention.",
    "what has grown": "What has grown is a new relationship with your own darkness — a working truce where once there was only war.",
    "what is illuminated": "The full moon reveals that what you have been fighting was never separate from you; the lion is yours.",
    "what hides in the light": "The shadow here is spiritual bypassing — gentleness used as a way to deny the real danger or the legitimate anger.",
    "what must be released": "Release the struggle. The lion is tamed; continued wrestling is now its own kind of fear.",
    "how to let go": "Let go through presence rather than force — simply be with the thing you are releasing until it no longer needs to be held.",
    "what emerges": "What emerges is integrated power: the part of you that was once a source of fear has become a source of strength.",
  },
  9: { // The Hermit
    "mind": "The mind needs its cave this week — not isolation as avoidance, but solitude as the condition in which real thought becomes possible.",
    "body": "The body needs slow, deliberate care this week rather than exertion. Rest, silence, and retreat are not luxuries; they are the practice.",
    "spirit": "The spirit requires withdrawal from the collective field in order to hear its own frequency clearly. The lantern only illuminates the single path beneath your feet.",
    "action": "Withdraw. The Hermit's action is the deliberate step away from the noise — schedule the retreat, take the long walk alone, turn off the world for one full day.",
    "the gift": "This cycle's gift is the lantern — the inner light that has been growing in the dark, that you will carry back when the time for return comes.",
    "what to release": "Release the obligation to be available, present, and socially legible at all times. You are allowed to disappear into yourself.",
    "the seed": "Plant the intention of inner authority — to spend this cycle learning to trust the light you carry rather than always seeking external illumination.",
    "the obstacle": "The obstacle is the seduction of hermitage as permanent state — the way solitude can become a justification for never returning to the world with what was found.",
    "first steps": "Create genuine solitude — an hour, an afternoon, a day — without device, obligation, or performance of productivity. Notice what surfaces.",
    "what has grown": "What has grown in the dark and the quiet is wisdom you did not know you were accumulating. The Hermit's cave is also a laboratory.",
    "what is illuminated": "The full moon shows the path you walked in solitude — not wasted wandering but a deliberate arc toward something real.",
    "what hides in the light": "The shadow is the wound of withdrawal: the loneliness that chose the cave because belonging felt too dangerous to risk.",
    "what must be released": "Release the retreat. The lantern was lit for a reason; the world needs what you found in the dark.",
    "how to let go": "Descend the mountain the way you climbed it — slowly, deliberately, with the lantern still held up.",
    "what emerges": "What emerges is the teacher, the guide, the self that was forged in solitude and now has something worth bringing back.",
  },
  10: { // Wheel of Fortune
    "mind": "The mind this week is asked to hold two truths: that you are not in control of the wheel's turning, and that your response to the turn is entirely yours.",
    "body": "The body rides the wheel too — attend to where it is in its own cycle, neither forcing energy that is not there nor suppressing what rises.",
    "spirit": "The spirit practices non-attachment this week — the capacity to remain centered as the wheel turns beneath you, neither clinging to the high nor dreading the descent.",
    "action": "Work with the momentum that is already present in your life rather than against it. The Wheel asks you to read the current and move accordingly.",
    "the gift": "This cycle brings the gift of timing — an alignment of circumstances that will not be available again in exactly this configuration. Use it.",
    "what to release": "Release the belief that you are the exception to impermanence. The wheel turns for every person and every situation, always.",
    "the seed": "Plant the intention of graceful adaptability — the willingness to receive what the wheel brings rather than demanding it stop at your preferred position.",
    "the obstacle": "The obstacle is the refusal to accept the turn — the energy wasted fighting the direction of an inexorable cycle.",
    "first steps": "Look at what is turning in your life right now — what is rising, what is falling — and make one decision that moves with rather than against the momentum.",
    "what has grown": "What has grown is hard to own: a cycle turned in your favor, and what flourished was partly luck, partly readiness. Both are true.",
    "what is illuminated": "The full moon illuminates the larger pattern — you can see now where you are in the cycle that has been turning beneath your conscious life.",
    "what hides in the light": "The shadow is the gambler: the belief that because the wheel can bring luck, effort and preparation are irrelevant.",
    "what must be released": "This turn of the wheel is complete. Release your grip on this particular configuration of circumstances — another turn is already beginning.",
    "how to let go": "Let go the way you would release a boat into a current: not abandoning it, but ceasing to hold it back from where the river will carry it.",
    "what emerges": "What emerges is a new chapter whose beginning you will only recognize in retrospect. Let it be strange; let it be new.",
  },
  11: { // Justice
    "mind": "The mind this week is called to impartiality — to look at your situation as a witness rather than an advocate, without flinching from what the evidence shows.",
    "body": "The body holds the account of every imbalance. This week, attend to what has been neglected, overtaxed, or asked to absorb what is not its to carry.",
    "spirit": "The spirit's work this week is moral clarity — the willingness to know the truth of your own actions without excusing what does not merit excuse.",
    "action": "Make the decision you have been avoiding because it requires you to be fair when you wanted to be partial. Justice is not comfortable; do it anyway.",
    "the gift": "This cycle's gift is clarity of consequence — the restoration of order that comes when truth is finally spoken and accounted for.",
    "what to release": "Release the version of the story where you bear no responsibility. The scales do not lie, and the part you played is the part that belongs to you.",
    "the seed": "Plant the intention of accountability — to enter this cycle willing to see clearly, act fairly, and hold the line between what is and what you wish were so.",
    "the obstacle": "The obstacle is the fear of the verdict — the part of you that will not seek the truth because you are not sure you can bear the answer.",
    "first steps": "Write the list: what is owed (to you, by you), what has been out of balance, what you have been pretending is fair when it is not. Start there.",
    "what has grown": "What has grown is the record — the accumulated weight of cause and effect that has been building since the new moon toward this reckoning.",
    "what is illuminated": "The full moon illuminates the scales exactly as they are: the imbalances you have been rationalizing, and the truths you have been softening.",
    "what hides in the light": "The shadow of Justice is the punisher: the one who uses the standard of fairness to wound rather than to heal.",
    "what must be released": "Release the grievance you have been carrying as evidence. The case is closed; continuing to hold it is the only remaining injustice.",
    "how to let go": "Let go through formal acknowledgment: name what happened, name your part in it, and close the ledger deliberately.",
    "what emerges": "What emerges is equilibrium — not the false peace of denial, but the settled quiet that comes after a true reckoning.",
  },
  12: { // The Hanged Man
    "mind": "The mind, suspended, sees everything upside down — and discovers that several things it has been treating as fixed are only fixed from one angle.",
    "body": "The body is asked to be still this week. Not the stillness of exhaustion but the voluntary surrender of the person who chooses to hang rather than flail.",
    "spirit": "The spirit gains this week not by seeking but by waiting — by becoming a vessel for what arrives when the doing stops.",
    "action": "The Hanged Man's action is the willing pause. Stop the project, the argument, the chase. Choose to wait deliberately rather than having waiting forced upon you.",
    "the gift": "This cycle's gift is the revelation that arrives only through surrender — the answer that could not be chased, only received.",
    "what to release": "Release your grip on control. Not everything — but the specific place where your holding on is the very thing preventing movement.",
    "the seed": "Plant the intention of patient suspension: to give this cycle's central question the unhurried time it requires before demanding an answer.",
    "the obstacle": "The obstacle is the ego's horror of looking unproductive. The Hanged Man appears to accomplish nothing, and is accomplishing everything.",
    "first steps": "Identify the thing you have been forcing. Stop. Allow the suspension. Notify the relevant parties if needed, but stop the forcing.",
    "what has grown": "What has grown is wisdom you could not have acquired through any amount of striving — it required the angle only surrender makes available.",
    "what is illuminated": "The full moon reveals the new perspective you have been slowly, involuntarily gaining. What you once called a problem now looks like a door.",
    "what hides in the light": "The shadow here is martyrdom: the person who calls their suffering a spiritual practice in order to avoid the action that would end it.",
    "what must be released": "The waiting is complete. What was learned in suspension was worth the stillness; now the tree needs to let the fruit fall.",
    "how to let go": "Let go with the acceptance that made the hanging bearable — not dramatically, but with the same quiet yielding that began it.",
    "what emerges": "What emerges is a self reoriented: you will not look at the world from the same angle again, and that is the whole point.",
  },
  13: { // Death
    "mind": "The mind this week mourns what it is releasing — and the mourning is real, not to be hurried. But beneath the grief, something is thinking new thoughts.",
    "body": "The body understands endings at a cellular level. Rest this week as the system reorganizes; what feels like fatigue may be transformation.",
    "spirit": "The soul does not fear Death — only the persona does. This week the spirit asks: which part of you is afraid of ending, and what would you be without it?",
    "action": "Name the thing that must end, and take one concrete action toward that ending. The Death card does not wait for comfort; it asks for honest completion.",
    "the gift": "This cycle's gift is the cleared ground — the fertile emptiness that only follows a genuine ending and precedes a genuine beginning.",
    "what to release": "Release the version of yourself that has become a costume — the identity, role, or story that once fit but no longer does.",
    "the seed": "Plant the intention of willing transformation — to move through this cycle's required ending consciously rather than being dragged through it.",
    "the obstacle": "The obstacle is grief masquerading as preservation — the attachment to what was that prevents honest engagement with what is.",
    "first steps": "Name the thing that is already dead but that you are still trying to keep alive through willpower. Let yourself know what you already know.",
    "what has grown": "What has grown in the time since the new moon has completed its life cycle. The growth was real; so is the ending.",
    "what is illuminated": "The full moon illuminates the bones of what is over: stripped of pretense, the ending is visible in its entirety. It is done.",
    "what hides in the light": "The shadow of Death is the refusal to grieve — the spiritual claim that endings are only transitions, used to skip the real feeling of loss.",
    "what must be released": "This is the Death card at the full moon: the major release. Name it. Let it be complete.",
    "how to let go": "Let go the way the leaves let go — not all at once, but in the way that is already happening. Stop holding them on.",
    "what emerges": "What emerges from this ending will not look like what ended. It will be new. Let that be strange and let it be real.",
  },
  14: { // Temperance
    "mind": "The mind this week is an alchemist's laboratory — the work is not to choose between thoughts but to find the precise proportion that produces something new.",
    "body": "The body flourishes this week under moderate, consistent care rather than intense effort followed by neglect. Find the sustainable rhythm.",
    "spirit": "The spirit practices the long patience this week — the alchemy that does not rush the reaction, that trusts the work happening in the vessel.",
    "action": "Find the middle path between two approaches you have been treating as mutually exclusive. The Temperance card is the practice of integration, not compromise.",
    "the gift": "This cycle's gift is the alchemy of combination — the discovery that two elements you have held apart, when poured together, create something neither could be alone.",
    "what to release": "Release the extremism. The all-or-nothing approach has been consuming fuel that patience would preserve.",
    "the seed": "Plant the intention of long-arc integration — to move through this cycle mixing, adjusting, and refining rather than demanding immediate perfection.",
    "the obstacle": "The obstacle is the seduction of intensity: the conviction that only the extreme gesture is the real one, that moderation is mediocrity.",
    "first steps": "Identify the two things in your life that need to be blended rather than chosen between. Begin the slow pour: a little of each, back and forth.",
    "what has grown": "What has grown is integrated — not one thing alone but the compound that emerged from the sustained practice of combination.",
    "what is illuminated": "The full moon illuminates the result of the long alchemy: what you have been quietly mixing is now visible in its transformed form.",
    "what hides in the light": "The shadow of Temperance is the avoidance of intensity dressed as balance — using moderation to never fully commit to anything.",
    "what must be released": "Release the formula. The alchemy has worked; stop adjusting what is already complete.",
    "how to let go": "Let go with the serene steadiness of Temperance itself — not as a dramatic act but as a quiet return to equilibrium.",
    "what emerges": "What emerges is integration: a self no longer split between competing imperatives, but holding both in a new and workable proportion.",
  },
  15: { // The Devil
    "mind": "The mind this week circles the same thoughts on the same loop. Notice the obsession — not to shame it, but to ask what it is standing in for.",
    "body": "The body carries the weight of what the mind refuses to face. This week, attend to the physical manifestations of what you have been suppressing or overindulging.",
    "spirit": "The spirit's work this week is shadow integration — the unflinching look at what you have chained to the basement and what it costs to keep it there.",
    "action": "Look directly at the one compulsion, addiction, or avoidance that has been running your life from the background. Name it without the shame that keeps it in power.",
    "the gift": "This cycle's gift is the revelation of bondage — and the discovery that you hold the key, that the chains are real but they are yours.",
    "what to release": "Release the narrative that this behavior or pattern defines you. The Devil shows you what is operating, not what you irrevocably are.",
    "the seed": "Plant the intention of honest shadow-work — to move through this cycle bringing one dark thing into the light where it loses power over you.",
    "the obstacle": "The obstacle is the pleasure of the cage: the comfort of familiar limitation, the relief of never having to ask more of yourself.",
    "first steps": "Name the chain — the specific behavior, thought pattern, or relationship that keeps you small. Name it without drama, without resolution, just the name.",
    "what has grown": "What has grown in shadow may not be comfortable to name, but under the full moon it must be seen: what you have been feeding in the dark is real.",
    "what is illuminated": "The full moon illuminates the exact mechanism of bondage — not just what binds you, but how you maintain it, and why.",
    "what hides in the light": "The shadow of the Devil is the shadow's shadow: the righteous refusal to look at your own complicity in your own captivity.",
    "what must be released": "The chain breaks here. Not in a burst of willpower, but in the full-moon clarity that makes continued pretense impossible.",
    "how to let go": "Let go the way someone unlocks a shackle they have been wearing so long they forgot it was a key they held: slowly, with shock at their own agency.",
    "what emerges": "What emerges from the Devil's shadow is reclaimed power — the energy that was consumed by the compulsion, now available for something else.",
  },
  16: { // The Tower
    "mind": "The mind this week faces a collapse — a belief structure, an assumption, a mental architecture that is being struck by lightning and will not survive the week intact.",
    "body": "The body knows before the mind does that something must break. Attend to the shock you are carrying and give it physical release.",
    "spirit": "The spirit is not destroyed by the Tower; it was the person trapped inside it. What is falling is not you — it is the structure that was too small to hold you.",
    "action": "Stop defending the structure you know is compromised. The Tower's action is to exit the building before it falls rather than going down with it.",
    "the gift": "This cycle's gift is radical liberation — the revelation that what you built on false foundations needed to fall, and that you survive the falling.",
    "what to release": "Release the lie that has been load-bearing. The Tower falls because it was built on something that was never true.",
    "the seed": "Plant the intention of honest rebuilding — to enter this cycle willing to clear the rubble before laying new foundations, however long that takes.",
    "the obstacle": "The obstacle is the terror of the collapse — the paralysis that prevents you from seeing that you are not the Tower; you are the person escaping it.",
    "first steps": "Identify the structural lie — the premise your current life is organized around that you know, somewhere, is false. Begin there.",
    "what has grown": "What has grown, this full moon reveals, was built on unstable ground. The falling was not a failure; it was the ground's honesty finally expressing itself.",
    "what is illuminated": "The full moon illuminates the rubble — and in the rubble, the thing that survived. Find that. It is what was real.",
    "what hides in the light": "The shadow of the Tower is the nihilist: the one who, having survived one collapse, decides all structures are false and refuses to build again.",
    "what must be released": "Release the ruins. Standing in the rubble insisting the walls are still standing is the Tower's most insidious aftermath.",
    "how to let go": "Let go by walking away from the wreckage. You cannot rebuild from inside a collapsed structure.",
    "what emerges": "What emerges from the Tower is the survivor who now knows what they can actually withstand — and the freedom of a cleared site.",
  },
  17: { // The Star
    "mind": "The mind this week is asked to practice hope — not naive optimism, but the disciplined refusal to let the worst interpretation be the final one.",
    "body": "The body needs replenishment this week, not exertion. Like water poured back into the earth, allow restoration before renewal.",
    "spirit": "The spirit, after darkness, looks up. This week the soul rehearses trust — the tentative, brave act of believing again.",
    "action": "Attend to what genuinely restores you — not what numbs, not what distracts, but what actually heals. The Star's action is the act of self-restoration.",
    "the gift": "This cycle's gift is renewed faith — not in a system or a person but in the simple, radical possibility that things can become beautiful again.",
    "what to release": "Release the cynicism you adopted as protection. It served you when you needed it, but it costs too much to carry forever.",
    "the seed": "Plant the intention of renewal — the willingness to begin again, to hope again, to reach upward even before there is evidence that the reaching is warranted.",
    "the obstacle": "The obstacle is the memory of the Tower: the difficulty of trusting again after a collapse, the scar tissue that makes opening feel dangerous.",
    "first steps": "Find one thing — one small, tangible thing — that represents the future you want to move toward. Hold it. Let it matter.",
    "what has grown": "What has grown in the gentle time since the new moon is fragile and real: the first new growth on cleared ground.",
    "what is illuminated": "The full moon illuminates the healing that has been happening quietly — you are further from the devastation than you have allowed yourself to believe.",
    "what hides in the light": "The shadow of the Star is wishful thinking: the hope that does not do the work of rebuilding, that waits for someone else to pour the water.",
    "what must be released": "Release the wound as identity. The Star says: you were injured, and you are not only the injury.",
    "how to let go": "Let go the way water is poured out — gently, steadily, with the trust that it goes where it needs to go.",
    "what emerges": "What emerges is the faith that was impossible after the darkness: quiet, tested, and for that very reason, real.",
  },
  18: { // The Moon
    "mind": "The mind this week is unreliable — not broken, but dream-fed, moving through territory where the straight path bends and familiar things cast unfamiliar shadows.",
    "body": "The body may be confused this week by what it thinks it fears. Attend to the sensation itself, not the story the mind builds around it.",
    "spirit": "The spirit descends this week into its own deep waters — the unconscious, the symbolic, the half-seen. Do not demand clarity from what lives in the dark.",
    "action": "Do not make major decisions this week. The Moon asks you to sit with the uncertainty until the tide gives you more information.",
    "the gift": "This cycle's gift is access to the unconscious — the symbols, fears, and deep psychic material that can only surface when the rational mind surrenders its vigil.",
    "what to release": "Release the demand for clarity. Some things are meant to be approached sideways, in the dark, by feel.",
    "the seed": "Plant the intention of deep-sea diving — to enter this cycle willing to not understand what you find until it is ready to be understood.",
    "the obstacle": "The obstacle is the labyrinth of your own fears — the Moon card does not create the monsters in the path, it only removes the light that was hiding them.",
    "first steps": "Begin a dream record. The Moon communicates in images, and the first step is simply paying attention to what arrives in the dark.",
    "what has grown": "What has grown since the new moon has been hidden from your conscious mind — but it has been growing, and the full moon shows it now, strange and alive.",
    "what is illuminated": "The full moon illuminates the fear — not to confirm it, but to show it in its actual proportions, which are always smaller than the dark makes them seem.",
    "what hides in the light": "The shadow of the Moon is the shadow itself: the things that go back under when you stop looking, that will need to be faced again on the next cycle.",
    "what must be released": "Release the illusion you have been inhabiting. You have known it was an illusion for some time; the full moon ends the useful portion of the dream.",
    "how to let go": "Let go by waking up — by choosing to emerge from the distorted water of the Moon's depths and stand on dry ground.",
    "what emerges": "What emerges from the Moon's cycle is a self that is no longer afraid of its own darkness — that has walked the path and arrived on the other side.",
  },
  19: { // The Sun
    "mind": "The mind this week is clear and generous. Let your thoughts have the warmth and openness of a cloudless morning — full presence without agenda.",
    "body": "The body wants to be outside, visible, moving through warmth. Do not keep it indoors this week — the Sun's work is done in the light.",
    "spirit": "The spirit returns to its most essential joy this week. Strip away everything that is not delight and notice what remains.",
    "action": "Let yourself be seen doing something you love. The Sun's action is the act of undefended joy — play, create, celebrate, without irony.",
    "the gift": "This cycle's gift is radiance — the particular warmth that comes from being fully yourself, which turns out to be the most generative energy you have.",
    "what to release": "Release the learned dimness — the habit of making yourself smaller, less joyful, less obvious than you actually are.",
    "the seed": "Plant the intention of authentic vitality: to pursue this cycle what genuinely lights you up, without modulating it for the comfort of others.",
    "the obstacle": "The obstacle is the shadow of the Sun: the brightness that blinds, the success that becomes performance, the joy that is posed rather than felt.",
    "first steps": "Do one thing purely for the joy of it — not productively, not strategically, not with an audience in mind. Just for the pleasure of the thing itself.",
    "what has grown": "What has grown is visible and undeniable: the thing you worked toward is now in full bloom, warm and bright, for everyone to see.",
    "what is illuminated": "The full moon, doubled with the Sun's energy, illuminates everything — including the ways you have been brighter, more capable, more joyful than you believed.",
    "what hides in the light": "The shadow of the Sun is the inflation: the grandiosity that creeps in when things go well, the forgetting of darkness that makes the next cycle harder.",
    "what must be released": "Release the triumph. Carry the warmth; set down the scoreboard. The Sun does not keep track — it simply shines.",
    "how to let go": "Let go with celebration — the Sun's release is generous and warm, not solemnized but toasted.",
    "what emerges": "What emerges is the self that knows how to return to joy — not as a state dependent on circumstances, but as a practice it can choose.",
  },
  20: { // Judgement
    "mind": "The mind hears a call this week — something beneath the daily noise that has been asking for an answer for longer than you have been willing to admit.",
    "body": "The body resurrects this week: old energy returns, dormant capacity awakens. Let the physical life respond to the call it has been waiting for.",
    "spirit": "The soul faces its own reckoning this week — not condemnation but evaluation, the honest accounting of who you have become and who you are being called to be.",
    "action": "Answer the call. Whatever has been summoning you — toward a vocation, a reckoning, a radical change — let this week be the week you respond.",
    "the gift": "This cycle's gift is awakening — the moment the person you have always been underneath finally rises through the person you thought you had to be.",
    "what to release": "Release the sleep. The Judgement card is the trumpet blast that makes staying unconscious impossible; the dream is over.",
    "the seed": "Plant the intention of radical self-evaluation — to use this cycle to honestly assess what is ready to be resurrected and what needs, at last, to be buried.",
    "the obstacle": "The obstacle is the fear of the verdict — the assumption that honest accounting will condemn rather than liberate.",
    "first steps": "Write the accounting: what you have done, what you have not done, what you are being called to do. Do not spare yourself, and do not condemn yourself.",
    "what has grown": "What has grown is a readiness for reckoning — the soul has been preparing, under the surface, for this moment of honest confrontation with itself.",
    "what is illuminated": "The full moon illuminates the call that has been sounding under the noise of your daily life. You have been hearing it. It is time to respond.",
    "what hides in the light": "The shadow of Judgement is the self-appointed judge: the inner critic who uses the language of awakening to wound rather than to wake.",
    "what must be released": "What must be released is the identity built for survival in a life you are leaving. It saved you; it is now the thing that confines you.",
    "how to let go": "Let go with the decisiveness of someone who has heard the call and answered it: not slowly, not tentatively, but with the full turning of the body toward what is summoning.",
    "what emerges": "What emerges is the version of you that was always underneath: less defended, more purposeful, answering to something larger than survival.",
  },
  21: { // The World
    "mind": "The mind this week rests in the completeness of what has been accomplished. Let it integrate without rushing toward the next project.",
    "body": "The body carries the memory of the entire journey in its cells. This week, honor that — move with the fullness of someone who has arrived somewhere real.",
    "spirit": "The spirit this week touches the mystery of completion: the strange, bittersweet sensation of having become what you set out to become.",
    "action": "Celebrate. Not modestly, not performatively, but genuinely. The World card demands acknowledgment of what is actually complete.",
    "the gift": "This cycle's gift is wholeness — the rare sense of integration, of all the pieces finally finding their places, of being fully present in your own life.",
    "what to release": "Release the restlessness — the habit of moving toward the next thing before fully inhabiting the completion of this one.",
    "the seed": "Plant the intention of integration: to spend this cycle consolidating rather than initiating, weaving what has been learned into who you now are.",
    "the obstacle": "The obstacle is the terror of completion — the way arriving at the World means the familiar journey is over, and the next one has not yet begun.",
    "first steps": "Acknowledge, to yourself and to the people who witnessed your journey, that you have arrived. Let the arrival be real before it becomes the launching pad.",
    "what has grown": "What has grown is everything you set out to grow, plus the things you did not expect — the World is always larger than the vision that summoned it.",
    "what is illuminated": "The full moon illuminates the entire arc: from the Fool's edge to this moment of completion. The distance is real. Let yourself see it.",
    "what hides in the light": "The shadow of the World is the fear of the void after completion — the emptiness that follows the ending of a chapter that gave meaning to the years.",
    "what must be released": "This chapter is complete. Release it in its entirety — not one element, not the parts that did not work, but the whole thing, as a finished work.",
    "how to let go": "Let go with reverence. The World's release is a closing ceremony — name what it was, thank it for what it gave, and close the door with both hands.",
    "what emerges": "What emerges is the beginning of a new great cycle — and the remarkable discovery that you are now the Fool again, but carrying everything you have become.",
  },
  22: { // Ace of Wands
    "mind": "The mind crackles with new possibility this week — follow the spark before it finds a reason not to burn.",
    "body": "The body is lit from within by creative fire this week. Let it move, build, express — the Ace of Wands is kinetic.",
    "spirit": "The spirit receives a new flame this week: inspiration that comes from elsewhere and asks only to be welcomed and fanned.",
    "action": "Begin the thing. The Ace of Wands is the pure start — not the plan, not the preparation, but the first actual gesture of creation.",
    "the gift": "This cycle's gift is the primal creative spark — the originating impulse before it becomes complicated by doubt or practicality.",
    "what to release": "Release the creative project that has been sitting, unchosen, for so long it has become a weight rather than a possibility.",
    "the seed": "Plant the intention of creative initiation: to say yes to one new creative impulse this cycle, before you have figured out where it leads.",
    "the obstacle": "The obstacle is perfectionism that prevents the spark from becoming fire — the demand that the first thing be the complete thing.",
    "first steps": "Pick up the tool — the pen, the brush, the instrument, the code editor — and make one gesture of beginning. That is all the Ace asks.",
    "what has grown": "What has grown from the spark is a genuine flame — small, perhaps, but self-sustaining, requiring now only fuel rather than constant rekindling.",
    "what is illuminated": "The full moon illuminates the creative potential you received but have not yet acted on. The window is still open.",
    "what hides in the light": "The shadow of the Ace of Wands is the serial beginner: the person who forever lights new fires because sustaining one past the spark is too demanding.",
    "what must be released": "Release the creative inhibition. Under the full moon, the Ace of Wands burns away the hesitation.",
    "how to let go": "Let go with a burst of creative expression — make something, anything, as the act of release.",
    "what emerges": "What emerges is a creative life in its most essential form: the living ember of a self that makes things and is not afraid to begin.",
  },
  23: { // Two of Wands
    "mind": "The mind stands at the high window this week, surveying the territory ahead. Let it plan, envision, and choose — but do not let planning replace the departure.",
    "body": "The body is ready for more than the familiar ground allows. This week it needs the physical sensation of standing at a new threshold.",
    "spirit": "The spirit holds the globe of possible futures in its hands this week, aware of both the vastness and the weight of what it is choosing.",
    "action": "Make the decision between the two paths before you. The Two of Wands does not reward indefinite surveying; at some point the ship must sail.",
    "the gift": "This cycle's gift is personal power — the clarity of knowing you have already established enough to launch from, and the boldness to do so.",
    "what to release": "Release the comfortable vantage point. The Two of Wands stands at the parapet not to stay there but to see far enough to choose where to go.",
    "the seed": "Plant the intention of bold vision: to commit this cycle to the larger horizon you have been seeing from a distance but not yet moving toward.",
    "the obstacle": "The obstacle is the seduction of the overview — the part of you that prefers planning to risking, surveys to departures.",
    "first steps": "Name the decision clearly: what are the two wands, the two paths? Write them down. Do not allow them to remain as fog.",
    "what has grown": "What has grown is readiness — the accumulated preparation that has been building toward this moment of departure and now simply needs the word 'go.'",
    "what is illuminated": "The full moon illuminates the horizon you have been scanning: it is closer than it has appeared, and the path more navigable than fear suggested.",
    "what hides in the light": "The shadow here is the visionary who never ships — the person with the world in their hands who finds one more reason to survey before sailing.",
    "what must be released": "Release the planning as a stay against commitment. The planning is done; what remains is the willingness to go.",
    "how to let go": "Let go through the act of departure — the Two of Wands releases the old familiar ground by choosing to leave it.",
    "what emerges": "What emerges from the threshold moment is the person who chose to go — and the world that becomes available to someone who leaves the parapet.",
  },
  24: { // Three of Wands
    "mind": "The mind has already sent the ships; this week it watches the horizon and practices the particular patience of someone who has done their part.",
    "body": "The body has been involved in building and launching; this week it holds the posture of someone who stands tall on solid ground, watching what unfolds.",
    "spirit": "The spirit this week understands the alchemy of investment and release — you have put your best work into the world and now the world has it.",
    "action": "Expand your vision to the next horizon. The Three of Wands sees far; this week, look as far as you can and let that seeing guide your next move.",
    "the gift": "This cycle's gift is proof of concept — the ships on the horizon are evidence that what you launched was real, that your vision had legs.",
    "what to release": "Release the smallness of the local ambition. The Three of Wands sees international waters — let this cycle's scope match the view.",
    "the seed": "Plant the intention of long-range commitment: to invest this cycle in something whose returns will arrive over months or years, not weeks.",
    "the obstacle": "The obstacle is impatience — the difficulty of holding the vision long enough for the ships to return, trusting the launch when the horizon is empty.",
    "first steps": "Map the larger landscape: where do you want to be in a year? What you put in motion this week should be legible from that distance.",
    "what has grown": "What has grown is enterprise — the work has moved beyond the personal and is now operating in the world on its own momentum.",
    "what is illuminated": "The full moon illuminates the ships on the horizon — the results of earlier choices are now visible, approaching or arrived.",
    "what hides in the light": "The shadow of the Three of Wands is overextension — the enterprise launched in too many directions at once, thinning the energy that made the first ships sail.",
    "what must be released": "Release the need to watch the horizon and trust that what was launched will find its way back. Your vigil is not what guides the ships home.",
    "how to let go": "Let go by turning inland — back to the work, the building, the next thing. The ships know where they are going.",
    "what emerges": "What emerges is a life at scale: the person who now operates at the size of their vision, receiving what they sent out into the world.",
  },
  25: { // Four of Wands
    "mind": "The mind this week is invited to rest in what is genuinely stable. Let yourself think from the foundation rather than about it.",
    "body": "The body needs to celebrate this week — literally. Movement, gathering, feasting: the physical act of marking that something good has been accomplished.",
    "spirit": "The spirit returns home this week. Not to the past, but to itself — the particular homecoming of arriving inside your own life.",
    "action": "Celebrate. Mark the threshold. Gather the people. The Four of Wands demands that the arrival be honored, not rushed past in service of the next departure.",
    "the gift": "This cycle's gift is foundation — the Four of Wands offers the stability, community, and belonging that allows everything else to grow.",
    "what to release": "Release the restlessness that resists arrival. Let yourself be home, fully, before the next journey begins.",
    "the seed": "Plant the intention of celebration and consolidation — to use this cycle to strengthen the foundations you have built rather than always building outward.",
    "the obstacle": "The obstacle is the restlessness of the builder who cannot stop building — the inability to inhabit what has already been made.",
    "first steps": "Gather your people. Not for a task, not toward a goal, but for the simple act of being together in the thing that has been built.",
    "what has grown": "What has grown is a home — not necessarily a building but a place of belonging, a community, a structure of relationships that now stands.",
    "what is illuminated": "The full moon illuminates what you have built and who you have built it with — and the astonishing fact that it is more solid than you have allowed yourself to feel.",
    "what hides in the light": "The shadow of the Four of Wands is the fear beneath the celebration: the dread that what has been built can be lost, that stability is always provisional.",
    "what must be released": "Release the celebration as performance. The Four of Wands under the full moon asks for genuine gratitude, not a managed event.",
    "how to let go": "Let go through the act of communal acknowledgment — share the harvest, tell the story, let the community receive what was built for them.",
    "what emerges": "What emerges from the harvest threshold is the next planting — the cycle that begins from a place of genuine fullness rather than hungry want.",
  },
};
