import type { SpreadPositionKey } from "./spreads";

export const CARD_POSITION_DESCRIPTIONS_C_REVERSED: Record<number, Partial<Record<SpreadPositionKey, string>>> = {
  52: { // Three of Swords (reversed)
    "mind": "The swords are still there but loosening — grief is beginning to move, though the mind keeps returning to the wound as if to confirm it is real.",
    "body": "The chest holds the memory of impact even as the blow recedes. The body knows recovery before the mind is willing to name it.",
    "spirit": "The soul is quietly beginning to forgive — not because the hurt was small, but because carrying it indefinitely costs more than the truth did.",
    "action": "Let one shard of the old grief be drawn out rather than pressed deeper. Healing is not avoidance — it is deliberate extraction.",
    "the gift": "The shadow gift here is the knowledge that you can withstand the unbearable. That knowledge is permanent and yours alone.",
    "what to release": "The vigilance against being hurt again — the armor assembled from the old wound that now prevents the new life from reaching you.",
    "the seed": "Plant the intention to grieve fully so that the forgiveness that follows is real rather than performed.",
    "the obstacle": "The loop of rehearsed pain, returning to the story of the wound not to heal it but to remain inside it.",
    "first steps": "Name the thing that hurt without narrating who was wrong. Let the pain exist without a verdict attached.",
    "what has grown": "A delayed tenderness — the softening that follows grief when it is given enough time and enough honest acknowledgment.",
    "what is illuminated": "How much energy has been poured into keeping the wound at exactly the same temperature. The full moon shows the maintenance cost.",
    "what hides in the light": "The grief you have not allowed yourself to feel because feeling it would mean admitting how much you cared.",
    "what must be released": "The need for an apology that may never come. Waiting for it is a second wound you are inflicting on yourself.",
    "how to let go": "Mourn the loss without requiring it to be someone's fault. Some grief is simply the price of having loved something real.",
    "what emerges": "The first moment of genuine lightness after sorrow — brief, tentative, and entirely honest.",
  },
  53: { // Four of Swords (reversed)
    "mind": "The mind is refusing the rest it desperately needs — circling back into action before the restoration is complete, mistaking motion for recovery.",
    "body": "The body has been returned to duty before it was ready. Something essential is running on fumes and calling it strength.",
    "spirit": "The spirit is being denied the stillness in which it integrates what has happened. Forced wakefulness is not presence — it is avoidance.",
    "action": "Stop. Even briefly, even imperfectly. The refusal to rest is not noble — it is the obstacle wearing discipline's clothing.",
    "the gift": "The shadow gift is the recognition of how deeply the fear of stopping runs, and what it says about what you are afraid to feel.",
    "what to release": "The belief that if you stop moving, something will catch you. The stillness is not the danger. The running is.",
    "the seed": "Plant the intention to honor your limits before they enforce themselves on you. Rest chosen is rest that restores.",
    "the obstacle": "The identity built around being someone who does not need to stop. The Four of Swords reversed shows that identity fraying.",
    "first steps": "Take one period of genuine stillness today — not sleep, not distraction, but quiet. Hold it for longer than feels comfortable.",
    "what has grown": "Burnout dressed as dedication. What has accumulated is not strength — it is unpaid debt to the self.",
    "what is illuminated": "The toll the relentless forward motion has taken, finally visible when even the body begins to refuse.",
    "what hides in the light": "The fear of what will surface if you are truly still. The restlessness is protective. That is why it is so hard to lay down.",
    "what must be released": "The guilt that arrives when you are not producing. Your worth is not the output.",
    "how to let go": "Give yourself permission — in writing if necessary — to stop for a measured period without it meaning failure.",
    "what emerges": "The first real breath after a long time of shallow ones. The silence after the insistence.",
  },
  54: { // Five of Swords (reversed)
    "mind": "The mind is beginning to count the cost of a victory won badly — turning the moment over, finding the hollow place where the triumph should have been.",
    "body": "The body carries guilt differently than it carries grief. Notice where you are bracing, clenching, unable to fully settle in the aftermath.",
    "spirit": "The spirit is asking the uncomfortable question: was this worth it? Let the question sit. It does not require a defense.",
    "action": "Acknowledge the harm that was done in winning — not to collapse into self-punishment, but because honesty is the only path through.",
    "the gift": "The shadow gift is a more accurate map of your own capacity for ruthlessness. That self-knowledge, honestly held, prevents the next time.",
    "what to release": "The justification. The story of why what was done was necessary. The Five of Swords reversed does not want the defense.",
    "the seed": "Plant the intention to compete from a place you could stand in afterward — not to lose, but to win in a way that costs you nothing you want to keep.",
    "the obstacle": "The part of you that is still sure you were right. It is not wrong, exactly — but it is getting in the way of the repair.",
    "first steps": "Reach out to the person left holding swords they didn't come in with. You don't have to grovel — just open the door.",
    "what has grown": "The uncomfortable awareness that not every victory is worth the field it leaves behind. That is not weakness. It is maturity.",
    "what is illuminated": "The specific thing you compromised to win — the value bent, the relationship strained, the integrity slightly dimmed.",
    "what hides in the light": "The relief underneath the guilt. Part of you is glad for the outcome, and the admission of that complicates everything.",
    "what must be released": "The posture of the wounded victor — holding both the win and the grievance, refusing to put either down.",
    "how to let go": "Return one sword. One gesture of repair, however small, that acknowledges the cost of the conflict.",
    "what emerges": "The possibility of reconnection where the conflict created distance — tentative, honest, built on something truer than the fight.",
  },
  55: { // Six of Swords (reversed)
    "mind": "The mind knows the direction has changed but cannot stop looking back. The boat is pointed toward calmer water and the eyes remain fixed on the shore that hurt you.",
    "body": "The body is stuck in a doorway — one foot in the difficult past, one foot refusing to commit to the crossing. The indecision is its own exhaustion.",
    "spirit": "The spirit is being called toward quieter water and is resisting, not because it doesn't want peace, but because it doesn't trust that peace is real.",
    "action": "Complete the departure that has been postponed. The turbulence ahead is less than the turbulence of remaining in-between.",
    "the gift": "The shadow gift is the recognition of how attached you are to the struggle. Something in you has built its identity around the difficulty.",
    "what to release": "The return ticket. As long as you are holding the way back as an option, the crossing cannot become a commitment.",
    "the seed": "Plant the intention to leave not just physically but completely — to take the mind and spirit into the new place as well as the body.",
    "the obstacle": "Nostalgia for the familiar difficulty. The storm was terrible and it was known. The calm is unfamiliar and therefore threatening.",
    "first steps": "Stop making the trip back in your mind. When the thought returns, notice it without following it to shore.",
    "what has grown": "A long and costly delay — the time spent returning to a difficulty that had already been partially left has its own grief to be acknowledged.",
    "what is illuminated": "What keeps pulling you back to the water that was already crossed. The full moon names the attachment precisely.",
    "what hides in the light": "The readiness. Underneath the hesitation and the backward glancing, you are more prepared for the crossing than you will admit.",
    "what must be released": "The version of the situation you keep returning to revise — hoping this time the story comes out differently.",
    "how to let go": "Push off from the shore. Not when you're ready. Now, with the discomfort still present.",
    "what emerges": "The calm that was waiting on the other side of the departure you kept postponing. It was always there.",
  },
  56: { // Seven of Swords (reversed)
    "mind": "The strategy that seemed elegant is unraveling. The mind is confronting the gap between what it told itself was clever and what it actually cost.",
    "body": "The body has been performing a version of yourself that doesn't quite fit. Notice the tension of sustained self-presentation in the chest and the jaw.",
    "spirit": "The spirit does not thrive in half-truths. Whatever partial version you have been offering to the world, it is beginning to feel smaller than you are.",
    "action": "Return what you have been carrying that wasn't yours to take. The gesture is uncomfortable and it is the only real way through.",
    "the gift": "The shadow gift is the relief available on the other side of exposure — being known more fully, even in the compromised thing, is less lonely than the secrecy.",
    "what to release": "The plan that depended on no one looking too closely. It has had its moment. Let it be done.",
    "the seed": "Plant the intention to be seen accurately — to stop curating what is known about you and allow something truer to surface.",
    "the obstacle": "The fear that full honesty will cost you more than the strategy already has. Do the math again. The strategy is not free.",
    "first steps": "Tell one person one true thing you have been managing their knowledge of. Notice what happens.",
    "what has grown": "The cumulative weight of maintained deception — not necessarily malicious, but exhausting, and now pressing to be set down.",
    "what is illuminated": "The specific thing that was being concealed and the specific reason — the full moon makes the shape visible without cruelty.",
    "what hides in the light": "The longing to be simply known — without the performance, without the angles, just seen.",
    "what must be released": "The version of events you have been maintaining that serves you at the cost of accuracy.",
    "how to let go": "Disclose. Not everything at once — the one true thing that has been most carefully kept. Begin there.",
    "what emerges": "The unexpected solidity of being known honestly. The blade laid down still cuts — but the laying down is its own kind of relief.",
  },
  57: { // Eight of Swords (reversed)
    "mind": "The stories that built the prison are beginning to lose their hold. The mind is discovering the gap between what it assumed was fixed and what is actually movable.",
    "body": "The body is starting to remember that it can move in directions the mind had declared impossible. Sensation is returning to places that had gone numb.",
    "spirit": "The soul has always known the way out. The spirit is gently, persistently pointing at the same gap in the swords it has been pointing at all along.",
    "action": "Take the step the mind insists will fail. Do it anyway, slowly, and see what the ground actually does under your foot.",
    "the gift": "The shadow gift is the specific shape of your own mental architecture — knowing exactly how you imprison yourself is the most useful map you have.",
    "what to release": "The secondary comfort of constraint — the identity that has formed around limitation, the relationships that depend on your staying small.",
    "the seed": "Plant the intention to act from the belief that one thing is possible, even while all the others remain uncertain.",
    "the obstacle": "The voice that sounds like wisdom and is actually fear. It is very good at wearing the costume of reason.",
    "first steps": "Name the belief out loud — the specific sentence the mind has been running that makes the exit invisible. Say it, then question it.",
    "what has grown": "A more precise understanding of the mind's capacity for self-defeat — not as condemnation, but as genuine intelligence about the mechanism.",
    "what is illuminated": "The architecture of the self-built cage — which walls are real, which are thought, and which are habit masquerading as necessity.",
    "what hides in the light": "How much you have been protecting yourself from your own freedom. The prison was also a shelter.",
    "what must be released": "The helplessness you have been rehearsing. However real it once was, it has become a performance.",
    "how to let go": "Remove the blindfold first. Clarity before movement. See what is actually there before deciding it cannot be crossed.",
    "what emerges": "Agency — arriving quietly, in small doses, proving itself through action before it believes itself through thought.",
  },
  58: { // Nine of Swords (reversed)
    "mind": "The catastrophic thinking is beginning to lose its authority. The mind is tentatively discovering that the predicted disaster has not yet arrived and possibly will not.",
    "body": "Sleep is returning, breath is deepening. The body is the first to know when the anxiety is lifting — trust this signal before the mind confirms it.",
    "spirit": "The spirit has been waiting patiently beneath the noise of the spiral. As the volume decreases, something steadier begins to be audible again.",
    "action": "Do one normal thing without rehearsing the disaster first. Let the action be evidence against the catastrophe.",
    "the gift": "The shadow gift is the knowledge of exactly what you fear most — and the discovery that naming it clearly makes it smaller than the un-named dread.",
    "what to release": "The inner critic that has been granted the authority of prophecy. It is not a prophet. It is a frightened part of you with a microphone.",
    "the seed": "Plant the intention to distinguish between genuine risk and imagined catastrophe — and to respond only to the first.",
    "the obstacle": "The habit of the spiral. Even as the anxiety loosens, the mind may reach for it out of familiarity. Notice the reach.",
    "first steps": "Write the specific fear down and then write the most probable actual outcome. The gap between them is the Nine of Swords reversed showing its work.",
    "what has grown": "Exhaustion from sustained anticipatory suffering — and, underneath the exhaustion, the first quiet recognition that you may have been wrong about how bad it would be.",
    "what is illuminated": "How much of the suffering was performed in the mind rather than lived in reality. This is not dismissal — it is diagnosis.",
    "what hides in the light": "The function the anxiety serves — what it protects, what it excuses, what identity it quietly sustains.",
    "what must be released": "The catastrophic narrative your nervous system has been running past the point of usefulness. It served a moment. The moment has passed.",
    "how to let go": "Sleep. The body already knows more than the mind about when the danger has passed. Let the body lead this time.",
    "what emerges": "The slow return of proportion — the world at its actual size, problems at their actual weight, the self capable of more than the spiral allowed.",
  },
  59: { // Ten of Swords (reversed)
    "mind": "The mind is pulling itself upright after the nadir — tentative, still tender, but no longer face-down in the ground.",
    "body": "The body is in early recovery: fragile, hyperaware, flinching at what sounds like the return of the blow. Give it time and gentleness and no unnecessary weight.",
    "spirit": "The spirit has survived the worst and is quietly verifying that it is still intact. It is. The soul checks its own contents after devastation.",
    "action": "Walk out of the field. Not running — walking, slowly, carrying only what you actually need for the next day.",
    "the gift": "The shadow gift is the undeniable evidence of survival. The Ten of Swords reversed says: you went all the way to the bottom and you are still here.",
    "what to release": "The shadow of the nadir — the voice that insists the bottom was the true shape of things rather than the lowest point of a cycle.",
    "the seed": "Plant the intention to rise at your own pace, without performing recovery for anyone who needs you to be fine.",
    "the obstacle": "The lingering shock of having gone all the way down. The body and mind do not recover on schedule — they recover when they recover.",
    "first steps": "Name one thing that is still intact — one resource, one relationship, one capacity that the devastation did not reach.",
    "what has grown": "The irreversible knowledge of what you can survive. That knowledge does not make things easier — it makes them possible.",
    "what is illuminated": "The size of the thing that has just passed — not minimized, not dramatized, but seen in its actual proportions under full light.",
    "what hides in the light": "The beginning. It is already forming in the corner of the frame, too small to see yet, but present. It is always present in this card.",
    "what must be released": "The lingering posture of bracing — the body still waiting for the blow that has already landed.",
    "how to let go": "Remove one sword. Not all ten. The recovery does not have to be total to begin. Pull out one sword and let that be enough for today.",
    "what emerges": "The first step away from the place where you fell — small, real, and oriented toward something other than the wound.",
  },
  60: { // Page of Swords (reversed)
    "mind": "The sharp mind is running without the wisdom to direct it — gathering information as a form of power rather than understanding, mistaking speed for clarity.",
    "body": "Nervous energy without direction is eroding the body from inside. The Page's quicksilver alertness has curdled into anxiety wearing curiosity's face.",
    "spirit": "The spirit is being outrun by the mind. Wit and watchfulness have their place; without depth they become weapons turned inward.",
    "action": "Slow the intake. Before seeking more information, sit with what is already known and let it deepen.",
    "the gift": "The shadow gift is the recognition of how intelligence can be weaponized — against others, against yourself — and the beginning of choosing otherwise.",
    "what to release": "The sharp comment that felt satisfying in the moment and cost more than it was worth. The tongue that moves faster than the consideration behind it.",
    "the seed": "Plant the intention to use the keen perception for something constructive — to build rather than dismantle with the same sharp tool.",
    "the obstacle": "Scattered thinking that cannot settle long enough to become real understanding. Information without synthesis is noise with a clever accent.",
    "first steps": "Stay with one question until it yields something, rather than moving immediately to the next one. Let depth be the practice.",
    "what has grown": "A habit of skimming the surface of everything — quick, informed, never quite landed.",
    "what is illuminated": "The anxiety that the curiosity has been outrunning. The Page reversed is watching because something feels unsafe — and has been telling itself that is just how minds work.",
    "what hides in the light": "The longing for real understanding beneath the parade of clever observations. Wit is the armor. Depth is what it guards.",
    "what must be released": "The gossip, the half-formed accusation, the sharp observation shared before it was tested against generosity.",
    "how to let go": "Withhold one cutting remark. Feel the discomfort of not deploying the blade. That discomfort is information.",
    "what emerges": "Genuine curiosity — the kind that listens as much as it questions, that seeks to understand rather than to possess the knowing.",
  },
  61: { // Knight of Swords (reversed)
    "mind": "The charge has outrun the thinking. The mind is somewhere three moves ahead while the body is still processing the damage from the last two.",
    "body": "The body is showing the cost of relentless velocity — tension, inflammation, the particular exhaustion of a system kept at combat readiness too long.",
    "spirit": "The spirit is not served by winning every argument. The Knight reversed asks: what is the ferocity actually in service of, and is that still true?",
    "action": "Stop before you say the next thing. Not forever — for one breath. Then decide if the charge is still required.",
    "the gift": "The shadow gift is the recognition that aggression and conviction are not the same thing. One burns the bridge. The other crosses it.",
    "what to release": "The verbal assault that closed a door you did not actually want closed. The Knight reversed leaves wreckage and calls it directness.",
    "the seed": "Plant the intention to direct the ferocity at problems rather than people — the same charge, aimed with more precision.",
    "the obstacle": "Impulsiveness wearing the mask of passion. Speed is not the same as rightness, and certainty is not the same as accuracy.",
    "first steps": "Apologize for the most recent collision that the Knight caused moving too fast. Not as self-punishment — as repair.",
    "what has grown": "A trail of severed connections and unfinished conflicts, each one created by the conviction that the charge mattered more than the aftermath.",
    "what is illuminated": "The specific relationship or opportunity that the unchecked speed has begun to damage. The full moon shows the collision in progress.",
    "what hides in the light": "The fear that if the Knight slows down, the cause will be lost. That fear is driving the charge more than the cause is.",
    "what must be released": "The argument you have been having at full volume with someone who no longer has the capacity or willingness to meet you there.",
    "how to let go": "Sheathe the sword before it is drawn. The Knight reversed is learning that not every provocation requires a response.",
    "what emerges": "Precision — the same ferocity, disciplined. A blade that cuts where it means to rather than everywhere it can reach.",
  },
  62: { // Queen of Swords (reversed)
    "mind": "The mind that was sharpened by experience has turned its edge on the people closest to it. Clarity has become cruelty without the intent to be cruel.",
    "body": "Bitterness is held in the body like a cold that will not resolve — a contracted quality in the chest, the breath not quite full.",
    "spirit": "The spirit is being shaped by old wounds rather than informed by them. The Queen reversed has let the hurt speak instead of speak through her.",
    "action": "Soften one thing. Not the truth — the delivery. The sharpness is not required by the clarity; it is required by the unprocessed wound.",
    "the gift": "The shadow gift is the precise location of the grief that has been converted into judgment. Following the blade back to its source is the gift.",
    "what to release": "The assessment that was accurate and delivered without mercy. Accuracy without compassion is a weapon, not a gift.",
    "the seed": "Plant the intention to speak the same truth but with the care that makes it receivable — not for their sake only, but for yours.",
    "the obstacle": "The wound that has been allowed to become a lens. Not everything you see through it is distorted — but more is than you are currently willing to examine.",
    "first steps": "Notice the next moment the tongue sharpens past what the situation requires. Pause. Ask: whose pain is speaking?",
    "what has grown": "Isolation — the particular loneliness of someone whose intelligence is feared rather than trusted, whose clarity keeps the room at a distance.",
    "what is illuminated": "The specific hurt that has been running the sharpness. The full moon shows the wound behind the blade, not just the blade.",
    "what hides in the light": "The grief the Queen has refused to mourn because mourning it would require laying down the anger that replaced it.",
    "what must be released": "The verdict on someone that has hardened past what the evidence actually supports. Judgment calcified into condemnation.",
    "how to let go": "Cry instead of cut. Just once. Let the sorrow take the shape the anger has been taking.",
    "what emerges": "The Queen upright — clarity that has been returned to compassion, truth that can be heard because it is offered rather than wielded.",
  },
  63: { // King of Swords (reversed)
    "mind": "The mind that governs others is now governing in its own interest. The King reversed uses clarity as justification rather than as service.",
    "body": "The rigidity that commands respect in the throne room is becoming restriction in the body. Authority held without release is a kind of calcification.",
    "spirit": "The spirit is watching the intelligence it was given being used to construct elaborate defenses of what was already decided. Wisdom does not work that way.",
    "action": "Examine the principle you are invoking. Is this actually principle — or is it preference dressed in principle's authority?",
    "the gift": "The shadow gift is the recognition of how power distorts perception — how having the final word can quietly corrupt the listening that should precede it.",
    "what to release": "The intellectual arrogance that mistakes confidence for correctness. The King reversed has stopped questioning himself and is starting to become his own blind spot.",
    "the seed": "Plant the intention to use the formidable mind in service of a truth larger than the one you currently hold. Humility is not weakness in a King — it is precision.",
    "the obstacle": "The certainty that has curdled into dogma. Every position the King holds is defensible; the problem is that none of them are currently open to revision.",
    "first steps": "Ask the question you already know the answer to, and genuinely listen for a different answer. Let someone else's logic reach you.",
    "what has grown": "An edifice of correct-sounding reasoning that has been built, stone by stone, to justify what the King wanted before the thinking began.",
    "what is illuminated": "The gap between the stated principle and the actual motivation. The full moon is not interested in the official version.",
    "what hides in the light": "The ethical compromise that has been rationalized so thoroughly it now sounds like integrity.",
    "what must be released": "The position being held for the sake of winning the argument rather than arriving at the truth.",
    "how to let go": "Concede a point. Not the whole argument — one point, to someone whose intelligence you have been discounting.",
    "what emerges": "Authority that has been returned to its proper function: service, clarity, and the genuine willingness to be wrong.",
  },
  64: { // Ace of Pentacles (reversed)
    "mind": "The pragmatic mind keeps returning to an opportunity that looks right but something is misaligned. The hesitation is not cowardice — it is information worth examining.",
    "body": "The body has not yet found solid ground. The new beginning the Ace offers is present but the footing is uncertain, the foundation still shifting.",
    "spirit": "The spirit recognizes the seed but senses the conditions are not yet right for planting. Forcing the moment does not accelerate the growth.",
    "action": "Examine the terms more carefully before committing. What appears to be an open door may lead somewhere other than promised.",
    "the gift": "The shadow gift is the opportunity to understand what actually constitutes a real beginning for you — what conditions are necessary, not optional.",
    "what to release": "The magical thinking that says the right opportunity will arrive pre-assembled with no risk. Seeds require actual soil.",
    "the seed": "Plant the intention to prepare the ground before you place the seed — to make the conditions genuinely ready rather than compelling them.",
    "the obstacle": "The gap between the vision of the material beginning and the unglamorous work that precedes it. The Ace reversed asks for that work first.",
    "first steps": "Audit the material foundation honestly. What is actually in place, what is assumed to be in place, and what needs to be built before the next step?",
    "what has grown": "A series of beginnings that did not take root because the ground was not ready when they were planted.",
    "what is illuminated": "The specific reason this seed is struggling — soil too depleted, timing off, the gift genuine but arriving in compromised form.",
    "what hides in the light": "The abundance already present that is being overlooked in the search for the new opportunity.",
    "what must be released": "The deal, partnership, or material commitment that looked like gold and is not quite what it presented itself as.",
    "how to let go": "Return to basics. What actually sustains you right now, independent of the promise? Start there.",
    "what emerges": "A more discerning eye for genuine material opportunity — slower to commit, less dazzled, and therefore more capable of actually receiving the real thing.",
  },
  65: { // Two of Pentacles (reversed)
    "mind": "The juggling act has broken down and the mind is too depleted to diagnose which ball caused the collapse. The answer is: too many balls.",
    "body": "The body has been carrying the disorganization that the mind refused to acknowledge. The strain is real — something has to be set down before something is dropped.",
    "spirit": "The spirit cannot find its ground in the chaos of competing demands. The sacred requires some portion of stillness to be heard.",
    "action": "Stop trying to manage everything at once. Choose the one thing that most requires your full presence and give it that.",
    "the gift": "The shadow gift is the limit — the threshold that cannot be ignored, finally demanding that a genuine decision be made about priorities.",
    "what to release": "The lie that says this level of juggling is sustainable. The Two of Pentacles reversed says it has already stopped being sustainable.",
    "the seed": "Plant the intention to do less and do it fully — not with guilt about what was set down, but with genuine commitment to what was chosen.",
    "the obstacle": "The inability to say no, or the refusal to, which amounts to the same collapse: the accumulated yes has exceeded what can be held.",
    "first steps": "Write every current commitment down. Look at the list as a whole. Cross one thing off — not renegotiate, not pause — release.",
    "what has grown": "Financial disorganization or logistical chaos that has been growing quietly in the margins while the main performance occupied center stage.",
    "what is illuminated": "The full weight of what is in the air — all the spinning, all the management, all the energy the balancing act requires.",
    "what hides in the light": "The need for help that has been invisible because asking for it felt like admitting the juggling was failing.",
    "what must be released": "The performance of having it together when the center is not holding. The facade requires more energy than the honest admission.",
    "how to let go": "Catch one thing before it hits the ground and set it down deliberately. Make the choice before the crisis makes it for you.",
    "what emerges": "A more honest economy of attention — fewer commitments, each one actually served.",
  },
  66: { // Three of Pentacles (reversed)
    "mind": "The mind is operating in isolation when the task requires collaboration — working around people rather than with them, mistaking solo efficiency for quality.",
    "body": "The physical experience of working alone when the work needs partnership is a particular heaviness. The body knows it is carrying what should be shared.",
    "spirit": "The spirit is being denied the particular energy that only genuine collaboration produces — the alchemy that no solitary effort can replicate.",
    "action": "Bring the work into the room. Show the unfinished thing to the people who could help it become what it is trying to be.",
    "the gift": "The shadow gift is the recognition of what has gone unacknowledged — skill that has been brought but not named, contribution that has been swallowed into the collective.",
    "what to release": "The self-sufficiency that has become isolation. There is a difference between capable independence and the inability to collaborate.",
    "the seed": "Plant the intention to communicate about the work more transparently — what you need, what is not working, where the misalignment lives.",
    "the obstacle": "The misalignment that everyone can feel and no one has named. The Three of Pentacles reversed is a team meeting that is not happening.",
    "first steps": "Say the thing the project needs out loud — even if it reveals a gap, a limitation, a need that feels uncomfortable to name.",
    "what has grown": "A body of work that is solid in isolation and has not yet been tested by the friction that would make it excellent.",
    "what is illuminated": "The specific gap — in communication, in collaboration, in the acknowledgment of each party's contribution — that has been quietly undermining the project.",
    "what hides in the light": "The ego friction that makes true collaboration difficult. Someone is protecting territory. It may be you.",
    "what must be released": "The need to control how the work turns out at the cost of what it could become with genuine partnership.",
    "how to let go": "Trust one other person with the part of the work you have been holding most tightly. Let their hands on it change it.",
    "what emerges": "A project that has been returned to its proper shape — built by more than one person, stronger for the friction, better than any solo effort could produce.",
  },
  67: { // Four of Pentacles (reversed)
    "mind": "The grip is loosening — but it loosened under pressure rather than through wisdom. The mind is catching up to what the hand has already lost.",
    "body": "The held-tight places in the body are beginning to release — sometimes through choice, sometimes through circumstances demanding a surrender the hands were not willing to make.",
    "spirit": "The spirit is discovering, in the forced opening, that what was released did not destroy the self. The fear was larger than the fact.",
    "action": "Practice the open hand while there is still something in it. Releasing before it is taken is the only release that is also a choice.",
    "the gift": "The shadow gift is the experience of having held too tightly and the resulting knowledge of exactly what kind of scarcity the grip was trying to prevent.",
    "what to release": "The security that has become a cage — the resource hoarded past the point of usefulness, the position held past the point of meaning.",
    "the seed": "Plant the intention to hold what you have with an open enough hand that it can grow rather than only be preserved.",
    "the obstacle": "Greed that has stopped recognizing itself as greed and now presents as prudence. The Four of Pentacles reversed does not honor the distinction.",
    "first steps": "Give away one thing — money, time, credit, resources — that the grip has been keeping. Notice that you are still standing.",
    "what has grown": "A fortified position that is also a prison. Safety has been achieved and joy has been excluded in the same gesture.",
    "what is illuminated": "The cost of the hoarding — not just to others but to the self. What has been blocked from flowing in by the same grip that blocked the outflow.",
    "what hides in the light": "The generosity that is possible once the scarcity the grip was defending against is honestly examined and found to be smaller than feared.",
    "what must be released": "Something you have held so long the holding has become identity. You are not your resources. Releasing them does not reduce you.",
    "how to let go": "Give without calculating the return. Once, fully, without the accounting. See what it costs you. Then look again.",
    "what emerges": "Flow. The abundance that was blocked by the grip begins to move when the hand opens. This is what the Four of Pentacles always knew and was afraid to test.",
  },
  68: { // Five of Pentacles (reversed)
    "mind": "The scarcity mindset is persisting after the worst has passed — the mind is still in winter though the warmth has arrived, still refusing to believe the door is open.",
    "body": "The body is beginning to recover but the nervous system is still braced for hardship. Safety is present; the recognition of safety is still incoming.",
    "spirit": "The spirit is learning to accept that the suffering can end — that it is not being disloyal to the hard time by allowing better to arrive.",
    "action": "Accept the help. Not as weakness, not with elaborate repayment plans — just receive what is being offered with genuine gratitude.",
    "the gift": "The shadow gift is the full knowledge of what it is to be without, and the resulting depth of appreciation when the without has passed.",
    "what to release": "The poverty mindset that has outlived the poverty. The hardship was real; the story that it is permanent is not.",
    "the seed": "Plant the intention to let abundance in — to stop flinching at the offer, to believe that ease is not followed necessarily by a corresponding loss.",
    "the obstacle": "The habit of scarcity — the way it has organized the entire approach to life and continues to do so even when circumstances no longer require it.",
    "first steps": "Name one area where support is available and you have been declining it. Accept that support this week.",
    "what has grown": "Resilience, yes — and also a dangerous comfort in lack. The difficulty became familiar and familiar became necessary.",
    "what is illuminated": "How long the scarcity story has been running past the circumstances that created it. The wound and the weather have both changed.",
    "what hides in the light": "The relief that is available — genuine, bodily relief — on the other side of accepting help. It has been right there.",
    "what must be released": "The identity of the person who has nothing, who needs no one, who endures rather than receives. It served a time. That time has passed.",
    "how to let go": "Walk through the door. The church has never been locked. The light through the window was always for you.",
    "what emerges": "Warmth — entering the body slowly, the way warmth always enters after real cold: tentative at first, then undeniable.",
  },
  69: { // Six of Pentacles (reversed)
    "mind": "The mind is entangled in a giving or receiving relationship that is not as equal as it presents itself. The generosity has strings. The dependence has a cost.",
    "body": "The body knows the difference between genuine nourishment and giving that depletes — or receiving that diminishes. Track the actual energy of the exchange.",
    "spirit": "The spirit is alert to the power asymmetry in the generosity. Something given with strings is a form of control wearing charity's face.",
    "action": "Name the imbalance — to yourself, then possibly to the person involved. The exchange can only be corrected once it is honestly described.",
    "the gift": "The shadow gift is the clarifying recognition of what genuine reciprocity looks like — and how often what passes for generosity is actually investment.",
    "what to release": "Charity that requires the recipient to remain needy in order for the giver to continue feeling generous. Both parties are diminished by it.",
    "the seed": "Plant the intention to give freely or not at all — to examine what the giving is for and whether it actually serves the person being given to.",
    "the obstacle": "The power dynamic disguised as generosity. Someone is holding the scales and they are not balanced. The obstacle is the pretense that they are.",
    "first steps": "Audit one relationship for genuine mutuality. Ask: if this exchange were made fully transparent, would both parties recognize it as fair?",
    "what has grown": "A dependency structure that serves neither party as well as it appears to — the giver bound to their role, the receiver to theirs.",
    "what is illuminated": "The real economy of the exchange — what is being given, what is being extracted, and who benefits from the arrangement's continuation.",
    "what hides in the light": "The need for control that philanthropy can fulfill. The hand that holds the scales controls the result.",
    "what must be released": "The giving that comes from guilt, or the receiving that comes from a refusal to build equal standing.",
    "how to let go": "Step off the scale. Stop positioning yourself as either the one who has or the one who lacks, and seek the level ground between.",
    "what emerges": "A more honest exchange — less flattering, more mutual, sustainable in a way that the performance of generosity never was.",
  },
  70: { // Seven of Pentacles (reversed)
    "mind": "Impatience is masquerading as assessment — the mind is pulling up the plant to see if the roots are growing rather than trusting the process it signed on for.",
    "body": "The body is exhausted by effort that has not produced visible return. This is different from wasted effort. The vine is still growing; the body doesn't know that yet.",
    "spirit": "The spirit is being tested by the gap between investment and return. What feels like abandonment by the harvest is actually the middle of the cycle.",
    "action": "Stop measuring and keep tending. The harvest does not respond to urgency. The vine grows on its own schedule.",
    "the gift": "The shadow gift is the recognition of what you are actually willing to wait for — what effort you will sustain without immediate reward, and what that says about your values.",
    "what to release": "The expectation that results arrive on the schedule that was originally imagined. Real things grow at the pace of real things.",
    "the seed": "Plant the intention to distinguish between work that is genuinely producing and work that is procrastination wearing the costume of patience.",
    "the obstacle": "Procrastination disguised as patience — the stillness that is not trust but avoidance, the waiting that is not faith but fear.",
    "first steps": "Return to the work with fresh eyes. Ask honestly: is this stalled because it needs more time, or because it needs different action?",
    "what has grown": "Frustration with the pace — and, underneath the frustration, the quiet suspicion that the investment was wrong. Examine that suspicion before abandoning the field.",
    "what is illuminated": "The real state of the work — not what you hoped it would be by now, but what it actually is. The full moon does not improve on the truth.",
    "what hides in the light": "The relief that would come from abandoning this particular vine and starting something new. The Seven reversed knows this temptation intimately.",
    "what must be released": "Either the premature harvest impulse or the crop that genuinely is not growing. The full moon helps you tell them apart.",
    "how to let go": "Make a decision. Either recommit fully and stop measuring, or release this investment with honesty and without drama.",
    "what emerges": "Clarity about what is worth the long wait and what has already had its moment without bearing the fruit that was hoped for.",
  },
  71: { // Eight of Pentacles (reversed)
    "mind": "The mind is circling the work without entering it — polishing the same section past the point of improvement, calling it refinement when it is avoidance.",
    "body": "The hands are moving but the presence is not fully in them. Habitual labor without intention is a form of sleep.",
    "spirit": "The spirit is not fed by work done from obligation alone. What was once a craft has become a compulsion. The love needs to be found again or the work needs to change.",
    "action": "Finish one thing. Not perfectly — done. Completion is the practice the Eight of Pentacles reversed is refusing.",
    "the gift": "The shadow gift is the recognition of the perfectionism as a specific form of fear — the terror of the finished thing being judged and found wanting.",
    "what to release": "The refinement that has become self-protection. Every additional revision is a reason not to be seen.",
    "the seed": "Plant the intention to complete rather than perfect — to value the finished thing more than the ongoing process of improvement that delays it.",
    "the obstacle": "The perfectionism that has made completion impossible. The Eight of Pentacles reversed builds the wall one more brick every time the exit is near.",
    "first steps": "Set a completion date. Not an ideal date — a real one, with the work in whatever state it has reached. The deadline is the practice.",
    "what has grown": "A body of unfinished work that collectively represents significant effort applied toward nothing that can be used, shared, or built upon.",
    "what is illuminated": "The specific thing the perfectionism is protecting — the dream of the work, held intact inside the refusal to ever test it against reality.",
    "what hides in the light": "The boredom underneath the compulsion. The work has been done for its own sake past the point of genuine engagement.",
    "what must be released": "The work that has been held in the workshop too long. It belongs in the world now, however imperfect.",
    "how to let go": "Ship the imperfect thing. Not to abandon standards — to discover that the real standard is completion, and that what leaves the workshop is always different from what you imagined.",
    "what emerges": "The practice of done — the discipline of the completed rather than the ideal, and the unexpected freedom that completion delivers.",
  },
  72: { // Nine of Pentacles (reversed)
    "mind": "The mind is cataloguing the abundance and finding it insufficient — comparing what is present to what was promised, and the comparison is becoming a form of poverty.",
    "body": "The sensory pleasures available in the present moment are being held at arm's length. The garden is beautiful and the body is not walking in it.",
    "spirit": "The spirit knows the difference between earned independence and isolated sufficiency. The Nine reversed has confused them.",
    "action": "Enjoy what you have without prefacing it with a plan for what comes next. The savoring is not a distraction from the work — it is the point.",
    "the gift": "The shadow gift is the discovery of what external validation has been substituting for. The Nine reversed shows where the foundation is rented rather than owned.",
    "what to release": "The need for others to confirm the value of what has been built before it can be fully inhabited.",
    "the seed": "Plant the intention to build on foundations that are genuinely solid — to repair what the surface presentation has been covering.",
    "the obstacle": "The gap between the image of sufficiency and the reality — the surface abundance that conceals a financial or emotional foundation that is less secure than it appears.",
    "first steps": "Look honestly at the foundations, not the displays. Audit one area — financial, relational, practical — with full honesty and no performance.",
    "what has grown": "An image of abundance that has required significant maintenance energy — the appearance of the Nine without the full substance of it.",
    "what is illuminated": "What the gloss has been covering. The full moon is not impressed by presentation. It shows what is actually there.",
    "what hides in the light": "The loneliness that the solitary sufficiency has been producing. The Nine of Pentacles reversed has the garden but has lost the bird.",
    "what must be released": "The performance of having arrived — the posture of sufficiency that has been protecting a foundation that needs attention.",
    "how to let go": "Stop performing the abundance and start actually inhabiting it. Less display, more genuine presence in what is already here.",
    "what emerges": "Either real sufficiency — the foundations repaired, the gap between image and substance closed — or the honest beginning of building toward it.",
  },
  73: { // Ten of Pentacles (reversed)
    "mind": "The mind is weighing a legacy that has cracks in its foundations — the inheritance of wealth or pattern alongside the inheritance of something unresolved.",
    "body": "The body carries the family system in its posture, its nervous system, its way of being in material reality. What was inherited that was never examined?",
    "spirit": "The spirit is asking whether the security being built is real or only the appearance of it — whether the ten pentacles are genuinely in the frame or arranged for the picture.",
    "action": "Address the family or financial dispute that has been running beneath the surface of the apparent stability. The foundation requires attention.",
    "the gift": "The shadow gift is the full inventory of what the family system actually transmitted — the wounds alongside the wealth, the patterns alongside the property.",
    "what to release": "The pretense that the family structure is functioning when it is not. The Ten of Pentacles reversed does not benefit from the maintenance of appearances.",
    "the seed": "Plant the intention to break the generational pattern that has cost more than the material inheritance that accompanied it.",
    "the obstacle": "The weight of unspoken family expectations — the architecture of obligation that surrounds the legacy and makes it a burden as much as a gift.",
    "first steps": "Name the specific thing in the family or financial structure that is not working. Say it once, clearly, to yourself. Then decide what to do with the saying.",
    "what has grown": "A structure that looks stable from outside and has been quietly undermined from within — by unaddressed conflict, unexamined inheritance, or wealth that was never matched by warmth.",
    "what is illuminated": "The gap between the image of the ten pentacles and what the people inside the frame actually experience.",
    "what hides in the light": "The love that is present beneath the dysfunction. The family in the card is complicated; it is still a family.",
    "what must be released": "A legacy — belief, behavior, financial pattern, family role — that was received but not chosen, and that is costing more than it is worth.",
    "how to let go": "Name the pattern as a pattern — not as truth, not as identity, but as something inherited that can also be set down.",
    "what emerges": "A more honest foundation — less impressive perhaps, but actually solid. Built on what is chosen rather than what was given.",
  },
  74: { // Page of Pentacles (reversed)
    "mind": "The mind is racing past the practical foundations — drawn to the concept, allergic to the implementation, mistaking enthusiasm for competence.",
    "body": "The body has not been put to work on the thing the mind is excited about. The Page reversed is all vision and no callus.",
    "spirit": "The spirit is restless for mastery it has not yet earned — impatient with the unglamorous beginning, already imagining the achievement.",
    "action": "Do the boring foundational work that the exciting idea requires. The Page reversed needs to kneel in the actual earth, not imagine the harvest.",
    "the gift": "The shadow gift is the specific gap between aspiration and application — named honestly, it becomes the exact curriculum the learning requires.",
    "what to release": "The fantasy of the quick path to mastery. The Page of Pentacles reversed is being sold something that does not exist.",
    "the seed": "Plant the intention to begin at the beginning — to be genuinely new at this, with the patience for the unglamorous early stages that real skill requires.",
    "the obstacle": "Get-rich-quick thinking substituting for patient investment of effort. The Page reversed wants the coin without the labor that produced it.",
    "first steps": "Identify the foundational skill or knowledge that has been skipped in the rush to the interesting part. Go back and learn it.",
    "what has grown": "A gap between what is claimed and what is actually known — the particular vulnerability of the person who has learned to perform competence before earning it.",
    "what is illuminated": "The specific shortcuts that have been taken and the price they are about to be charged. The full moon shows the gap in the foundation.",
    "what hides in the light": "The genuine aptitude that is present — real, promising, capable of producing something — underneath the impatience that is currently preventing it from developing.",
    "what must be released": "The carelessness with learning — the treating of knowledge as optional decoration rather than the foundation on which everything else rests.",
    "how to let go": "Admit what you don't know. Out loud, to someone who can teach you. Let the pride of pretending to know go first.",
    "what emerges": "The beginning of genuine competence — slower than the fantasy version, more real, and therefore actually capable of producing what the fantasy only imagined.",
  },
  75: { // Knight of Pentacles (reversed)
    "mind": "The reliable mind has become the rigid mind — cataloguing reasons to stay still long past the point where staying still was wisdom.",
    "body": "The body has settled into a rut that calls itself a rhythm. There is a difference between sustainable pace and petrification.",
    "spirit": "The spirit is restless inside the immovability. The Knight reversed has been reliable for so long that reliability has become the only mode available.",
    "action": "Move. Not abandon the path — but take the next step that the excessive caution has been indefinitely postponing.",
    "the gift": "The shadow gift is the recognition of where patience has curdled into avoidance — where the genuine virtue of steadiness has become an excuse for not risking.",
    "what to release": "The excessive caution that is dressing itself as prudence. Not every risk is reckless. Some have been waiting long enough.",
    "the seed": "Plant the intention to move one step in the direction that the Knight reversed has been calling unreasonable. Test the unreasonableness.",
    "the obstacle": "Stubbornness presenting as reliability. The insistence on doing things the tried way, even when the tried way is no longer working.",
    "first steps": "Identify the thing that has been waiting for conditions that will never be ideal enough. Set a date and proceed under imperfect conditions.",
    "what has grown": "Inertia — patient effort curdled into the inability to change direction even when the direction has stopped serving its purpose.",
    "what is illuminated": "The full weight of the stagnation — how long the standing still has been happening, and what has been missed in the waiting.",
    "what hides in the light": "The fear underneath the caution — not of failure specifically, but of the disruption to the known and the safe.",
    "what must be released": "The approach that has outlived its usefulness. The Knight reversed honors the method that worked; the full moon asks what works now.",
    "how to let go": "Move first, evaluate after. The Knight reversed has been evaluating in place for too long. The assessment will be clearer from motion.",
    "what emerges": "Progress — the kind the Knight always produces when the caution is correctly calibrated rather than overrun. Reliable, real, and finally moving again.",
  },
  76: { // Queen of Pentacles (reversed)
    "mind": "The mind is tracking everyone else's needs and has quietly stopped tracking its own. The Queen reversed tends the garden and has forgotten she is also a plant.",
    "body": "The body is showing the signs of sustained self-neglect masquerading as care for others: depletion, exhaustion, the particular hollowness of giving more than is being replenished.",
    "spirit": "The spirit cannot be nourished by giving alone. The Queen reversed has made herself into a resource for others and forgotten that she is also a self.",
    "action": "Do something for yourself today. Not as a reward for having done enough for others — as a basic act of self-stewardship.",
    "the gift": "The shadow gift is the precise recognition of where the line between generosity and self-erasure lives — and the beginning of choosing not to cross it.",
    "what to release": "The role of the one who holds everything together. It is true that you can do it. It is also true that no one asked you to do it at the cost of yourself.",
    "the seed": "Plant the intention to tend yourself with a fraction of the care given to others — not equally, to start — just not with nothing.",
    "the obstacle": "The inability to receive without immediately redirecting the attention back outward. Care comes in; the Queen reversed reroutes it before it can land.",
    "first steps": "Cancel or defer one commitment that exists purely to serve others at the cost of your own necessary rest or restoration.",
    "what has grown": "A household, a project, a set of relationships — tended beautifully — and underneath it, a self that has been running on fumes.",
    "what is illuminated": "The full cost of the overextension — not just fatigue, but the particular grief of a self that has been perpetually deferred.",
    "what hides in the light": "The resentment that the selfless Queen has not allowed herself to feel — because feeling it would require admitting that the giving has not been entirely free.",
    "what must be released": "The giving that is driven by the inability to stop rather than by genuine abundance. Compulsive care is not the same as generosity.",
    "how to let go": "Let someone else tend the garden for one day. Leave it imperfectly tended and let that be enough.",
    "what emerges": "A self that has been returned to — tentative, in need of care, but present. The Queen cannot give what she has not first received.",
  },
  77: { // King of Pentacles (reversed)
    "mind": "The mind that built the empire is now being run by it — thinking in metrics of accumulation rather than stewardship, confusing what was built with who did the building.",
    "body": "The body has been used as an instrument of material achievement and is now registering the cost. Even kings must eventually tend the ground beneath the throne.",
    "spirit": "The spirit is not impressed by the empire. It is asking what the empire is for — and the King reversed does not yet have an honest answer.",
    "action": "Ask what you are building this for. Not the official version — the real one. Let the answer surprise you.",
    "the gift": "The shadow gift is the recognition of how thoroughly the material has been mistaken for the meaningful. The King reversed has the castle and has lost the warmth.",
    "what to release": "The identity constructed from net worth. You are not your assets. The King reversed has forgotten that distinction.",
    "the seed": "Plant the intention to steward rather than accumulate — to hold the material abundance in service of something that cannot be purchased with it.",
    "the obstacle": "The materialism that has crossed into identity — the sense that having more proves something about worth rather than resources.",
    "first steps": "Give something significant away — money, time, power — not for the appearance of generosity but to test whether the self remains intact without it.",
    "what has grown": "An empire that is structurally impressive and spiritually empty — the Midas problem, accumulated one quiet compromise at a time.",
    "what is illuminated": "What the abundance has cost — in relationships unmade, in joy deferred, in the warmth sacrificed to the efficiency of building.",
    "what hides in the light": "The fear of loss that drove the accumulation — still present, still running, now hidden underneath the very security it built.",
    "what must be released": "The accumulation that has outrun its purpose — the having that exists to prove something rather than to build anything.",
    "how to let go": "Use the wealth in a way that cannot be converted back into status. Give it irrevocably to something beyond the self.",
    "what emerges": "The King upright — the steward who holds abundance with open hands, who knows the empire is a tool and not a throne.",
  },
};
