export interface CardDefinition {
  id: number;
  name: string;
  arcana: "major" | "minor";
  suit?: "wands" | "cups" | "swords" | "pentacles";
  number: number;
  descriptions: [string, string, string, string, string];
  reversedDescriptions: [string, string, string, string, string];
}

export function cardImageSlug(cardId: number, pack = "default"): string {
  return `${pack}/${String(cardId).padStart(2, "0")}`;
}

export function getCardDescription(
  card: CardDefinition,
  rarityScore: number,
  isReversed: boolean
): string {
  return (isReversed ? card.reversedDescriptions : card.descriptions)[
    rarityScore - 1
  ];
}

export const CARDS: CardDefinition[] = [
  {
    id: 0,
    name: "The Fool",
    arcana: "major",
    number: 0,
    descriptions: [
      "A new journey begins. Step forward without overthinking.",
      "The precipice before the leap — innocence and raw possibility hang in the air.",
      "You stand at the threshold of transformation, unencumbered by fear. The abyss is not a warning; it is an invitation.",
      "Chaos threads through your path like silver lightning. What the world calls recklessness, the cosmos calls faith.",
      "Before form there was the Fool — pure becoming, the universe folding itself into experience for the first time.",
    ],
    reversedDescriptions: [
      "Hesitation holds you back. A first step is being avoided.",
      "Recklessness without reflection courts avoidable ruin. Pause before the plunge.",
      "The leap is real, but the timing is wrong — the ground below has not yet solidified.",
      "An old self refuses to dissolve, clinging to the cliff's edge while the new self waits in the wind.",
      "The primordial leap inverted: creation hesitates at its own threshold, and nothing begins.",
    ],
  },
  {
    id: 1,
    name: "The Magician",
    arcana: "major",
    number: 1,
    descriptions: [
      "Focus your will. The tools you need are already in your hands.",
      "Intent becomes action. You have more agency than you are claiming.",
      "The four elements answer your call. What you envision, you can manifest — the channel between thought and world is open.",
      "You are the conduit through which possibility becomes matter. The universe does not create for you; it creates through you.",
      "The first act of will after the void. All of creation is this gesture: as above, so below.",
    ],
    reversedDescriptions: [
      "Scattered energy yields scattered results. Gather yourself.",
      "Skills exist but remain untapped, hidden behind self-doubt or distraction.",
      "The channel is open but misdirected — power flows into illusion or manipulation.",
      "Will turned inward becomes manipulation; the tools of creation are being used to deceive.",
      "The infinite potential of the void collapses into stagnation when will is absent.",
    ],
  },
  {
    id: 2,
    name: "The High Priestess",
    arcana: "major",
    number: 2,
    descriptions: [
      "Trust your intuition. Something important is just below the surface.",
      "Still water reveals what turbulence conceals. Listen before you speak.",
      "The veil between worlds is thin for you now. What you sense but cannot articulate is truer than what you can explain.",
      "Ancient knowing moves through you, bypassing logic. The moon's pull on tides is not intellectual — neither is this.",
      "Before the Word was silence. You carry the memory of that silence.",
    ],
    reversedDescriptions: [
      "Intuition is being ignored in favour of noise. Go quiet.",
      "Inner wisdom exists but is suppressed by external pressure or self-doubt.",
      "Hidden knowledge is being withheld — from you, or by you.",
      "The unconscious floods upward, overwhelming rather than guiding.",
      "The primordial silence is broken before its time; wisdom spoken too soon becomes confusion.",
    ],
  },
  {
    id: 3,
    name: "The Empress",
    arcana: "major",
    number: 3,
    descriptions: [
      "Nurture what is growing. Something in your life needs care.",
      "Abundance flows from patience. Creation is not forced — it unfolds.",
      "The fertile ground of your life is rich right now. What you plant with genuine care will return multiplied.",
      "You carry the generative force of nature itself. Growth, beauty, and abundance are not rewards — they are your nature.",
      "She is the earth remembering it is alive — all growth, all nourishment, all the warmth that makes life possible.",
    ],
    reversedDescriptions: [
      "Neglect is stunting growth. Tend to what is wilting.",
      "Creative blocks or dependence are interrupting natural abundance.",
      "Over-nurturing suffocates as surely as neglect. Give space to what you love.",
      "Abundance withheld from itself — the garden that will not allow rain.",
      "Creation turned against itself: the primordial mother becoming a force of consumption.",
    ],
  },
  {
    id: 4,
    name: "The Emperor",
    arcana: "major",
    number: 4,
    descriptions: [
      "Establish structure. Clarity in your foundations will serve you.",
      "Authority wielded with wisdom is a form of care. Take responsibility.",
      "The order you build now will shelter others later. Leadership is a form of love.",
      "Your will can become law — not through force but through the coherence of your vision and the consistency of your action.",
      "The first law given to chaos. Structure is not the enemy of creation; it is its skeleton.",
    ],
    reversedDescriptions: [
      "Rigidity is breaking what flexibility would bend. Loosen your grip.",
      "Authority is being misused or refused at cost.",
      "Control disguised as care. Dominance where partnership is needed.",
      "The tyrant's throne — power that has forgotten its origin in service.",
      "The primordial law inverted: order collapsing into the tyranny it was meant to prevent.",
    ],
  },
  {
    id: 5,
    name: "The Hierophant",
    arcana: "major",
    number: 5,
    descriptions: [
      "Tradition holds wisdom worth examining. Look to what has lasted.",
      "A mentor, institution, or belief system offers genuine guidance now.",
      "The bridge between the sacred and the everyday is crossed through ritual, commitment, and shared understanding.",
      "You are both student and keeper of something ancient. The lineage you carry is not a burden — it is a living inheritance.",
      "The first church was the sky. All tradition is humanity trying to remember what it already knew.",
    ],
    reversedDescriptions: [
      "Dogma is blocking growth. Question what you have been told to accept.",
      "A tradition or institution is failing you or those it claims to serve.",
      "Rebellion for its own sake has its own rigidity. Discern before you discard.",
      "The keeper of keys who has lost the door. Spiritual authority without spiritual truth.",
      "The sacred form hollowed out — ritual without meaning, law without love.",
    ],
  },
  {
    id: 6,
    name: "The Lovers",
    arcana: "major",
    number: 6,
    descriptions: [
      "A meaningful choice is before you. Your values are the compass.",
      "Union — of people, ideas, or aspects of self — is deepening something important.",
      "This is not merely a decision; it is an alignment. What you choose now will define what kind of person you are becoming.",
      "Love at its highest is not comfort but confrontation — the mirror that shows you who you truly are and asks if you can bear it.",
      "Before separation there was the primal unity. The Lovers remember what the world has forgotten: that beneath all division is one.",
    ],
    reversedDescriptions: [
      "A misalignment between values and actions is causing friction.",
      "Disharmony in a relationship, or a choice being avoided.",
      "Temptation is pulling you away from your deeper knowing. The easy path is not always the true one.",
      "Union fractured — the mirror turned away, the beloved made into an enemy.",
      "The primal split without the hope of reunion; separation that has forgotten its own origin in wholeness.",
    ],
  },
  {
    id: 7,
    name: "The Chariot",
    arcana: "major",
    number: 7,
    descriptions: [
      "Push forward. Willpower and focus will carry you through.",
      "Competing forces can be harnessed rather than fought. Direction matters more than speed.",
      "You are capable of commanding opposing impulses and driving them toward a single goal. This is mastery, not suppression.",
      "The triumph of will is not over others but over the chaos within. You are the charioteer of your own becoming.",
      "The cosmos in motion — not pulled by external forces but driven by the single, unwavering intent at its center.",
    ],
    reversedDescriptions: [
      "Loss of direction or scattered effort is stalling momentum.",
      "The opposing forces have gained the upper hand. Something needs to be reined in.",
      "Aggression or force is being applied where finesse is needed.",
      "Victory pursued at any cost becomes its own defeat. The chariot without a destination.",
      "Primordial drive without purpose — raw momentum becoming destruction.",
    ],
  },
  {
    id: 8,
    name: "Strength",
    arcana: "major",
    number: 8,
    descriptions: [
      "Patience and compassion are your power right now, not force.",
      "Courage does not mean the absence of fear. You have what this requires.",
      "The wildness within you is not an enemy to be tamed but an ally to be understood. Your shadow, befriended, becomes your greatest strength.",
      "You carry a quiet ferocity that moves the world more surely than violence ever could. This is the power that endures.",
      "Before there was armour there was the open hand, and the lion that lay down because it was met with love.",
    ],
    reversedDescriptions: [
      "Self-doubt or fear is quietly eroding your resolve. Name it.",
      "Force is being used where gentleness would succeed. Or: necessary boundaries are absent.",
      "Inner wildness suppressed becomes shadow. What are you refusing to acknowledge?",
      "The lion turned against its keeper — primal drives overwhelming the capacity for gentleness.",
      "Strength without love is only violence. The primordial force turned on itself.",
    ],
  },
  {
    id: 9,
    name: "The Hermit",
    arcana: "major",
    number: 9,
    descriptions: [
      "Solitude and reflection are offering something the crowd cannot.",
      "Your inner lantern is lit. Trust it to guide you through unfamiliar terrain.",
      "This withdrawal is not abandonment — it is the sacred work of turning toward the source. The light you carry is for your path first.",
      "You have reached the place on the mountain where the guides have turned back. What remains is between you and the silence.",
      "The ancient who carries the first light — solitude not as exile but as the original country of the soul.",
    ],
    reversedDescriptions: [
      "Isolation has crossed the line from necessary to harmful. Re-engage.",
      "The inner voice is being ignored in favour of external noise.",
      "Withdrawal from connection is protecting a wound rather than healing it.",
      "The lantern extinguished — wisdom turned inward until it burns the holder.",
      "Primordial solitude without the possibility of return: the self that has forgotten it was once in relation.",
    ],
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    arcana: "major",
    number: 10,
    descriptions: [
      "Change is underway. Flow with it rather than against it.",
      "A cycle is completing. What comes next has already been set in motion.",
      "The wheel does not turn for you or against you — it turns. Your wisdom lies in moving with it, in reading the current before it shifts.",
      "Fortune is not luck but alignment — the capacity to recognise the turning point and meet it with the whole of yourself.",
      "The great cycle that precedes all history — the original rhythm to which all events are still dancing.",
    ],
    reversedDescriptions: [
      "Resistance to inevitable change is making things harder than they need to be.",
      "A run of bad luck — but cycles turn. This too will shift.",
      "The wheel is turning but you are clinging to a spoke. Let go.",
      "External forces have taken the wheel. Reclaim what agency you can.",
      "The cycle inverted: change without evolution, motion without meaning.",
    ],
  },
  {
    id: 11,
    name: "Justice",
    arcana: "major",
    number: 11,
    descriptions: [
      "An honest accounting of cause and effect is due. Truth will serve you.",
      "A fair outcome is possible when all facts are clear. Objectivity is your ally.",
      "The scales demand that nothing be hidden from yourself. The judgment that truly serves is the one you apply first to your own actions.",
      "Justice is not vengeance and it is not mercy — it is precise, it is clear, and it sees everything you have done and left undone.",
      "The original law that predates all legal systems: action and consequence, perfectly balanced, at the centre of all things.",
    ],
    reversedDescriptions: [
      "A situation is not being seen clearly. Bias or avoidance is distorting judgment.",
      "An unfair outcome is at risk. All evidence must be weighed.",
      "Self-deception about your own role in a situation is blocking resolution.",
      "Justice delayed by corruption, cowardice, or willful blindness.",
      "The scales tipped beyond recovery — the original law betrayed at its source.",
    ],
  },
  {
    id: 12,
    name: "The Hanged Man",
    arcana: "major",
    number: 12,
    descriptions: [
      "Pause and reconsider from a different angle. The delay is meaningful.",
      "Voluntary surrender to a larger process is bringing hidden insight.",
      "The world looks entirely different from this inverted vantage point. What you called a problem may be a doorway — but only if you stop struggling.",
      "This is the gift that cannot be taken by force: the revelation that arrives only when all striving ceases.",
      "The suspended moment before all transformation — the breath held between one world and the next.",
    ],
    reversedDescriptions: [
      "Stalling that masquerades as waiting. Useful pause has become avoidance.",
      "Sacrifice is being resisted at cost. What needs to be released?",
      "The liminal space has overstayed its welcome. It is time to emerge.",
      "Martyrdom without wisdom — suffering without the insight it was meant to deliver.",
      "The suspension that becomes a prison: the sacred pause that refuses to end.",
    ],
  },
  {
    id: 13,
    name: "Death",
    arcana: "major",
    number: 13,
    descriptions: [
      "An ending is clearing the way for something new. Let go.",
      "Transformation is not optional here — resistance only prolongs the transition.",
      "This is the most profound of the card's promises: nothing that truly matters can be destroyed by this kind of ending. What remains will be essential.",
      "The great leveller who takes everything that was never really yours to keep. In the wake of that stripping away, you discover what you actually are.",
      "The oldest mystery: that endings are not the opposite of beginnings but their deepest form.",
    ],
    reversedDescriptions: [
      "Clinging to what is already gone is preventing new life from taking root.",
      "Fear of change is making an inevitable transition more painful.",
      "The ending is resisted to the point of stagnation. Release is needed.",
      "The undead — the refusal to let something that has ended actually end.",
      "Primordial transformation blocked: the universe refusing to complete its own cycle.",
    ],
  },
  {
    id: 14,
    name: "Temperance",
    arcana: "major",
    number: 14,
    descriptions: [
      "Balance and moderation are the path forward. Integration is underway.",
      "The middle way is not weakness — it is the most precise form of strength.",
      "You are being asked to hold opposites without collapsing them — to let fire and water meet in you without either destroying the other.",
      "The alchemical work is the patient blending of what seemed incompatible. Time and flow are your instruments.",
      "The original alchemy — the cosmos finding its own equilibrium from within the chaos of its own making.",
    ],
    reversedDescriptions: [
      "Excess or imbalance in some area of life is creating instability.",
      "Patience is running out before the work is done. Hold the course.",
      "Extremes are pulling you in opposite directions. Find the center.",
      "Imbalance so deep it has become identity — chaos mistaken for character.",
      "The primordial balance shattered: the universe caught between its own extremes.",
    ],
  },
  {
    id: 15,
    name: "The Devil",
    arcana: "major",
    number: 15,
    descriptions: [
      "Name what has a hold on you. Awareness is the first loosening of the chain.",
      "An unhealthy attachment or pattern is more visible now. You can see the chain — which means you can examine it.",
      "The bonds shown here are not usually forced. The terrifying truth is that they were chosen, however unconsciously, and so they can be unchosen.",
      "Shadow material rises into view. The Devil's greatest trick is convincing you that what binds you is freedom. Look again.",
      "The primordial shadow — not evil but the part of creation that turned away from its own light and called the darkness home.",
    ],
    reversedDescriptions: [
      "Breaking free from an old pattern or addiction is possible right now.",
      "The chains are looser than they appear. A small act of will can begin the release.",
      "Freedom is close, but old identities around the limitation resist release.",
      "The shadow examined and integrated — the Devil dethroned by the light of honest self-knowledge.",
      "The primordial binding released: creation reclaiming what it surrendered to darkness.",
    ],
  },
  {
    id: 16,
    name: "The Tower",
    arcana: "major",
    number: 16,
    descriptions: [
      "Something built on a false foundation is coming down. This is necessary.",
      "Sudden change disrupts, but the disruption is clearing ground that needed clearing.",
      "What is destroyed was not as solid as it appeared. The lightning reveals — it does not create the flaw.",
      "The Tower falls so that something real can be built in its place. Mourn what is lost; do not rebuild the lie.",
      "The original cataclysm — the cosmic correction that runs through all things, the universe refusing to maintain a beautiful falsehood.",
    ],
    reversedDescriptions: [
      "A necessary collapse is being avoided or delayed at cost.",
      "The crisis has passed but its lesson has not yet landed.",
      "Catastrophising about change that is actually manageable.",
      "The Tower avoided through compromise — the false structure preserved, and so the lightning waits.",
      "The primordial correction denied: the universe held back from its own necessary destruction.",
    ],
  },
  {
    id: 17,
    name: "The Star",
    arcana: "major",
    number: 17,
    descriptions: [
      "Hope is real and warranted. Let yourself believe in what is coming.",
      "After disruption comes the quiet clarity of what truly matters. Rest in it.",
      "The star shines whether or not you are watching. Its constancy is a fact, not a promise that depends on your faith.",
      "You have been remade. The sky above the ruins of the old life is the same sky it always was — and it is full of stars.",
      "The first light after the first darkness. The star that predates the world and will outlast it.",
    ],
    reversedDescriptions: [
      "Hope is present but being suppressed by fear or disappointment. Let it breathe.",
      "Disillusionment is colouring a situation darker than it actually is.",
      "Waiting for rescue rather than participating in your own renewal.",
      "The star obscured — hope that exists but cannot reach the one who needs it.",
      "The primordial light turned inward: the universe forgetting its own luminosity.",
    ],
  },
  {
    id: 18,
    name: "The Moon",
    arcana: "major",
    number: 18,
    descriptions: [
      "Things are not as clear as they seem. Proceed carefully and trust your instincts.",
      "The unconscious is speaking through dreams, intuition, and unease. Pay attention.",
      "You are moving through terrain that cannot be mapped in daylight. The Moon's light distorts and reveals simultaneously — both are true.",
      "Fear and illusion have always shared territory. What you are afraid of may be real; it may be shadow. The only way to know is to keep walking.",
      "The primordial night — the original unknown that preceded all knowing, and which nothing that has ever been known has fully conquered.",
    ],
    reversedDescriptions: [
      "Confusion is lifting. What was murky is beginning to clarify.",
      "Anxiety or irrational fears are louder than usual. Name them rather than feeding them.",
      "Illusions are being seen through. This can be disorienting before it is freeing.",
      "The moon's distortions taken as reality — the map mistaken for the territory, the shadow mistaken for the thing.",
      "The primordial confusion absolute: the universe lost in its own night, with no dawn in memory.",
    ],
  },
  {
    id: 19,
    name: "The Sun",
    arcana: "major",
    number: 19,
    descriptions: [
      "Clarity and joy are available right now. Receive them.",
      "What was hidden or confused is now lit plainly. Trust what you see.",
      "Vitality, confidence, and warmth radiate from you and through your circumstances. This is not performance — it is your actual state, made visible.",
      "The Sun shows everything — the beautiful and the difficult — without shadow or concealment. To be fully seen is the gift and the demand of this moment.",
      "The first light that named itself Light. All warmth, all visibility, all the conditions for life — here, at their source.",
    ],
    reversedDescriptions: [
      "Optimism is being blocked by circumstances or inner resistance. Seek the light.",
      "Ego or arrogance is dimming what should be a moment of genuine radiance.",
      "Vitality exists but is being withheld or misdirected.",
      "The blinding sun — truth so bright it can no longer be approached.",
      "The primordial light turned away from creation: warmth that refuses to warm.",
    ],
  },
  {
    id: 20,
    name: "Judgement",
    arcana: "major",
    number: 20,
    descriptions: [
      "A call to rise. Something is asking you to step into a larger version of yourself.",
      "Clarity about your past is creating genuine freedom for your future.",
      "The reckoning is not punishment — it is the invitation to be seen fully, including the parts you have hidden, and to find that you are still whole.",
      "You are standing at the threshold of your own rebirth. The trumpet has sounded. The only question is whether you will answer.",
      "The original awakening — the moment all of creation hears its own name called and remembers what it was before it forgot.",
    ],
    reversedDescriptions: [
      "Self-doubt or guilt is preventing you from answering a genuine call.",
      "A necessary reckoning is being avoided. What needs to be faced?",
      "Old judgments — others' or your own — are being mistaken for truth.",
      "The call heard but refused: the self that will not be remade even when the old form has failed.",
      "The primordial awakening withheld: the universe at the threshold, unwilling to cross.",
    ],
  },
  {
    id: 21,
    name: "The World",
    arcana: "major",
    number: 21,
    descriptions: [
      "A cycle is completing with real accomplishment behind it. Acknowledge what you have done.",
      "Integration of hard-won lessons is bringing a sense of wholeness and arrival.",
      "What began so long ago — The Fool's first step — has brought you here. Everything was part of the journey, including what you would rather not remember.",
      "You are the world, dancing at the center of your own becoming. This is not the end — it is the fullness before the next beginning.",
      "The great completion — the universe recognising itself in the mirror of its own creation.",
    ],
    reversedDescriptions: [
      "A cycle is near completion but something is preventing the final step. Identify it.",
      "Success is present but not fully claimed or integrated.",
      "Stagnation at the finish line — the achievement within reach but not grasped.",
      "The world held just out of reach — wholeness visible but not inhabitable.",
      "The primordial completion withheld: creation at the edge of recognising itself, unable to close the circle.",
    ],
  },
  // Minor Arcana — Wands
  {
    id: 22,
    name: "Ace of Wands",
    arcana: "minor",
    suit: "wands",
    number: 1,
    descriptions: [
      "A spark of new energy or inspiration is available. Reach for it.",
      "Creative fire is being handed to you. What will you kindle?",
      "Pure potential in its most vital form — the universe leaning forward and offering you the first flame of something real.",
      "This is the fire before it becomes anything, the passion before it has a name. It is asking only that you receive it and begin.",
      "The primordial creative impulse — the first light of the first will, the moment the universe decided to make something.",
    ],
    reversedDescriptions: [
      "Creative energy is blocked or stalled. What is dampening the spark?",
      "An opportunity for new beginnings is being missed or delayed.",
      "Enthusiasm exists but lacks direction or follow-through.",
      "The flame offered but not taken — creative potential dissipating for want of a hand to hold it.",
      "The first fire withheld from its own creation: will that cannot yet strike the match.",
    ],
  },
  {
    id: 23,
    name: "Two of Wands",
    arcana: "minor",
    suit: "wands",
    number: 2,
    descriptions: [
      "You have made a start. Now plan where it leads.",
      "The world is wider than your current view. Consider expanding your horizon.",
      "You hold the fire in one hand and the map in the other. The power here is in choosing the direction, not the destination.",
      "This is the moment before departure — the profound, quiet authority of someone who has decided but not yet moved.",
      "The primordial pause between the spark and the journey — the will that has named itself and is now choosing its direction.",
    ],
    reversedDescriptions: [
      "Indecision is stalling forward momentum. Make a choice and move.",
      "Planning has become a substitute for action. The world is waiting.",
      "Fear of the unknown is making the familiar feel safer than it is.",
      "The map held but never consulted — the power of vision refused.",
      "The primordial decision unmade: will that has named itself but cannot choose a direction.",
    ],
  },
  {
    id: 24,
    name: "Three of Wands",
    arcana: "minor",
    suit: "wands",
    number: 3,
    descriptions: [
      "Something you set in motion is now delivering results. Stay watchful.",
      "Your reach is extending further than you thought possible. Trust the expansion.",
      "The ships on the horizon are yours — you sent them out, and now they are returning. Patience and vision are being rewarded.",
      "You have become the kind of person who waits for ships from the high ground, not from the shore. That shift in position changes everything.",
      "The first fruits of will — creation looking back at what it has set in motion and recognising its own work.",
    ],
    reversedDescriptions: [
      "Expected results are delayed. Examine what may need adjusting.",
      "Expansion is being blocked by short-sightedness or poor planning.",
      "The ships are delayed or lost. Adapt rather than wait.",
      "Vision without execution — the high ground abandoned for the shore.",
      "Creation looking back and not recognising its own work: the will estranged from its outcomes.",
    ],
  },
  {
    id: 25,
    name: "Four of Wands",
    arcana: "minor",
    suit: "wands",
    number: 4,
    descriptions: [
      "A moment of celebration and belonging. Receive it without reservation.",
      "Home — whether place or people — is offering real nourishment right now.",
      "The harvest festival of the soul: a pause to honour what has been built, who has been built alongside, and what remains worth protecting.",
      "Community is not a consolation prize for solitude. This is the fire that sustains, the circle that holds.",
      "The first homecoming — the original return to warmth and belonging after the long work of becoming.",
    ],
    reversedDescriptions: [
      "Instability in home or community is creating unease. Address the foundations.",
      "A celebration is incomplete or tinged with something unresolved.",
      "Belonging is sought but not found, or found but not felt.",
      "The fire that warms the community extinguished — the circle that held, broken.",
      "The primordial homecoming refused: the self that cannot return because it has forgotten the way.",
    ],
  },
  {
    id: 26,
    name: "Five of Wands",
    arcana: "minor",
    suit: "wands",
    number: 5,
    descriptions: [
      "Friction and competition are present. Stay in the game.",
      "The clash of multiple wills is producing heat. Not all conflict is harmful.",
      "What looks like chaos may be the rough work of multiple strong visions finding their relationship to each other. Stay in it long enough to find out.",
      "This is the creative tension that precedes synthesis — the fight before the breakthrough.",
      "The primordial friction — the original collision of forces that generates, rather than destroys, the conditions for creation.",
    ],
    reversedDescriptions: [
      "Unnecessary conflict is draining energy. Seek common ground.",
      "Suppressed competition is creating hidden tensions. Name the dynamic.",
      "The conflict has become the point, rather than a means to an end.",
      "Destructive competition with no creative outcome — fire consuming what it was meant to light.",
      "The primordial friction turned against itself: conflict that no longer generates, only destroys.",
    ],
  },
  {
    id: 27,
    name: "Six of Wands",
    arcana: "minor",
    suit: "wands",
    number: 6,
    descriptions: [
      "Recognition and success are arriving. Accept them with grace.",
      "Victory has been earned. The challenge now is to receive it without arrogance.",
      "This is the moment the crowd lifts its voice for you. Whether or not you sought it, you were seen and recognised for real achievement.",
      "The triumph is genuine, but it is a waypoint, not a destination. Savour it; then look to what comes next.",
      "The first victory — the moment creation recognised its own excellence and named it good.",
    ],
    reversedDescriptions: [
      "Delayed recognition or a setback is temporarily obscuring real achievement.",
      "Success feels hollow or is being used for ego rather than growth.",
      "A fall from public favour — deserved or not — is demanding recalibration.",
      "The triumph turned against the triumphant — victory that poisons rather than nourishes.",
      "The first recognition withheld: creation that made something excellent and no voice arose to name it.",
    ],
  },
  {
    id: 28,
    name: "Seven of Wands",
    arcana: "minor",
    suit: "wands",
    number: 7,
    descriptions: [
      "Hold your ground. You are being challenged but you have the high position.",
      "Defending your position requires persistence, not aggression. Stay firm.",
      "You have climbed to a height worth defending. The challenges coming at you from below confirm the value of what you have built.",
      "The exhaustion of continual defence can wear you down before the opposition ever reaches you. Pace yourself.",
      "The original stand — the first time creation refused to yield what it had built.",
    ],
    reversedDescriptions: [
      "You are yielding ground that does not need to be surrendered. Reassess.",
      "Defensiveness has become reactivity. Choose your battles more carefully.",
      "Overwhelm from multiple fronts is making defence seem impossible. Prioritise.",
      "The high ground abandoned — the position that cost so much, surrendered.",
      "Creation yielding what it built before the challenge was real: the primordial capitulation.",
    ],
  },
  {
    id: 29,
    name: "Eight of Wands",
    arcana: "minor",
    suit: "wands",
    number: 8,
    descriptions: [
      "Things are accelerating. Act quickly and with clear aim.",
      "Communication and movement are in flow. Use this momentum.",
      "Every arrow is in the air and every one of them is heading somewhere. The clarity of this moment is the gift — do not waste it on hesitation.",
      "The swift completion of what has been long in preparation. The moment when all the tributaries become one river.",
      "The primordial momentum — the first time creation moved so quickly it became luminous.",
    ],
    reversedDescriptions: [
      "Slowdowns or miscommunications are frustrating progress. Investigate the blockage.",
      "Haste without direction is scattering energy. Slow down enough to aim.",
      "Things that should be moving are stagnating. What needs to be released?",
      "Arrows in flight with no target — velocity without vector.",
      "The primordial momentum reversed: creation in motion but moving in circles.",
    ],
  },
  {
    id: 30,
    name: "Nine of Wands",
    arcana: "minor",
    suit: "wands",
    number: 9,
    descriptions: [
      "You are nearly through. Don't give up now.",
      "Battle-worn but not broken — there is still enough left for the final push.",
      "The wound you are guarding is real. So is your capacity to continue. Both are true simultaneously.",
      "Resilience is not the absence of exhaustion — it is continuing to stand after it arrives.",
      "The original endurance — creation refusing to yield even at the point when yielding would have been easier.",
    ],
    reversedDescriptions: [
      "Stubbornness is being mistaken for strength. Know when to rest or redirect.",
      "Past wounds are making the present seem more dangerous than it is.",
      "The last reserves are being used wisely or unwisely — discern which.",
      "The warrior who cannot lay down arms even when the war is over.",
      "Endurance become rigidity — creation that cannot stop fighting even when the fight has ended.",
    ],
  },
  {
    id: 31,
    name: "Ten of Wands",
    arcana: "minor",
    suit: "wands",
    number: 10,
    descriptions: [
      "The load is heavy. Put down what isn't truly yours to carry.",
      "An ending is near. The burden lessens when you reach it.",
      "You have taken on more than was ever sustainable. The question is not whether it is too heavy — it clearly is — but which parts of it are actually yours.",
      "The completion of this cycle requires that you examine what ambition has accumulated. Not all of it serves you.",
      "The weight of completed creation — the moment it all arrives at once and must be set down before the next beginning.",
    ],
    reversedDescriptions: [
      "An impossible burden is being released or renegotiated. Welcome the relief.",
      "Over-responsibility is being challenged — but resistance to letting go persists.",
      "Collapse under the weight of too much, too long. Recovery is needed.",
      "The burden that has become identity — the load that cannot be put down because the self has forgotten it has hands.",
      "Creation exhausted by its own weight, unable to reach the threshold where the burden could be set down.",
    ],
  },
  {
    id: 32,
    name: "Page of Wands",
    arcana: "minor",
    suit: "wands",
    number: 11,
    descriptions: [
      "A message or a spark of inspiration is arriving. Stay curious.",
      "Fresh energy and enthusiasm are available — channel them before they scatter.",
      "The fire is young here, and young fire is the most dangerous and most wonderful kind. Let it explore without forcing it into form too quickly.",
      "The messenger who doesn't yet know the full scope of what they carry — but carries it with total commitment.",
      "The first curiosity — the original wonder before it had named anything and could still be surprised by everything.",
    ],
    reversedDescriptions: [
      "Creative ideas arrive but are not followed through. The spark needs more oxygen.",
      "Impatience or recklessness is burning up energy before it can be directed.",
      "News is delayed or unreliable. Verify before acting.",
      "Enthusiasm that destroys what it touches — the fire that doesn't know how to love what it lights.",
      "The primordial wonder stunted: curiosity that cannot grow into courage.",
    ],
  },
  {
    id: 33,
    name: "Knight of Wands",
    arcana: "minor",
    suit: "wands",
    number: 12,
    descriptions: [
      "Bold action is called for. Move toward what excites you.",
      "Passion and courage are propelling you forward. Trust the energy.",
      "The Knight of Wands does not stop to calculate odds — this is both the gift and the danger. The momentum is real; so is the need for occasional steering.",
      "You are the kind of person who runs toward fire. Remember that every fire also has an outer edge.",
      "The first quest — the original moment courage chose a direction and committed absolutely.",
    ],
    reversedDescriptions: [
      "Recklessness is outpacing wisdom. Slow down before the collision.",
      "Scattered energy is preventing any single pursuit from gaining traction.",
      "Arrogance or impulsivity is undermining a genuine strength.",
      "The rider and the horse at odds — will that wants to move in every direction at once.",
      "The primordial quest without a quest: courage that has forgotten how to choose.",
    ],
  },
  {
    id: 34,
    name: "Queen of Wands",
    arcana: "minor",
    suit: "wands",
    number: 13,
    descriptions: [
      "Warmth, confidence, and magnetic energy are available to you.",
      "Lead with enthusiasm and others will follow naturally.",
      "The Queen of Wands knows her own fire — she neither hides it nor lets it consume others. That balance is real mastery.",
      "This is charisma rooted in genuine self-knowledge: the warmth that comes from being so fully oneself that there is no longer anything to perform.",
      "The original warmth — the fire that knows how to hold without burning.",
    ],
    reversedDescriptions: [
      "Confidence has tipped into domination. Notice how you are using your warmth.",
      "Jealousy or insecurity is temporarily dimming your natural radiance.",
      "Power is being withheld from yourself — the fire banked too low.",
      "The fire turned territorial — warmth that burns whatever comes too close.",
      "The primordial warmth inverted: fire that forgets what it was meant to illuminate.",
    ],
  },
  {
    id: 35,
    name: "King of Wands",
    arcana: "minor",
    suit: "wands",
    number: 14,
    descriptions: [
      "Lead with vision and integrity. Others are looking to you.",
      "Creative authority and mature passion are your resources right now.",
      "The King of Wands has learned to be the fire, not just to start it. Vision, charisma, and the capacity to inspire are at their height.",
      "The alchemical king — he has transmuted raw enthusiasm into sustained, creative leadership that builds rather than burns.",
      "The primordial creative authority — the fire that knows how to govern what it has made.",
    ],
    reversedDescriptions: [
      "Visionary energy has become imperious. Check in with those you lead.",
      "Impulsiveness is undermining mature authority.",
      "Creative power is being used for ego rather than genuine creation.",
      "The king who has forgotten that authority exists in service of others.",
      "The primordial fire-king whose power has become its own end — creation that serves only itself.",
    ],
  },
  // Minor Arcana — Cups
  {
    id: 36,
    name: "Ace of Cups",
    arcana: "minor",
    suit: "cups",
    number: 1,
    descriptions: [
      "A new emotional beginning is offered. Open to it.",
      "Love, compassion, or creative flow is available in abundance right now.",
      "The cup overflows — not from excess but from source. What is being offered here is not a thing but a state: the original capacity to feel.",
      "This is the heart before it learned to guard itself. Receive it.",
      "The first feeling — the primordial opening of the universe to its own experience.",
    ],
    reversedDescriptions: [
      "Emotional walls are blocking what is trying to be felt or received.",
      "A new beginning is available but grief or fear is making it difficult to reach.",
      "The cup is present but tipped — the gift is available but not yet received.",
      "Emotional numbness or overflow — the cup that cannot hold what is offered.",
      "The primordial feeling withheld: the universe refusing its own capacity for experience.",
    ],
  },
  {
    id: 37,
    name: "Two of Cups",
    arcana: "minor",
    suit: "cups",
    number: 2,
    descriptions: [
      "A genuine connection is deepening. Honour it.",
      "Partnership — romantic, professional, or otherwise — is reaching a point of real mutual recognition.",
      "The meeting of equals: two forces that recognise each other as mirrors without losing their own distinctness.",
      "This is love in its most balanced form — not possession, not merger, but the profoundly generous act of seeing and being seen.",
      "The original recognition — the first moment two things met and understood that they were the same fire in different vessels.",
    ],
    reversedDescriptions: [
      "Imbalance or miscommunication is straining a connection. Address it directly.",
      "A partnership is dissolving or needs renegotiation.",
      "Codependence or unequal exchange is distorting what could be genuine.",
      "The mirror broken — the relationship that can no longer reflect the self clearly.",
      "The primordial recognition denied: two fires that cannot see themselves in each other.",
    ],
  },
  {
    id: 38,
    name: "Three of Cups",
    arcana: "minor",
    suit: "cups",
    number: 3,
    descriptions: [
      "Community, celebration, and shared joy are available. Participate.",
      "The abundance of this moment is meant to be shared. Let yourself enjoy it without guilt.",
      "There is a rare kind of magic in being fully celebrated by people who truly know you. This is that moment — do not deflect it.",
      "Friendship as a creative force: the conversations, the laughter, the shared history that sustains through the lean times.",
      "The first feast — the original discovery that joy multiplied by presence becomes something entirely new.",
    ],
    reversedDescriptions: [
      "Social exhaustion or isolation is asking for honest attention.",
      "Overindulgence is masking something more important. What is underneath?",
      "Community feels forced or superficial. Authentic connection is what is needed.",
      "The celebration that excludes — the feast where someone is always seated outside.",
      "The primordial feast turned to excess: celebration that no longer knows what it is celebrating.",
    ],
  },
  {
    id: 39,
    name: "Four of Cups",
    arcana: "minor",
    suit: "cups",
    number: 4,
    descriptions: [
      "Discontent is present. Before acting, ask what is actually missing.",
      "A pause for genuine introspection can clarify what you truly want.",
      "The fourth cup is offered but not yet seen. Sometimes the gift arrives precisely when we are turned away from gratitude.",
      "Apathy is not a character flaw — it is a signal. What needs attention is asking for your attention in the only language available to it right now.",
      "The original restlessness — creation noticing its own incompleteness for the first time.",
    ],
    reversedDescriptions: [
      "Emerging from a period of withdrawal or ennui. The world is reaching you again.",
      "Missed opportunities through excessive rumination are becoming visible. Act now.",
      "The depression has served its purpose; now it is a habit. It is time to move.",
      "The cup remains unrecognised even when it is directly offered — apathy as willful blindness.",
      "The primordial restlessness become stasis: creation that notices its incompleteness and refuses to address it.",
    ],
  },
  {
    id: 40,
    name: "Five of Cups",
    arcana: "minor",
    suit: "cups",
    number: 5,
    descriptions: [
      "Grief is real and deserves space. And behind you, something remains.",
      "Loss needs to be felt fully before it can be integrated.",
      "The three spilled cups are the loss. The two standing cups behind you are the life still available. Both are true. You can turn around.",
      "Grief without integration becomes the whole story. Integration without grief is denial. Both cups, spilled and standing, are yours.",
      "The first mourning — the original loss, and the first discovery that something remains even after the worst.",
    ],
    reversedDescriptions: [
      "Recovery from grief is underway. Let yourself move forward without guilt.",
      "The loss is being held so tightly it prevents seeing what remains.",
      "Forgiveness — of yourself or another — is the work that loss has been trying to lead you toward.",
      "Grief become identity — the self that can no longer remember a self before the loss.",
      "The primordial mourning without the return: the two remaining cups unseen forever.",
    ],
  },
  {
    id: 41,
    name: "Six of Cups",
    arcana: "minor",
    suit: "cups",
    number: 6,
    descriptions: [
      "The past offers genuine nourishment. Let yourself receive it.",
      "Innocence, memory, and emotional simplicity are refreshing something important.",
      "This is not nostalgia as escape but memory as medicine — the capacity to return to what was once whole in order to carry that wholeness forward.",
      "The gift of the child-self: the part of you that loved without condition is still present. It has not been cancelled by everything that came after.",
      "The original memory — the moment creation remembered its beginning and felt tender about it.",
    ],
    reversedDescriptions: [
      "Nostalgia is becoming avoidance. The past is a resource, not a residence.",
      "An old pattern or relationship is reactivating. Examine with clear eyes.",
      "Sentimentality is colouring a present situation with a past it does not share.",
      "The child-self not as gift but as wound: the past that rules rather than nourishes.",
      "The original memory turned into a prison: creation that cannot move forward because it cannot leave its beginning.",
    ],
  },
  {
    id: 42,
    name: "Seven of Cups",
    arcana: "minor",
    suit: "cups",
    number: 7,
    descriptions: [
      "Too many options are making it hard to see clearly. Focus is needed.",
      "Fantasy and wishful thinking need to be distinguished from genuine possibility.",
      "The cups hold everything your imagination has conjured — beauty, dread, desire, illusion. The work is not choosing the best cup but learning to see which ones are real.",
      "The abundant imagination that cannot yet choose is not a failure — it is a richness in need of discernment.",
      "The primordial proliferation of possibility — the moment before creation chose, when everything that could be was equally real.",
    ],
    reversedDescriptions: [
      "Clarity is arriving after a period of confusion. A choice is becoming possible.",
      "Illusions are dispelling — what remains is what is real.",
      "The fantasies have been examined and the viable ones are separating from the merely appealing.",
      "Paralysis by possibility: the imagination that generates without the will to choose.",
      "The primordial proliferation without resolution: creation that never chose, and so all the cups remain full and none are ever drunk.",
    ],
  },
  {
    id: 43,
    name: "Eight of Cups",
    arcana: "minor",
    suit: "cups",
    number: 8,
    descriptions: [
      "Something familiar needs to be left behind in order to grow.",
      "Walking away is not failure — sometimes it is the most important form of wisdom.",
      "The cups are not broken — they are simply no longer enough. The decision to move on, when it comes from deep knowing rather than avoidance, is an act of profound self-respect.",
      "What you are leaving is real. What you are moving toward is not yet visible. Both truths must be held simultaneously.",
      "The first departure — the original moment creation looked at what it had built and understood that more was possible.",
    ],
    reversedDescriptions: [
      "Staying out of fear rather than genuine commitment. Examine the real reason.",
      "The departure is being delayed past the point of wisdom. What is being avoided?",
      "A fear of abandonment is being projected onto a situation that requires leaving.",
      "The self that cannot leave even what no longer serves it — the cups that hold long past their time.",
      "The primordial departure refused: creation that sees the horizon and will not move toward it.",
    ],
  },
  {
    id: 44,
    name: "Nine of Cups",
    arcana: "minor",
    suit: "cups",
    number: 9,
    descriptions: [
      "Wishes and desires are being fulfilled. Receive the satisfaction without suspicion.",
      "Contentment is real and available. You are allowed to feel it.",
      "This is the card of genuine pleasure — not the frantic pursuit of happiness but its actual arrival. The challenge is being present enough to notice.",
      "Everything you have wanted emotionally is here or is coming. Trust it. Pleasure is not a warning.",
      "The original satisfaction — the moment creation completed something and felt, fully, that it was good.",
    ],
    reversedDescriptions: [
      "Complacency is substituting for genuine contentment. Examine the difference.",
      "Material or emotional satisfaction is present but hollow. What is missing?",
      "Overindulgence as a substitute for what is actually needed.",
      "The wish fulfilled but not enjoyed — the cup full and the mouth closed.",
      "The primordial satisfaction withheld: creation completing something and finding no pleasure in it.",
    ],
  },
  {
    id: 45,
    name: "Ten of Cups",
    arcana: "minor",
    suit: "cups",
    number: 10,
    descriptions: [
      "Harmony, family, and emotional fulfilment are available. Let yourself rest in them.",
      "A period of genuine happiness and belonging is here or near.",
      "The rainbow of ten cups is not an achievement — it is a recognition of what was always there. The work was learning to see it.",
      "Relational wholeness: the deep peace of knowing you are loved, that you belong, and that what you have built together is real.",
      "The original belonging — the first time the universe looked at the life within it and felt at home.",
    ],
    reversedDescriptions: [
      "Family or community harmony is disrupted. What needs tending?",
      "Outward happiness conceals inner discord. Attend to what is beneath the surface.",
      "Disconnection from what matters most is making even real blessings feel hollow.",
      "The rainbow obscured — the life that contains everything it needs but cannot see it.",
      "The primordial belonging denied: the universe that built everything it needed for home and then forgot to live in it.",
    ],
  },
  {
    id: 46,
    name: "Page of Cups",
    arcana: "minor",
    suit: "cups",
    number: 11,
    descriptions: [
      "A message from the heart, or an unexpected emotional insight, is arriving.",
      "Stay open to intuition and imagination. Something surprising wants to speak.",
      "The fish emerging from the cup — unexpected wisdom from the depths of feeling. Do not dismiss the strange or the tender just because it is unexpected.",
      "Emotional creativity in its first form: the heart that has not yet learned what it is not allowed to feel.",
      "The first emotional stirring — the original moment feeling surprised the universe by arriving.",
    ],
    reversedDescriptions: [
      "Emotional immaturity or naivety is affecting a situation. Grow through it.",
      "Creative daydreaming has decoupled from productive action.",
      "Unreliable emotional information — the fish in the cup is a fantasy, not a message.",
      "Feeling overwhelmed by emotion that has not yet been translated into wisdom.",
      "The first emotional stirring gone awry: the feeling that cannot be contained or directed.",
    ],
  },
  {
    id: 47,
    name: "Knight of Cups",
    arcana: "minor",
    suit: "cups",
    number: 12,
    descriptions: [
      "Follow your heart toward something that genuinely moves you.",
      "Romance, idealism, and emotional pursuit are in motion.",
      "The Knight of Cups rides slowly because beauty is everywhere and he refuses to rush past it. The quest is real and so is the tendency to get lost in the quest itself.",
      "Lead with feeling, but do not let feeling become the only compass. The heart is the most honest guide available — and the most easily deceived.",
      "The original romantic — the first quest undertaken for love rather than conquest.",
    ],
    reversedDescriptions: [
      "Moods and emotions are inconsistent, making reliable action difficult.",
      "Romantic idealisation is obscuring practical reality.",
      "The pursuit of feeling is becoming an end in itself rather than a means to connection.",
      "The knight who has made the quest about the riding — beauty noticed everywhere and arrived at nowhere.",
      "The primordial romance without the beloved: feeling that mistakes its own motion for arrival.",
    ],
  },
  {
    id: 48,
    name: "Queen of Cups",
    arcana: "minor",
    suit: "cups",
    number: 13,
    descriptions: [
      "Lead with empathy and intuition. They are your clearest resources right now.",
      "Deep emotional intelligence is available — yours or someone near you.",
      "The Queen of Cups holds the cup closed because what it contains is too sacred for ordinary handling. She knows the difference between feeling and indulgence.",
      "This is the mastery of emotional knowing: fluid without being formless, compassionate without being consumed.",
      "The original nurturer — the first form of love that knew how to hold without possessing.",
    ],
    reversedDescriptions: [
      "Emotional boundaries are absent or collapsed. Care is being given at cost to self.",
      "Empathy has become projection — feeling for others what is actually yours.",
      "Moodiness or emotional manipulation is operating below the conscious level.",
      "The cup tilted — the holder of feeling who has begun to drown in it.",
      "The primordial nurturer overwhelmed: love that has forgotten how to receive as well as give.",
    ],
  },
  {
    id: 49,
    name: "King of Cups",
    arcana: "minor",
    suit: "cups",
    number: 14,
    descriptions: [
      "Emotional maturity and compassionate authority are the qualities called for.",
      "Lead from wisdom about the heart — yours and others'.",
      "The King of Cups sits calmly on the sea because he has learned the sea will not become the land, and the land will not become the sea. He rules both from the throne of their tension.",
      "Mastery here is not control of emotion but mastery of the self within emotion — the capacity to feel fully while acting wisely.",
      "The original emotional authority — the king who rules through feeling rather than force.",
    ],
    reversedDescriptions: [
      "Emotional volatility or manipulation is affecting leadership or relationships.",
      "The mature emotional wisdom exists but is being suppressed or bypassed.",
      "External calm masks internal turbulence. The throne is on the water — but the water is rising.",
      "The king overwhelmed by his own sea — authority that has lost its ground.",
      "The primordial emotional king dethroned: the capacity for feeling mistaken for weakness.",
    ],
  },
  // Minor Arcana — Swords
  {
    id: 50,
    name: "Ace of Swords",
    arcana: "minor",
    suit: "swords",
    number: 1,
    descriptions: [
      "A moment of mental clarity is available. Use it.",
      "Truth, reason, and discernment are cutting through confusion.",
      "The blade offered here is not a weapon — it is the capacity for clear thought. Wielded with integrity, it separates the real from the imagined.",
      "This is the gift of the mind at its most precise: the ability to see through pretense, including your own.",
      "The original word — the first thought that cut through the void and named something true.",
    ],
    reversedDescriptions: [
      "Confusion or miscommunication is clouding a situation. Seek clarity before acting.",
      "The sharp mind is being turned against itself — self-criticism as self-destruction.",
      "Truth is present but being avoided. The blade laid down still cuts.",
      "The mind so sharp it has begun to cut what it was meant to protect.",
      "The original word withheld: the truth that refuses to speak itself into being.",
    ],
  },
  {
    id: 51,
    name: "Two of Swords",
    arcana: "minor",
    suit: "swords",
    number: 2,
    descriptions: [
      "A difficult decision is being held in suspension. Gather more information.",
      "Balance is being maintained by refusing to tip either way. How long can this continue?",
      "The blindfold is not ignorance — it is the deliberate choice to feel your way toward a decision when sight cannot provide the answer.",
      "Stalemate has its own intelligence. Sometimes the wisest course is to acknowledge that no choice is currently available without more information.",
      "The first impasse — the original moment two equal forces met and neither could yield.",
    ],
    reversedDescriptions: [
      "A decision that has been avoided is now becoming urgent.",
      "The information needed is available — the reluctance to look is the only barrier.",
      "False peace maintained through deliberate ignorance. The blindfold must come off.",
      "The two swords lowered — the stalemate finally broken, for better or worse.",
      "The primordial impasse resolved by collapse rather than wisdom.",
    ],
  },
  {
    id: 52,
    name: "Three of Swords",
    arcana: "minor",
    suit: "swords",
    number: 3,
    descriptions: [
      "Grief and heartache need to be felt, not managed.",
      "The clarity that follows loss is painful and necessary.",
      "The swords are not punishments — they are the exact, sharp shape of the truth. What they have cut through was already failing.",
      "Sorrow faced directly has a shorter lifespan than sorrow avoided. Let it pass through you.",
      "The original heartbreak — the first time the universe felt the precise shape of what it had lost.",
    ],
    reversedDescriptions: [
      "Recovery from grief is in process. Tend it with patience.",
      "Sorrow is being repressed rather than released. The heart needs to mourn.",
      "Reopening of old wounds — the sword removed before the wound had fully healed.",
      "The grief become chronic — the heart that has forgotten life without the swords.",
      "The primordial heartbreak without healing: loss that permanently remakes rather than eventually releasing.",
    ],
  },
  {
    id: 53,
    name: "Four of Swords",
    arcana: "minor",
    suit: "swords",
    number: 4,
    descriptions: [
      "Rest and recuperation are not luxuries — they are necessary right now.",
      "Take the break. The sword will still be there when you return.",
      "The truce you are being offered — with yourself, with the world, with the relentless pace — is legitimate. Receive it.",
      "Recovery is its own form of preparation. The knight in the tomb is not surrendering; they are gathering the strength to rise.",
      "The original rest — the moment creation paused after the effort and let the silence in.",
    ],
    reversedDescriptions: [
      "Restlessness is preventing the rest that is genuinely needed.",
      "Recovery has been completed; remaining in the resting position is now stagnation.",
      "Burnout approaches if rest continues to be refused.",
      "The four swords lowered too soon — the truce broken before the healing was done.",
      "The primordial rest refused: creation that cannot stop, even when stopping would save it.",
    ],
  },
  {
    id: 54,
    name: "Five of Swords",
    arcana: "minor",
    suit: "swords",
    number: 5,
    descriptions: [
      "Victory at too high a cost. Consider what you have actually won.",
      "A conflict has produced a result, but the aftermath requires honest assessment.",
      "Taking all the swords is within your power. It is also worth asking if you need them all, and what carrying them will cost you going forward.",
      "Winning by any means is not the same as winning. What kind of victor do you want to be?",
      "The original pyrrhic victory — the first time creation won and found the field empty.",
    ],
    reversedDescriptions: [
      "Movement beyond a painful conflict is beginning. Leave it behind you.",
      "Lingering in the aftermath of conflict past its usefulness. Resolve to let go.",
      "Guilt about the way a victory was won is providing an important signal. Listen to it.",
      "The defeated picking up what the victor discarded — power shifting after the hollow win.",
      "The primordial victory examined and found empty: creation that won everything and gained nothing.",
    ],
  },
  {
    id: 55,
    name: "Six of Swords",
    arcana: "minor",
    suit: "swords",
    number: 6,
    descriptions: [
      "You are moving away from difficulty toward calmer waters. Keep going.",
      "Transition and passage are underway — not easy, but necessary.",
      "The swords are still in the boat because the past does not disappear — it travels with you. But the direction has changed.",
      "Sometimes the only available choice is the lesser difficulty. The far shore may not be paradise, but it is better than the storm you are leaving.",
      "The original crossing — the first departure from a known difficulty toward an unknown calm.",
    ],
    reversedDescriptions: [
      "A necessary departure is being postponed. The calmer waters are waiting.",
      "Travel or transition is delayed or blocked. Examine what is holding you.",
      "Returning to difficulty that was already left — the boat that turned around.",
      "The passage resisted — the swords driven deeper into the boat, the far shore invisible.",
      "The primordial crossing refused: creation that cannot leave the storm because the storm has become home.",
    ],
  },
  {
    id: 56,
    name: "Seven of Swords",
    arcana: "minor",
    suit: "swords",
    number: 7,
    descriptions: [
      "Strategic thinking is needed. Not everything needs to be confronted directly.",
      "Something is not fully disclosed in a situation. Investigate carefully.",
      "The strategy works — but only if it is honest with itself about what it is. Tactical retreat and outright deception are not the same thing.",
      "You are being clever. The question worth asking is whether cleverness is the right tool here.",
      "The original strategy — the first time creation chose cunning over confrontation.",
    ],
    reversedDescriptions: [
      "Deception — your own or another's — is being uncovered. Truth is surfacing.",
      "A strategic plan has failed or is unduly risky. Reassess.",
      "Guilt about a compromise or evasion is asking for honest self-examination.",
      "The thief caught — the strategy that worked until the moment it did not.",
      "The primordial cunning turned against itself: the strategy that deceived only its architect.",
    ],
  },
  {
    id: 57,
    name: "Eight of Swords",
    arcana: "minor",
    suit: "swords",
    number: 8,
    descriptions: [
      "You feel trapped, but the situation is less fixed than it appears.",
      "The blindfold is removable. Look at what is actually constraining you.",
      "The swords form a cage only so long as you believe they do. The limitation is largely mental — which is both the hardest and the most freeing thing to hear.",
      "Your own thinking is the primary prison. This is not blame — it is the exact location of the key.",
      "The original entrapment — the first time creation convinced itself that the walls were real.",
    ],
    reversedDescriptions: [
      "The mental constraints are loosening. Freedom becomes possible through self-knowledge.",
      "Escaping a restrictive situation — or a restrictive pattern of thought — is underway.",
      "The blindfold remains even after the swords have been removed. Old limitations outlasting their source.",
      "The cage made permanent — the belief in walls so complete that the open gate is never found.",
      "The primordial entrapment without release: creation that chose the walls so thoroughly it forgot it could choose otherwise.",
    ],
  },
  {
    id: 58,
    name: "Nine of Swords",
    arcana: "minor",
    suit: "swords",
    number: 9,
    descriptions: [
      "Anxiety and dark thoughts are louder than usual. They are not prophecy.",
      "The night terrors are real feelings, not facts. Distinguish between them.",
      "The swords above the bed are not entering the room — they are manifestations of fear. What they represent is real enough; what they predict is not.",
      "The darkest hour of the mind is also the hour when honesty about what is actually happening becomes possible. What is the anxiety protecting you from knowing?",
      "The original dread — the first time the mind turned its capacity for imagination against itself.",
    ],
    reversedDescriptions: [
      "Emerging from a period of anxiety or depression. The weight is lifting.",
      "The inner critic has been given too much authority. Reclaim the floor.",
      "What was imagined as catastrophic is being revealed as manageable.",
      "The nine swords descending — anxiety that has moved from thought to manifestation.",
      "The primordial dread without dawn: the mind's imagination permanently arrayed against itself.",
    ],
  },
  {
    id: 59,
    name: "Ten of Swords",
    arcana: "minor",
    suit: "swords",
    number: 10,
    descriptions: [
      "A painful ending is complete. What follows now can only be better.",
      "The lowest point has been reached. The only direction from here is toward recovery.",
      "The ten swords are definitive — but the dawn on the horizon is equally definitive. Endings of this magnitude always precede beginnings of equal magnitude.",
      "This is not defeat. This is the completion of a particular cycle of suffering. It is finished.",
      "The original nadir — the first time creation reached the absolute lowest point and discovered the ground.",
    ],
    reversedDescriptions: [
      "Recovery is beginning after significant loss or failure.",
      "The worst has passed but its shadow lingers. Be patient with the emergence.",
      "A catastrophic ending is being resisted past the point of wisdom. Let it complete.",
      "The swords deepened further — rock bottom not yet reached, and the fall continues.",
      "The primordial nadir without the dawn: the lowest point reached and the horizon remaining dark.",
    ],
  },
  {
    id: 60,
    name: "Page of Swords",
    arcana: "minor",
    suit: "swords",
    number: 11,
    descriptions: [
      "Alert curiosity and quick thinking are available to you.",
      "New ideas or important information require careful examination.",
      "The Page of Swords is all watching and no conclusions — the pure, pre-judgmental attention that makes genuine understanding possible.",
      "The mind at its most alive: curious without agenda, sharp without cruelty, questioning without destruction.",
      "The original question — the first curiosity that did not yet know what answer it would find.",
    ],
    reversedDescriptions: [
      "Gossip, harsh words, or scattered thinking are creating problems.",
      "Curiosity has become nosiness or information is being gathered for harmful use.",
      "Mental energy is scattered across too many inputs. Focus is needed.",
      "The sword raised without the steadiness to use it wisely — sharp wit without wisdom.",
      "The primordial question weaponised: curiosity that cuts where it should illuminate.",
    ],
  },
  {
    id: 61,
    name: "Knight of Swords",
    arcana: "minor",
    suit: "swords",
    number: 12,
    descriptions: [
      "Act decisively and with conviction. The moment is here.",
      "Truth and direct communication are your most powerful tools right now.",
      "The Knight of Swords charges forward so quickly that the strategy is pure momentum — and the momentum is sometimes the strategy.",
      "Speed and clarity combined are formidable. Just ensure the direction was worth the charge.",
      "The original decisive act — the first time creation committed completely to a direction without reservation.",
    ],
    reversedDescriptions: [
      "Impulsiveness or aggression is cutting off possibilities rather than opening them.",
      "The charge has outrun both wisdom and necessity. Rein in the momentum.",
      "Verbal aggression or harsh communication is alienating those you need.",
      "The knight that has lost the cause but kept the speed — all charge, no direction.",
      "The primordial decisive act inverted: commitment without purpose, speed without destination.",
    ],
  },
  {
    id: 62,
    name: "Queen of Swords",
    arcana: "minor",
    suit: "swords",
    number: 13,
    descriptions: [
      "Clear-eyed truth and sharp discernment are your gifts right now.",
      "Speak what is true, even when it is difficult.",
      "The Queen of Swords has earned her clarity through experience. What looks like coldness is the discipline to see without distortion.",
      "She holds the sword upright because truth does not need to attack — it simply needs to stand.",
      "The original clarity — the mind that learned, through everything it endured, to see exactly what is there.",
    ],
    reversedDescriptions: [
      "Bitterness or pain is sharpening the tongue past the point of usefulness.",
      "Clarity has become cruelty. The truth is present but the delivery is injuring.",
      "A wound is shaping a judgment that should be impartial.",
      "The queen who has forgotten that the sword is for truth, not for wounding.",
      "The primordial clarity inverted: the mind that sees everything and uses the sight only to wound.",
    ],
  },
  {
    id: 63,
    name: "King of Swords",
    arcana: "minor",
    suit: "swords",
    number: 14,
    descriptions: [
      "Authority grounded in clear thinking and ethical commitment.",
      "Lead with intellectual rigour and fairness.",
      "The King of Swords is the mind that has learned to govern itself: precise, fair, and committed to truth even when it is uncomfortable.",
      "His authority does not depend on force because it depends on something harder to fake: the absolute consistency of his reasoning and ethics.",
      "The original just ruler — the mind that achieved mastery over itself and used it in service of others.",
    ],
    reversedDescriptions: [
      "Intellectual arrogance or the abuse of authority is creating harm.",
      "Clear thinking is being bypassed in favour of ideology or personal bias.",
      "The ethical commitments of a position have been compromised by power.",
      "The tyrant king — authority that has forgotten it exists to serve truth rather than itself.",
      "The primordial just mind corrupted: the clarity that served only to justify the will to power.",
    ],
  },
  // Minor Arcana — Pentacles
  {
    id: 64,
    name: "Ace of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 1,
    descriptions: [
      "A new material opportunity is being offered. Receive it and begin.",
      "Prosperity, stability, and tangible beginnings are available right now.",
      "The golden pentacle is more than money — it is the seed of everything that can be made real, touched, built, and sustained.",
      "Earth holds the offering and will hold what you make of it. Begin with both hands open.",
      "The original gift of matter — the first form that gave substance to everything that would follow.",
    ],
    reversedDescriptions: [
      "Financial opportunity is blocked or its terms are not as they appear.",
      "A promising beginning is struggling to take root. Examine the foundations.",
      "Material focus is becoming greed or attachment. Reassess your relationship with resources.",
      "The seed offered but not planted — the pentacle that never became anything.",
      "The primordial gift of matter withheld: the world that refused its own substance.",
    ],
  },
  {
    id: 65,
    name: "Two of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 2,
    descriptions: [
      "Balancing multiple priorities is the current challenge. You can do it.",
      "Flexibility and adaptability are your greatest assets in flux.",
      "The juggler keeps the coins in the air not through strength but through the constant, subtle adjustment of attention. It is demanding — and it is working.",
      "Life in motion requires constant recalibration. The fluency you are developing now is genuine skill.",
      "The original balance — the first dance between two equally real demands.",
    ],
    reversedDescriptions: [
      "Too many balls are in the air and the juggling is failing. Prioritise ruthlessly.",
      "Financial imbalance or disorganisation needs direct attention.",
      "The appearance of balance is being maintained while the reality deteriorates.",
      "One of the coins has already dropped — the juggler is behind the rhythm.",
      "The primordial balance lost: two demands that cannot be met simultaneously and the refusal to choose between them.",
    ],
  },
  {
    id: 66,
    name: "Three of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 3,
    descriptions: [
      "Collaboration and skilled effort are producing real results.",
      "The craft is being recognised. Your contribution matters.",
      "Three people with three different forms of knowledge are making something that none of them could make alone. This is what mastery looks like in action.",
      "The cathedral is built by the collaboration — not one genius alone, but a team of genuine skill and genuine listening.",
      "The original collaboration — the first time creation understood that some things can only be built together.",
    ],
    reversedDescriptions: [
      "Misalignment in a team or project is undermining collective effort.",
      "Skill exists but is not being recognised, or is not being applied well.",
      "Working in isolation when collaboration is what is actually needed.",
      "The three craftspeople unable to share the plan — each building in a different direction.",
      "The primordial collaboration refused: creation that insisted on solitude and built something lesser.",
    ],
  },
  {
    id: 67,
    name: "Four of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 4,
    descriptions: [
      "Security is worth protecting — but check whether protection has become hoarding.",
      "What is being held is genuinely valuable. So is the act of sharing.",
      "The pentacles are held close because the world has been uncertain. The discernment needed now is between prudent security and paralysing possession.",
      "Resources conserved for the right moment are wisdom. Resources conserved to the point where no moment is ever right have become their own prison.",
      "The original conserving — the first time creation held what it had made because it was afraid of losing it.",
    ],
    reversedDescriptions: [
      "Releasing an overly tight grip on resources or control is bringing relief.",
      "Greed or miserliness is blocking abundance rather than protecting it.",
      "Insecurity is being addressed through accumulation rather than through the real work.",
      "The coins let go at last — or the coins scattered by forces the holder could not contain.",
      "The primordial conserving become catastrophe: the grip loosened by loss rather than wisdom.",
    ],
  },
  {
    id: 68,
    name: "Five of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 5,
    descriptions: [
      "Hardship is real but not permanent. Help is closer than it appears.",
      "Material or emotional scarcity can obscure the resources that remain available.",
      "The light in the window of the church is not locked — the door is open. The only question is whether the difficulty of the moment is preventing you from looking up.",
      "Poverty — of resources, of connection, of spirit — is a real condition. It is also, sometimes, a narrowing of perception. Both can be true.",
      "The original scarcity — the first time creation experienced lack, and the first time it discovered what endurance means.",
    ],
    reversedDescriptions: [
      "Recovery from financial or emotional hardship is beginning. Accept the help being offered.",
      "The worst of the scarcity has passed, but the mentality of lack persists. Update the inner map.",
      "Help is being refused out of pride or shame. This is worth examining.",
      "The light in the window seen at last — the door opened, the sanctuary entered.",
      "The primordial scarcity without relief: the church door locked, the light unreachable.",
    ],
  },
  {
    id: 69,
    name: "Six of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 6,
    descriptions: [
      "Generosity and the right exchange of resources are highlighted.",
      "What you give and receive matters — and so does how.",
      "The merchant weighs the coins carefully, giving what is needed and receiving what is owed. Generosity is not the same as indiscriminate giving.",
      "The right relationship with resources — neither hoarding nor squandering, neither servility nor dominance — is a practice that never finishes.",
      "The original exchange — the first time creation understood that giving and receiving are two faces of the same act.",
    ],
    reversedDescriptions: [
      "Imbalance in giving and receiving — too much in one direction — is creating resentment.",
      "Charity is being given with strings, or received with hidden cost.",
      "Power dynamics in financial or resource relationships need examination.",
      "The scale tipped — generosity become control, or giving without the capacity to receive.",
      "The primordial exchange corrupted: giving and receiving become weapons rather than gifts.",
    ],
  },
  {
    id: 70,
    name: "Seven of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 7,
    descriptions: [
      "Patient effort is yielding results. This is the right time to evaluate progress.",
      "The harvest is coming — but first, an honest assessment of what has grown.",
      "The farmer pauses to look at what has been growing. The pause is not laziness — it is the intelligence to understand what you are actually tending.",
      "Long-term investment — in work, in relationships, in craft — requires these moments of clear-eyed review.",
      "The original patient labour — the first act of sustained creation that required waiting to see what it became.",
    ],
    reversedDescriptions: [
      "Impatience is leading to premature harvesting or abandonment of long-term plans.",
      "The effort invested has not produced the expected results. Reassess the approach.",
      "Procrastination is disguising itself as patience. The work is not being done.",
      "The farmer who has waited too long — the fruit past ripeness, the harvest become waste.",
      "The primordial patience without its fruit: creation that waited and waited and found nothing.",
    ],
  },
  {
    id: 71,
    name: "Eight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 8,
    descriptions: [
      "Dedicated practice and mastery through repetition are the path right now.",
      "The craft is developing. Do not rush the process.",
      "The craftsman strikes the pentacle again and again — not because the first one was wrong, but because each strike teaches something the previous one could not.",
      "Diligence is not glamorous. It is also the only path to genuine mastery.",
      "The original practice — the first repeated effort that turned raw capacity into skill.",
    ],
    reversedDescriptions: [
      "Perfectionism is preventing completion. Good work done is better than perfect work imagined.",
      "The repetition has become mindless — effort without improvement.",
      "Cutting corners or laziness is producing inferior results. Return to proper craft.",
      "The craftsman who cannot stop striking — perfectionism become compulsion.",
      "The primordial practice without progress: the same blow struck forever, and nothing made.",
    ],
  },
  {
    id: 72,
    name: "Nine of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 9,
    descriptions: [
      "Self-sufficiency and the fruits of sustained effort are available to you.",
      "You have built something real. Enjoy what you have created.",
      "The garden is yours — cultivated by your own hand, sustained by your own wisdom. The falcon on the wrist is trained, not tamed.",
      "This is earned abundance: not luck, not inheritance, but the patient accumulation of genuine competence and genuine care.",
      "The original self-sufficiency — the first moment creation looked at what it had grown and needed nothing else.",
    ],
    reversedDescriptions: [
      "Over-reliance on external validation is diminishing genuine self-sufficiency.",
      "Financial independence is delayed or its foundations are not as solid as they appear.",
      "The fruits of labour are present but the capacity to enjoy them is absent.",
      "The garden neglected — the self-sufficiency that required maintenance, and maintenance refused.",
      "The primordial self-sufficiency exposed as isolation: the garden that became a fortress.",
    ],
  },
  {
    id: 73,
    name: "Ten of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 10,
    descriptions: [
      "Legacy, family wealth, and lasting abundance are highlighted.",
      "What you have built is large enough to sustain others.",
      "The ten pentacles form the Tree of Life — not just wealth, but the generational root system that makes wealth meaningful.",
      "This is what it looks like when material success and relational richness occur together. Both matter. Neither alone is complete.",
      "The original legacy — the first time creation built something that would outlast itself.",
    ],
    reversedDescriptions: [
      "Family disputes or loss of security are affecting foundations.",
      "Legacy is being built on unsound or unjust foundations. Examine the roots.",
      "Wealth is present but hollow — the family name without the family warmth.",
      "The ten pentacles scattered — the legacy dismantled by those who were meant to inherit it.",
      "The primordial legacy undone: the building that outlasted its builders but not its purpose.",
    ],
  },
  {
    id: 74,
    name: "Page of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 11,
    descriptions: [
      "New practical skills or material opportunities are worth serious attention.",
      "Study, learning, and laying groundwork are the right focus.",
      "The Page holds the pentacle like it is the most interesting thing in the world — because right now, in the beginning, it is. That quality of attention is the first requirement of mastery.",
      "The beginner's mind applied to practical matters: serious, curious, and willing to start at the beginning.",
      "The original student — the first apprenticeship, the first realisation that skill is built rather than given.",
    ],
    reversedDescriptions: [
      "Impracticality or lack of follow-through on material goals is creating stagnation.",
      "Learning is being approached carelessly or without genuine commitment.",
      "Get-rich-quick thinking is substituting for patient skill development.",
      "The pentacle dropped — the apprentice who lost interest before the lesson was learned.",
      "The primordial student who refuses to begin: the beginner's mind that will not suffer being a beginner.",
    ],
  },
  {
    id: 75,
    name: "Knight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 12,
    descriptions: [
      "Steady, methodical effort will get you further than bursts of brilliance right now.",
      "Reliability and thoroughness are your greatest assets.",
      "The Knight of Pentacles does not charge — he plods, and his plodding is more reliable than anyone else's gallop.",
      "Hard work, not inspiration, is the engine of what is being built here. That is not a diminishment.",
      "The original patient labour — the first slow, deliberate act of creation that built something permanent.",
    ],
    reversedDescriptions: [
      "Perfectionism or excessive caution is blocking progress. Good enough and done beats perfect and pending.",
      "Stubbornness is being mistaken for reliability. Adapt where adaptation is needed.",
      "The methodical approach has become mechanical — effort without thinking.",
      "The knight unmounted — the patience that has curdled into inertia.",
      "The primordial patient labour become obstinacy: creation that refuses to change its method even when the method fails.",
    ],
  },
  {
    id: 76,
    name: "Queen of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 13,
    descriptions: [
      "Practical nurturing and resourceful abundance are your gifts right now.",
      "Create a environment where those around you can thrive.",
      "The Queen of Pentacles holds the pentacle in her lap like a living thing — because in her hands, resources become nourishment.",
      "She is the abundance made practical: warm, competent, grounded in what actually sustains rather than what merely impresses.",
      "The original practical nurturer — the first care that turned resources into home.",
    ],
    reversedDescriptions: [
      "Work-life balance is disrupted. Practical obligations are crowding out deeper nourishment.",
      "Financial anxiety is creating a scarcity mentality that restricts generous action.",
      "The nurturing is present but directed outward to the point of self-neglect.",
      "The queen who holds the pentacle so tightly it cannot nourish — abundance hoarded rather than shared.",
      "The primordial practical nurturer without recipients: warmth with nowhere to go.",
    ],
  },
  {
    id: 77,
    name: "King of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 14,
    descriptions: [
      "Mastery of material reality and responsible stewardship are the qualities called for.",
      "Lead with practical wisdom and genuine generosity.",
      "The King of Pentacles has built an empire — not by conquest but by patient, intelligent care for what was entrusted to him.",
      "Abundance at this level is not a reward — it is a responsibility. He knows this, and it shows in every decision.",
      "The original steward — the first master of matter who understood that ownership is another word for responsibility.",
    ],
    reversedDescriptions: [
      "Materialism or financial irresponsibility is undermining genuine security.",
      "The abundance is being used for status rather than stewardship.",
      "Corruption of practical authority — the king who has mistaken wealth for wisdom.",
      "The empire built but not sustained — the king who cannot maintain what he built.",
      "The primordial steward who became the tyrant: mastery of matter turned to domination of those who depend on it.",
    ],
  },
];

export const CARD_BY_ID: Record<number, CardDefinition> = Object.fromEntries(
  CARDS.map((c) => [c.id, c])
);

export const RARITY_LABELS: Record<number, string> = {
  1: "Mundane",
  2: "Wandering",
  3: "Mystic",
  4: "Arcane",
  5: "Primordial",
};
