// Auto-generated by lockbox — do not edit
// Modify the relevant clear.json/secret.json files and run `lockbox generate`
// Do not import directly — use your config loader

import { deepFreeze } from '@charcoalhq/lockbox';

export default deepFreeze({
  "betterAuthSecret": "ENC[Qsef2JO6htm/2O8cd8iCttnUrL5DMGgtlehQBenpDWhkfcVv/4FnM0AKu4xguRqRVkFLGYkMBVnLJEQmNDbTo+7l5Ci3WgjXEWs80wSWZVUcJRY=]",
  "betterAuthUrl": "http://localhost:3000",
  "databaseUrl": "postgresql://arkhana:arkhana@localhost:5432/arkhana",
  "nodeEnv": "development",
  "port": 3000
} as const);
